package cn.servicehub.knowledge.application;

import cn.servicehub.attachment.AttachmentProperties;
import cn.servicehub.attachment.application.StoragePort;
import cn.servicehub.attachment.application.VirusScanPort;
import cn.servicehub.audit.AuditEvent;
import cn.servicehub.audit.AuditEventPublisher;
import cn.servicehub.catalog.application.ServiceCatalogService;
import cn.servicehub.iam.application.IamProjectionService;
import cn.servicehub.knowledge.domain.*;
import cn.servicehub.security.*;
import cn.servicehub.ticket.domain.Ticket;
import cn.servicehub.ticket.domain.TicketRepository;
import cn.servicehub.ticket.domain.TicketStatus;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.Instant;
import java.util.*;
import org.slf4j.MDC;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

/** Source files are private. Only a bounded, published plain-text version is previewable. */
@Service public class KnowledgeService {
 private static final int MAX_PREVIEW_BYTES=256*1024;
 private final KnowledgeRepository repo; private final StoragePort storage; private final VirusScanPort scanner; private final AttachmentProperties limits; private final CurrentUserProvider users; private final ObjectAuthorizationService auth; private final AuditEventPublisher audit; private final TicketRepository tickets; private final IamProjectionService iam; private final ServiceCatalogService catalogs; private final Clock clock=Clock.systemUTC();
 public KnowledgeService(KnowledgeRepository r,StoragePort s,VirusScanPort v,AttachmentProperties l,CurrentUserProvider u,ObjectAuthorizationService a,AuditEventPublisher e,TicketRepository t,IamProjectionService i,ServiceCatalogService c){repo=r;storage=s;scanner=v;limits=l;users=u;auth=a;audit=e;tickets=t;iam=i;catalogs=c;}
 public KnowledgeDocument importDocument(String title,String category,List<String> tags,List<String> catalogIds,MultipartFile file){CurrentUser actor=users.requireCurrentUser();String org=currentOrganization(actor);requireManagerScope(actor,org);List<String> scope=validateCatalogs(catalogIds);validateMetadata(title,category,tags);Imported imported=storeAndScan(file);String did="KDOC-"+UUID.randomUUID(),vid="KVER-"+UUID.randomUUID(),taskId="KIMP-"+UUID.randomUUID();var now=clock.instant();KnowledgePublicationStatus status=publicationStatus(imported);KnowledgeDocument d=new KnowledgeDocument(did,title.trim(),category,cleanTags(tags),org,scope,status,vid,actor.iamUserId(),now,now,null,null,null);KnowledgeDocumentVersion v=new KnowledgeDocumentVersion(vid,did,1,imported.key,imported.mediaType,imported.size,org,scope,status,null,now,null);KnowledgeImportTask task=task(taskId,did,actor,imported,now);try{repo.save(d,v,task);}catch(RuntimeException e){storage.delete(imported.key);throw e;}audit(actor,"KNOWLEDGE_IMPORTED",did,Map.of("status",status.name(),"scanOutcome",scanOutcome(imported),"organizationId",org,"catalogCount",String.valueOf(scope.size()),"mediaType",imported.mediaType,"sizeBytes",String.valueOf(imported.size)));return d;}
 public KnowledgeDocumentVersion importVersion(String id,MultipartFile file){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=managerDocument(actor,id);Imported imported=storeAndScan(file);var now=clock.instant();String vid="KVER-"+UUID.randomUUID();KnowledgePublicationStatus status=publicationStatus(imported);int next=repo.findVersions(id).stream().mapToInt(KnowledgeDocumentVersion::versionNumber).max().orElse(0)+1;KnowledgeDocumentVersion v=new KnowledgeDocumentVersion(vid,id,next,imported.key,imported.mediaType,imported.size,d.owningOrganizationId(),d.serviceCatalogItemIds(),status,null,now,null);KnowledgeImportTask task=task("KIMP-"+UUID.randomUUID(),id,actor,imported,now);try{repo.saveVersion(v,task);}catch(RuntimeException e){storage.delete(imported.key);throw e;}audit(actor,"KNOWLEDGE_VERSION_IMPORTED",id,Map.of("versionId",vid,"version",String.valueOf(next),"status",status.name(),"scanOutcome",scanOutcome(imported)));return v;}
 public List<KnowledgeDocument> list(String query,String category,String tag){CurrentUser actor=users.requireCurrentUser();validateSearch(query,category,tag);String org=currentOrganization(actor);return repo.findDocuments().stream().filter(d->publiclyReadable(org,d)).filter(d->matches(d,query,category,tag)).toList();}
 public KnowledgeDocument get(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);if(!publiclyReadable(currentOrganization(actor),d))throw new KnowledgeNotFoundException();return d;}
 public KnowledgeDocument workspaceDocument(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);boolean editable=Set.of(KnowledgePublicationStatus.DRAFT,KnowledgePublicationStatus.PENDING_REVIEW).contains(d.status())&&(d.creatorIamUserId().equals(actor.iamUserId())||managerScoped(actor,d));if(!editable)throw new KnowledgeNotFoundException();return d;}
 public List<KnowledgeDocumentVersion> versions(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);boolean publicReader=!actor.authorities().contains("ROLE_AUDITOR")&&publiclyReadable(currentOrganization(actor),d);boolean owner=d.creatorIamUserId().equals(actor.iamUserId())&&Set.of(KnowledgePublicationStatus.DRAFT,KnowledgePublicationStatus.PENDING_REVIEW).contains(d.status());boolean manager=managerScoped(actor,d)||auditorScoped(actor,d);if(!publicReader&&!owner&&!manager)throw new KnowledgeNotFoundException();return repo.findVersions(id).stream().filter(v->sameScope(d,v)).filter(v->manager||owner||v.status()==KnowledgePublicationStatus.PUBLISHED||v.status()==KnowledgePublicationStatus.SUPERSEDED).toList();}
 public KnowledgeDocument createDraft(String title,String category,List<String> tags,List<String> catalogIds,String content){CurrentUser actor=users.requireCurrentUser();String org=currentOrganization(actor);List<String> scope=validateCatalogs(catalogIds);validateMetadata(title,category,tags);byte[] body=validateManualContent(content);String did="KDOC-"+UUID.randomUUID(),vid="KVER-"+UUID.randomUUID();Instant now=clock.instant();String key="knowledge-manual/"+vid.toLowerCase(Locale.ROOT);storage.put(key,body);KnowledgeDocument d=new KnowledgeDocument(did,title.trim(),category,cleanTags(tags),org,scope,KnowledgePublicationStatus.DRAFT,vid,actor.iamUserId(),now,now,null,null,null);KnowledgeDocumentVersion v=new KnowledgeDocumentVersion(vid,did,1,key,"text/plain",body.length,org,scope,KnowledgePublicationStatus.DRAFT,null,now,null);try{repo.saveDraft(d,v);}catch(RuntimeException exception){storage.delete(key);throw exception;}audit(actor,"KNOWLEDGE_DRAFT_CREATED",did,Map.of("organizationId",org,"catalogCount",Integer.toString(scope.size())));return d;}
 public KnowledgeDocument updateDraft(String id,int expectedVersion,String title,String category,List<String> tags,List<String> catalogIds,String content){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument current=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);if(current.status()!=KnowledgePublicationStatus.DRAFT||!current.creatorIamUserId().equals(actor.iamUserId())||!currentOrganization(actor).equals(current.owningOrganizationId()))throw new KnowledgeNotFoundException();KnowledgeDocumentVersion old=repo.findVersion(current.currentVersionId()).filter(v->v.status()==KnowledgePublicationStatus.DRAFT&&sameScope(current,v)).orElseThrow(KnowledgeDraftConflictException::new);if(expectedVersion<1||old.versionNumber()!=expectedVersion)throw new KnowledgeDraftConflictException();validateMetadata(title,category,tags);List<String> scope=validateCatalogs(catalogIds);byte[] body=validateManualContent(content);String vid="KVER-"+UUID.randomUUID();Instant now=clock.instant();String key="knowledge-manual/"+vid.toLowerCase(Locale.ROOT);storage.put(key,body);KnowledgeDocument changed=new KnowledgeDocument(id,title.trim(),category,cleanTags(tags),current.owningOrganizationId(),scope,KnowledgePublicationStatus.DRAFT,vid,current.creatorIamUserId(),current.createdAt(),now,null,null,current.sourceTicketId());KnowledgeDocumentVersion version=new KnowledgeDocumentVersion(vid,id,expectedVersion+1,key,"text/plain",body.length,current.owningOrganizationId(),scope,KnowledgePublicationStatus.DRAFT,null,now,null);try{repo.updateDraft(changed,version,current.currentVersionId());}catch(RuntimeException exception){storage.delete(key);throw exception;}audit(actor,"KNOWLEDGE_DRAFT_UPDATED",id,Map.of("fromVersion",Integer.toString(expectedVersion),"toVersion",Integer.toString(expectedVersion+1)));return changed;}
 public KnowledgeDocument submitDraft(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);if(d.status()!=KnowledgePublicationStatus.DRAFT||!d.creatorIamUserId().equals(actor.iamUserId())||!currentOrganization(actor).equals(d.owningOrganizationId()))throw new KnowledgeNotFoundException();validateCatalogs(d.serviceCatalogItemIds());Instant now=clock.instant();repo.submitDraft(id,d.currentVersionId(),actor.iamUserId(),now);audit(actor,"KNOWLEDGE_DRAFT_SUBMITTED",id,Map.of("versionId",d.currentVersionId()));return repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);}
 public void deleteDraft(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);if(d.status()!=KnowledgePublicationStatus.DRAFT||!d.creatorIamUserId().equals(actor.iamUserId()))throw new KnowledgeNotFoundException();KnowledgeDocumentVersion version=repo.findVersion(d.currentVersionId()).orElseThrow(KnowledgeNotFoundException::new);if(!repo.deleteDraft(id,actor.iamUserId()))throw new KnowledgeNotFoundException();storage.delete(version.attachmentStorageKey());audit(actor,"KNOWLEDGE_DRAFT_DELETED",id,Map.of());}
 public List<KnowledgeDocument> workbench(WorkbenchSection section){CurrentUser actor=users.requireCurrentUser();String org=currentOrganization(actor);return switch(section){case MY_DRAFTS->repo.findDocuments().stream().filter(d->d.creatorIamUserId().equals(actor.iamUserId())&&d.status()==KnowledgePublicationStatus.DRAFT).toList();case MY_SUBMISSIONS->repo.findDocuments().stream().filter(d->d.creatorIamUserId().equals(actor.iamUserId())&&d.status()!=KnowledgePublicationStatus.MIGRATION_PENDING).toList();case PENDING_REVIEW->{requireManagerRole(actor);yield repo.findDocuments().stream().filter(d->d.status()==KnowledgePublicationStatus.PENDING_REVIEW&&managerScoped(actor,d)).toList();}case REVIEWED->{requireManagerRole(actor);yield repo.findDocuments().stream().filter(d->managerScoped(actor,d)).filter(d->repo.findVersion(d.currentVersionId()).map(v->actor.iamUserId().equals(v.reviewerIamUserId())).orElse(false)).toList();}};}
 public List<KnowledgeDocument> favorites(){CurrentUser actor=users.requireCurrentUser();String org=currentOrganization(actor);return repo.findFavoriteDocumentIds(actor.iamUserId()).stream().map(repo::findDocument).flatMap(Optional::stream).filter(d->publiclyReadable(org,d)).toList();}
 public boolean favorite(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=publicDocument(actor,id);repo.saveFavorite(actor.iamUserId(),d.id(),clock.instant());audit(actor,"KNOWLEDGE_FAVORITED",id,Map.of());return true;}
 public boolean unfavorite(String id){CurrentUser actor=users.requireCurrentUser();publicDocument(actor,id);repo.deleteFavorite(actor.iamUserId(),id);audit(actor,"KNOWLEDGE_UNFAVORITED",id,Map.of());return false;}
 public boolean isFavorite(String id){CurrentUser actor=users.requireCurrentUser();publicDocument(actor,id);return repo.isFavorite(actor.iamUserId(),id);}
 public int currentVersionNumber(KnowledgeDocument d){return repo.findVersion(d.currentVersionId()).map(KnowledgeDocumentVersion::versionNumber).orElse(1);}
 public List<KnowledgeReviewItem> reviewQueue(){CurrentUser actor=users.requireCurrentUser();requireManagerRole(actor);return repo.findImportTasks().stream().map(t->repo.findDocument(t.documentId()).filter(d->managerScoped(actor,d)).map(d->new KnowledgeReviewItem(t,d,repo.findVersions(d.id()).stream().filter(v->v.status()==KnowledgePublicationStatus.PENDING_REVIEW&&sameScope(d,v)).toList())).orElse(null)).filter(Objects::nonNull).filter(i->!i.pendingVersions().isEmpty()||"REJECTED".equals(i.task().status())||"SCAN_FAILED".equals(i.task().status())).toList();}
 public KnowledgeDocument publish(String id,String versionId){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=managerDocument(actor,id);KnowledgeDocumentVersion v=repo.findVersion(versionId).filter(x->x.documentId().equals(id)&&sameScope(d,x)).orElseThrow(KnowledgeNotFoundException::new);if(v.status()!=KnowledgePublicationStatus.PENDING_REVIEW)throw new KnowledgeValidationException();validateCatalogs(d.serviceCatalogItemIds());repo.publish(id,versionId,actor.iamUserId());audit(actor,"KNOWLEDGE_PUBLISHED",id,Map.of("versionId",versionId,"organizationId",d.owningOrganizationId()));return repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);}
 public KnowledgeDocument archive(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=managerDocument(actor,id);if(d.status()!=KnowledgePublicationStatus.PUBLISHED)throw new KnowledgeValidationException();repo.archive(id,actor.iamUserId());audit(actor,"KNOWLEDGE_ARCHIVED",id,Map.of("currentVersionId",d.currentVersionId()));return repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);}
 /**
  * Converts only server-derived ticket metadata to a non-published draft. Source description,
  * comments and attachments are deliberately excluded: they frequently contain operational data.
  */
 public KnowledgeDocument createDraftFromResolvedTicket(String ticketId,String category,List<String> tags){
  CurrentUser actor=users.requireCurrentUser(); Ticket ticket=tickets.findById(ticketId).orElseThrow(KnowledgeNotFoundException::new);
  auth.requireAuthorized(actor,new ObjectAuthorizationRequest("ticket",ticket.id(),ObjectAction.APPROVE,Map.of("requesterIamUserId",ticket.requester().iamUserId(),"serviceCatalogItemId",ticket.serviceCatalogItem().id())));
  if(ticket.status()!=TicketStatus.RESOLVED&&ticket.status()!=TicketStatus.CLOSED)throw new KnowledgeValidationException();String org=ticket.requester().organizationId();List<String> scope=validateCatalogs(List.of(ticket.serviceCatalogItem().id()));requireManagerScope(actor,org);validateMetadata(ticket.title(),category,tags);
  String did="KDOC-"+UUID.randomUUID(),vid="KVER-"+UUID.randomUUID(); var now=clock.instant();
  byte[] safeStub=("来源工单："+ticket.id()+"\n\n发布前请由知识责任人补充经脱敏审核的处理步骤。\n").getBytes(StandardCharsets.UTF_8);
  Imported imported=storeAndScan(safeStub,"text/plain"); KnowledgePublicationStatus status=KnowledgePublicationStatus.DRAFT;
  KnowledgeDocument d=new KnowledgeDocument(did,normalizeTicketTitle(ticket.title()),category,cleanTags(tags),org,scope,status,vid,actor.iamUserId(),now,now,null,null,ticket.id());
  KnowledgeDocumentVersion v=new KnowledgeDocumentVersion(vid,did,1,imported.key,imported.mediaType,imported.size,org,scope,status,null,now,null);
  try{repo.saveDraft(d,v);}catch(RuntimeException e){storage.delete(imported.key);throw e;} audit(actor,"KNOWLEDGE_DRAFT_CREATED_FROM_TICKET",did,Map.of("sourceTicketId",ticket.id(),"status",status.name())); return d;
 }
 public FeedbackSummary feedback(String id,KnowledgeFeedback.FeedbackValue value,String reasonCode){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=publicDocument(actor,id);if(reasonCode!=null&&!reasonCode.matches("^[A-Z][A-Z0-9_]{1,63}$"))throw new KnowledgeValidationException();KnowledgeDocumentVersion v=repo.findVersion(d.currentVersionId()).filter(x->sameScope(d,x)&&x.status()==KnowledgePublicationStatus.PUBLISHED).orElseThrow(KnowledgeNotFoundException::new);repo.saveFeedback(new KnowledgeFeedback(d.id(),v.id(),actor.iamUserId(),value,reasonCode,clock.instant()));FeedbackSummary summary=feedbackSummary(d);audit(actor,"KNOWLEDGE_FEEDBACK_RECORDED",id,Map.of("value",value.name(),"reasonCode",reasonCode==null?"":reasonCode));return summary;}
 public FeedbackSummary feedbackSummary(String id){CurrentUser actor=users.requireCurrentUser();return feedbackSummary(publicDocument(actor,id));}
 public List<KnowledgeReviewCandidate> reviewCandidates(){CurrentUser actor=users.requireCurrentUser();requireManagerRole(actor);Instant now=clock.instant();return repo.findDocuments().stream().filter(d->d.status()==KnowledgePublicationStatus.PUBLISHED&&managerScoped(actor,d)).map(d->{FeedbackSummary s=feedbackSummary(d);boolean expired=d.reviewDueAt()!=null&&!d.reviewDueAt().isAfter(now);boolean low=s.total()>=3&&s.helpfulCount()*100<s.total()*60;String reason=expired?"REVIEW_DUE":low?"LOW_HELPFULNESS":null;return reason==null?null:new KnowledgeReviewCandidate(d.id(),d.title(),reason,d.reviewDueAt(),d.reviewOwnerIamUserId(),s.helpfulCount(),s.notHelpfulCount());}).filter(Objects::nonNull).toList();}
 public KnowledgeDocument completeReview(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=managerDocument(actor,id);if(d.status()!=KnowledgePublicationStatus.PUBLISHED)throw new KnowledgeValidationException();Instant next=clock.instant().plus(java.time.Duration.ofDays(180));repo.completeReview(id,actor.iamUserId(),next);audit(actor,"KNOWLEDGE_REVIEW_COMPLETED",id,Map.of("nextReviewDueAt",next.toString()));return repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);}
 public PlainTextPreview preview(String id){CurrentUser actor=users.requireCurrentUser();KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);boolean editableState=Set.of(KnowledgePublicationStatus.DRAFT,KnowledgePublicationStatus.PENDING_REVIEW).contains(d.status());boolean allowed=publiclyReadable(currentOrganization(actor),d)||editableState&&(d.creatorIamUserId().equals(actor.iamUserId())||managerScoped(actor,d));if(!allowed)throw new KnowledgeNotFoundException();KnowledgeDocumentVersion v=repo.findVersion(d.currentVersionId()).filter(x->sameScope(d,x)).orElseThrow(KnowledgeNotFoundException::new);if(!Set.of(KnowledgePublicationStatus.DRAFT,KnowledgePublicationStatus.PENDING_REVIEW,KnowledgePublicationStatus.PUBLISHED).contains(v.status())||!"text/plain".equals(v.detectedMediaType())||v.sizeBytes()>MAX_PREVIEW_BYTES)throw new KnowledgeValidationException();try(InputStream input=storage.open(v.attachmentStorageKey())){byte[] bytes=input.readNBytes(MAX_PREVIEW_BYTES+1);if(bytes.length>MAX_PREVIEW_BYTES)throw new KnowledgeValidationException();String body=new String(bytes,StandardCharsets.UTF_8);audit(actor,"KNOWLEDGE_PREVIEWED",id,Map.of("versionId",v.id()));return new PlainTextPreview(v.id(),v.versionNumber(),body);}catch(KnowledgeValidationException e){throw e;}catch(Exception e){throw new KnowledgeValidationException();}}
 private Imported storeAndScan(MultipartFile file){if(file==null||file.isEmpty()||file.getSize()>limits.maxFileSizeBytes())throw new KnowledgeValidationException();byte[] bytes;try{bytes=file.getBytes();}catch(Exception e){throw new KnowledgeValidationException();}String type=detect(bytes);if(type==null)throw new KnowledgeValidationException();String key="knowledge-quarantine/"+("KVER-"+UUID.randomUUID()).toLowerCase(Locale.ROOT);storage.put(key,bytes);VirusScanPort.ScanResult scan;try{scan=scanner.scan(key,bytes);}catch(RuntimeException e){scan=new VirusScanPort.ScanResult(false,"SCANNER_UNAVAILABLE");}return new Imported(key,type,bytes.length,scan.clean(),scan.detail());}
 private Imported storeAndScan(byte[] bytes,String type){String key="knowledge-quarantine/"+("KVER-"+UUID.randomUUID()).toLowerCase(Locale.ROOT);storage.put(key,bytes);VirusScanPort.ScanResult scan;try{scan=scanner.scan(key,bytes);}catch(RuntimeException e){scan=new VirusScanPort.ScanResult(false,"SCANNER_UNAVAILABLE");}return new Imported(key,type,bytes.length,scan.clean(),scan.detail());}
 private KnowledgeImportTask task(String id,String documentId,CurrentUser actor,Imported imported,java.time.Instant now){return new KnowledgeImportTask(id,documentId,null,imported.clean?"COMPLETED":isMalware(imported.scanDetail)?"REJECTED":"SCAN_FAILED",actor.iamUserId(),imported.clean?null:imported.scanDetail,now,now);}
 private static KnowledgePublicationStatus publicationStatus(Imported imported){return imported.clean?KnowledgePublicationStatus.PENDING_REVIEW:isMalware(imported.scanDetail)?KnowledgePublicationStatus.REJECTED:KnowledgePublicationStatus.IMPORTED;}
 private static String scanOutcome(Imported imported){return imported.clean?"CLEAN":isMalware(imported.scanDetail)?"MALWARE_FOUND":"SCAN_FAILED";}
 private static boolean isMalware(String detail){return "MALWARE_FOUND".equals(detail)||"MALWARE_SIGNATURE".equals(detail);}
 private String currentOrganization(CurrentUser actor){var projection=iam.requireActiveProjection(actor.iamUserId());String id=projection.organization()==null?null:projection.organization().iamOrganizationId();if(id==null||id.isBlank())throw new KnowledgeNotFoundException();return id;}
 private List<String> validateCatalogs(List<String> values){if(values==null||values.isEmpty()||values.size()>20)throw new KnowledgeValidationException();List<String> result=values.stream().filter(Objects::nonNull).map(String::trim).filter(v->!v.isBlank()).distinct().toList();if(result.isEmpty()||result.size()!=values.size()||result.stream().anyMatch(id->!catalogs.isPublishedItem(id)))throw new KnowledgeValidationException();return result;}
 private void requireManagerRole(CurrentUser actor){if(!isManager(actor))throw new org.springframework.security.access.AccessDeniedException("Knowledge administration is not authorized");}
 private void requireManagerScope(CurrentUser actor,String organizationId){requireManagerRole(actor);if(organizationId==null||organizationId.isBlank()||(!actor.authorities().contains("ROLE_PLATFORM_ADMIN")&&!actor.authorities().contains("DATA_SCOPE_ORGANIZATION:"+organizationId)))throw new org.springframework.security.access.AccessDeniedException("Knowledge organization scope is not authorized");}
 private boolean managerScoped(CurrentUser actor,KnowledgeDocument d){return isManager(actor)&&d.status()!=KnowledgePublicationStatus.MIGRATION_PENDING&&d.owningOrganizationId()!=null&&(actor.authorities().contains("ROLE_PLATFORM_ADMIN")||actor.authorities().contains("DATA_SCOPE_ORGANIZATION:"+d.owningOrganizationId()))&&!d.serviceCatalogItemIds().isEmpty();}
 private boolean auditorScoped(CurrentUser actor,KnowledgeDocument d){return actor.authorities().contains("ROLE_AUDITOR")&&d.owningOrganizationId()!=null&&actor.authorities().contains("DATA_SCOPE_ORGANIZATION:"+d.owningOrganizationId());}
 private KnowledgeDocument managerDocument(CurrentUser actor,String id){requireManagerRole(actor);KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);if(!managerScoped(actor,d))throw new KnowledgeNotFoundException();return d;}
 private KnowledgeDocument managementReadableDocument(CurrentUser actor,String id){boolean reader=isManager(actor)||actor.authorities().contains("ROLE_AUDITOR");if(!reader)throw new org.springframework.security.access.AccessDeniedException("Knowledge administration is not authorized");KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);if(d.status()==KnowledgePublicationStatus.MIGRATION_PENDING||d.owningOrganizationId()==null||!actor.authorities().contains("DATA_SCOPE_ORGANIZATION:"+d.owningOrganizationId())||d.serviceCatalogItemIds().isEmpty())throw new KnowledgeNotFoundException();return d;}
 private KnowledgeDocument publicDocument(CurrentUser actor,String id){KnowledgeDocument d=repo.findDocument(id).orElseThrow(KnowledgeNotFoundException::new);if(!publiclyReadable(currentOrganization(actor),d))throw new KnowledgeNotFoundException();return d;}
 private boolean publiclyReadable(String organizationId,KnowledgeDocument d){return d.status()==KnowledgePublicationStatus.PUBLISHED&&organizationId.equals(d.owningOrganizationId())&&!d.serviceCatalogItemIds().isEmpty()&&d.serviceCatalogItemIds().stream().allMatch(catalogs::isPublishedItem);}
 private static boolean sameScope(KnowledgeDocument d,KnowledgeDocumentVersion v){return Objects.equals(d.owningOrganizationId(),v.owningOrganizationId())&&d.serviceCatalogItemIds().equals(v.serviceCatalogItemIds());}
 private static boolean isManager(CurrentUser u){return u.authorities().contains("ROLE_SERVICE_MANAGER")||u.authorities().contains("ROLE_PLATFORM_ADMIN");}
 private static boolean matches(KnowledgeDocument d,String query,String category,String tag){if(category!=null&&!category.isBlank()&&!category.equals(d.categoryCode()))return false;if(tag!=null&&!tag.isBlank()&&!d.tags().contains(tag))return false;if(query==null||query.isBlank())return true;String q=query.trim().toLowerCase(Locale.ROOT);return (d.title()+" "+d.categoryCode()+" "+String.join(" ",d.tags())).toLowerCase(Locale.ROOT).contains(q);}
 private static void validateSearch(String query,String category,String tag){if(query!=null&&query.length()>100||category!=null&&category.length()>64||tag!=null&&tag.length()>65)throw new KnowledgeValidationException();}
 private static byte[] validateManualContent(String content){if(content==null||content.isBlank()||content.length()>100000||content.chars().anyMatch(c->c==0||(c<32&&c!='\n'&&c!='\r'&&c!='\t')))throw new KnowledgeValidationException();byte[] bytes=content.getBytes(StandardCharsets.UTF_8);if(bytes.length>MAX_PREVIEW_BYTES)throw new KnowledgeValidationException();return bytes;}
 private static void validateMetadata(String title,String category,List<String> tags){if(title==null||title.trim().isBlank()||title.length()>200||category==null||!category.matches("^[A-Z][A-Z0-9_-]{1,63}$"))throw new KnowledgeValidationException();cleanTags(tags);} private static List<String> cleanTags(List<String> values){if(values==null)return List.of();if(values.size()>20)throw new KnowledgeValidationException();return values.stream().map(v->{if(v==null||!v.matches("^#[^\\s#]{1,64}$"))throw new KnowledgeValidationException();return v;}).distinct().toList();}
 private static String detect(byte[] b){if(starts(b,"%PDF-".getBytes(StandardCharsets.US_ASCII)))return "application/pdf";String text=new String(b,StandardCharsets.UTF_8);if(text.indexOf('\uFFFD')<0&&text.chars().noneMatch(c->c==0||(c<32&&c!='\n'&&c!='\r'&&c!='\t')))return "text/plain";return null;} private static boolean starts(byte[] b,byte[] p){if(b.length<p.length)return false;for(int i=0;i<p.length;i++)if(b[i]!=p[i])return false;return true;}
 private FeedbackSummary feedbackSummary(KnowledgeDocument d){List<KnowledgeFeedback> values=repo.findFeedback(d.id(),d.currentVersionId());long helpful=values.stream().filter(v->v.value()==KnowledgeFeedback.FeedbackValue.HELPFUL).count();return new FeedbackSummary(helpful,values.size()-helpful);}
 private static String normalizeTicketTitle(String value){String title=value==null?"":value.trim().replaceAll("[\\t\\r\\n ]+"," ");return title.length()>200?title.substring(0,200):title;}
 private void audit(CurrentUser actor,String action,String id,Map<String,String> attr){String requestId=MDC.get("requestId");audit.publish(new AuditEvent(clock.instant(),requestId==null?"system":requestId,actor.iamUserId(),action,"knowledge-document",id,attr));}
 private record Imported(String key,String mediaType,long size,boolean clean,String scanDetail){} public enum WorkbenchSection{MY_DRAFTS,MY_SUBMISSIONS,PENDING_REVIEW,REVIEWED} public record PlainTextPreview(String versionId,int versionNumber,String content){} public record KnowledgeReviewItem(KnowledgeImportTask task,KnowledgeDocument document,List<KnowledgeDocumentVersion> pendingVersions){} public record FeedbackSummary(long helpfulCount,long notHelpfulCount){public long total(){return helpfulCount+notHelpfulCount;}}
}
