package cn.servicehub.workflow.lifecycleapproval.infrastructure;

import cn.servicehub.workflow.domain.WorkflowAction;
import cn.servicehub.workflow.lifecycleapproval.domain.LifecycleActionApprovalRepository;
import cn.servicehub.workflow.lifecycleapproval.domain.LifecycleActionApprovalRequest;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Repository;

@Repository
@Profile("mysql")
public class MySqlLifecycleActionApprovalRepository implements LifecycleActionApprovalRepository {
    private final JdbcTemplate jdbc; private final ObjectMapper json;
    public MySqlLifecycleActionApprovalRepository(JdbcTemplate jdbc, ObjectMapper json) { this.jdbc = jdbc; this.json = json; }
    @Override public void save(LifecycleActionApprovalRequest r) { try { jdbc.update("INSERT INTO ticket_lifecycle_action_approval_request (id,ticket_id,action_code,applicant_iam_user_id,reason,target_iam_user_id,source_ticket_version,source_workflow_version,approval_engine_instance_id,approval_process_key,approval_process_definition_id,approval_process_version,approval_policy_id,approval_policy_version,approval_decision_mode,required_approval_count,approval_timeout_policy_version,approval_escalation_policy_version,approval_due_at,approval_candidate_roles_json,approval_candidate_iam_user_ids_json,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", r.id(),r.ticketId(),r.action().name(),r.applicantIamUserId(),r.reason(),r.targetIamUserId(),r.sourceTicketVersion(),r.sourceWorkflowVersion(),r.approvalEngineInstanceId(),r.processKey(),r.processDefinitionId(),r.processVersion(),r.policyId(),r.policyVersion(),r.decisionMode(),r.requiredApprovalCount(),r.timeoutPolicyVersion(),r.escalationPolicyVersion(),ts(r.dueAt()),json.writeValueAsString(r.candidateRoles()),json.writeValueAsString(r.candidateIamUserIds()),r.status(),ts(r.createdAt())); } catch (DuplicateKeyException e) { throw new cn.servicehub.workflow.application.WorkflowConflictException(); } catch (Exception e) { throw new IllegalStateException("Lifecycle approval snapshot cannot be persisted", e); } }
    @Override public List<LifecycleActionApprovalRequest> findByTicketId(String ticketId) { return jdbc.query("SELECT * FROM ticket_lifecycle_action_approval_request WHERE ticket_id=? ORDER BY created_at", (rs,n)->map(rs), ticketId); }
    @Override public Optional<LifecycleActionApprovalRequest> find(String ticketId, String requestId) { return jdbc.query("SELECT * FROM ticket_lifecycle_action_approval_request WHERE ticket_id=? AND id=?", (rs,n)->map(rs), ticketId, requestId).stream().findFirst(); }
    @Override public Optional<LifecycleActionApprovalRequest> findById(String requestId) { return jdbc.query("SELECT * FROM ticket_lifecycle_action_approval_request WHERE id=?", (rs,n)->map(rs), requestId).stream().findFirst(); }
    @Override public boolean finalizeDecision(String ticketId,String requestId,String decision,String approver,String reason,Instant at) { return jdbc.update("UPDATE ticket_lifecycle_action_approval_request SET status=?,approver_iam_user_id=?,decision_reason=?,decided_at=? WHERE ticket_id=? AND id=? AND status='PENDING_APPROVAL'",decision,approver,reason,ts(at),ticketId,requestId)==1; }
    @Override public boolean markExecuted(String ticketId,String requestId,long ticketVersion,long workflowVersion,Instant at) { return jdbc.update("UPDATE ticket_lifecycle_action_approval_request SET status='EXECUTED',executed_at=? WHERE ticket_id=? AND id=? AND status='APPROVED' AND source_ticket_version=? AND source_workflow_version=?",ts(at),ticketId,requestId,ticketVersion,workflowVersion)==1; }
    @Override public boolean markStale(String ticketId,String requestId,Instant at) { return jdbc.update("UPDATE ticket_lifecycle_action_approval_request SET status='STALE',executed_at=? WHERE ticket_id=? AND id=? AND status='APPROVED'",ts(at),ticketId,requestId)==1; }
    @Override public List<LifecycleActionApprovalRequest> findPendingDueBefore(Instant now,int limit) { return jdbc.query("SELECT * FROM ticket_lifecycle_action_approval_request WHERE status='PENDING_APPROVAL' AND approval_due_at<=? ORDER BY approval_due_at LIMIT ?",(rs,n)->map(rs),ts(now),limit); }
    @Override public boolean claimExpiration(String ticketId,String requestId,Instant at) { return jdbc.update("UPDATE ticket_lifecycle_action_approval_request SET status='EXPIRING',expiration_claimed_at=? WHERE ticket_id=? AND id=? AND status='PENDING_APPROVAL' AND approval_due_at<=?",ts(at),ticketId,requestId,ts(at))==1; }
    @Override public boolean markExpired(String ticketId,String requestId,Instant at) { return jdbc.update("UPDATE ticket_lifecycle_action_approval_request SET status='EXPIRED',executed_at=? WHERE ticket_id=? AND id=? AND status='EXPIRING'",ts(at),ticketId,requestId)==1; }
    @Override public void appendTimeoutEvent(String id,LifecycleActionApprovalRequest r,Instant at) { jdbc.update("INSERT INTO ticket_lifecycle_action_approval_timeout_event (id,approval_request_id,ticket_id,timeout_policy_version,escalation_policy_version,occurred_at) VALUES (?,?,?,?,?,?)",id,r.id(),r.ticketId(),r.timeoutPolicyVersion(),r.escalationPolicyVersion(),ts(at)); }
    private LifecycleActionApprovalRequest map(java.sql.ResultSet rs) throws java.sql.SQLException { try { return new LifecycleActionApprovalRequest(rs.getString("id"),rs.getString("ticket_id"),WorkflowAction.valueOf(rs.getString("action_code")),rs.getString("applicant_iam_user_id"),rs.getString("reason"),rs.getString("target_iam_user_id"),rs.getLong("source_ticket_version"),rs.getLong("source_workflow_version"),rs.getString("approval_engine_instance_id"),rs.getString("approval_process_key"),rs.getString("approval_process_definition_id"),rs.getInt("approval_process_version"),rs.getString("approval_policy_id"),rs.getLong("approval_policy_version"),rs.getString("approval_decision_mode"),rs.getInt("required_approval_count"),rs.getString("approval_timeout_policy_version"),rs.getString("approval_escalation_policy_version"),rs.getTimestamp("approval_due_at").toInstant(),json.readValue(rs.getString("approval_candidate_roles_json"),new TypeReference<java.util.Set<String>>(){}),json.readValue(rs.getString("approval_candidate_iam_user_ids_json"),new TypeReference<java.util.Set<String>>(){}),rs.getString("status"),rs.getString("approver_iam_user_id"),rs.getString("decision_reason"),instant(rs,"decided_at"),instant(rs,"executed_at"),rs.getTimestamp("created_at").toInstant()); } catch (Exception e) { throw new java.sql.SQLException("Lifecycle approval snapshot is unreadable",e); } }
    private static Instant instant(java.sql.ResultSet rs,String col) throws java.sql.SQLException { Timestamp value=rs.getTimestamp(col); return value==null?null:value.toInstant(); } private static Timestamp ts(Instant value){return Timestamp.from(value);}
}
