package cn.servicehub.servicesystem.infrastructure;

import cn.servicehub.servicesystem.application.ServiceSystemConflictException;
import cn.servicehub.servicesystem.domain.ServiceSystem;
import cn.servicehub.servicesystem.domain.ServiceSystemCatalogMapping;
import cn.servicehub.servicesystem.domain.ServiceSystemModule;
import cn.servicehub.servicesystem.domain.ServiceSystemRepository;
import cn.servicehub.servicesystem.domain.ServiceSystemStatus;
import cn.servicehub.servicesystem.domain.TicketServiceSystemSnapshot;
import java.sql.Timestamp;
import java.util.List;
import java.util.Optional;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
@Profile("mysql")
public class MySqlServiceSystemRepository implements ServiceSystemRepository {
    private final JdbcTemplate jdbc;
    public MySqlServiceSystemRepository(JdbcTemplate jdbc) { this.jdbc=jdbc; }
    @Override public List<ServiceSystem> findAll(){return jdbc.query("SELECT * FROM service_system_registry ORDER BY system_name, system_code",(rs,n)->system(rs));}
    @Override public Optional<ServiceSystem> findByCode(String code){return jdbc.query("SELECT * FROM service_system_registry WHERE system_code=?",(rs,n)->system(rs),code).stream().findFirst();}
    @Override public ServiceSystem saveSystem(ServiceSystem value,long expected){
        int changed=jdbc.update("UPDATE service_system_registry SET system_name=?,ci_id=?,owner_iam_user_id=?,owning_organization_id=?,lifecycle_status=?,version=version+1,change_reason=?,updated_by_iam_user_id=?,updated_at=?,published_at=? WHERE system_code=? AND version=?",value.name(),value.configurationItemId(),value.ownerIamUserId(),value.owningOrganizationId(),value.status().name(),value.changeReason(),value.updatedByIamUserId(),Timestamp.from(value.updatedAt()),timestamp(value.publishedAt()),value.code(),expected);
        if(changed==0&&expected==0) jdbc.update("INSERT INTO service_system_registry (system_code,system_name,ci_id,owner_iam_user_id,owning_organization_id,lifecycle_status,version,change_reason,created_by_iam_user_id,updated_by_iam_user_id,created_at,updated_at,published_at) VALUES (?,?,?,?,?,?,1,?,?,?,?,?,?)",value.code(),value.name(),value.configurationItemId(),value.ownerIamUserId(),value.owningOrganizationId(),value.status().name(),value.changeReason(),value.createdByIamUserId(),value.updatedByIamUserId(),Timestamp.from(value.createdAt()),Timestamp.from(value.updatedAt()),timestamp(value.publishedAt()));
        else if(changed==0) throw new ServiceSystemConflictException(); return findByCode(value.code()).orElseThrow();
    }
    @Override public List<ServiceSystemModule> findModules(String system){return jdbc.query("SELECT * FROM service_system_module WHERE system_code=? ORDER BY sort_order,module_code",(rs,n)->module(rs),system);}
    @Override public Optional<ServiceSystemModule> findModule(String system,String module){return jdbc.query("SELECT * FROM service_system_module WHERE system_code=? AND module_code=?",(rs,n)->module(rs),system,module).stream().findFirst();}
    @Override public ServiceSystemModule saveModule(ServiceSystemModule value,long expected){int changed=jdbc.update("UPDATE service_system_module SET module_name=?,module_path=?,active=?,sort_order=?,version=version+1,updated_by_iam_user_id=?,updated_at=? WHERE system_code=? AND module_code=? AND version=?",value.name(),value.path(),value.active(),value.sortOrder(),value.updatedByIamUserId(),Timestamp.from(value.updatedAt()),value.systemCode(),value.code(),expected);if(changed==0&&expected==0)jdbc.update("INSERT INTO service_system_module (system_code,module_code,module_name,module_path,active,sort_order,version,updated_by_iam_user_id,updated_at) VALUES (?,?,?,?,?,?,1,?,?)",value.systemCode(),value.code(),value.name(),value.path(),value.active(),value.sortOrder(),value.updatedByIamUserId(),Timestamp.from(value.updatedAt()));else if(changed==0)throw new ServiceSystemConflictException();return findModule(value.systemCode(),value.code()).orElseThrow();}
    @Override public List<ServiceSystemCatalogMapping> findSystemCatalogMappings(String system){return jdbc.query("SELECT * FROM service_system_catalog_mapping WHERE system_code=? ORDER BY service_catalog_item_id",(rs,n)->mapping(rs,null),system);}
    @Override public List<ServiceSystemCatalogMapping> findModuleCatalogMappings(String system,String module){return jdbc.query("SELECT * FROM service_system_module_catalog_mapping WHERE system_code=? AND module_code=? ORDER BY service_catalog_item_id",(rs,n)->mapping(rs,module),system,module);}
    @Override public ServiceSystemCatalogMapping saveCatalogMapping(ServiceSystemCatalogMapping v,long expected){boolean module=v.moduleCode()!=null;String table=module?"service_system_module_catalog_mapping":"service_system_catalog_mapping";String where=module?"system_code=? AND module_code=? AND service_catalog_item_id=? AND version=?":"system_code=? AND service_catalog_item_id=? AND version=?";Object[] args=module?new Object[]{v.active(),v.defaultMapping(),v.updatedByIamUserId(),Timestamp.from(v.updatedAt()),v.systemCode(),v.moduleCode(),v.serviceCatalogItemId(),expected}:new Object[]{v.active(),v.defaultMapping(),v.updatedByIamUserId(),Timestamp.from(v.updatedAt()),v.systemCode(),v.serviceCatalogItemId(),expected};int changed=jdbc.update("UPDATE "+table+" SET active=?,is_default=?,version=version+1,updated_by_iam_user_id=?,updated_at=? WHERE "+where,args);if(changed==0&&expected==0){if(module)jdbc.update("INSERT INTO service_system_module_catalog_mapping (system_code,module_code,service_catalog_item_id,active,is_default,version,updated_by_iam_user_id,updated_at) VALUES (?,?,?,?,?,1,?,?)",v.systemCode(),v.moduleCode(),v.serviceCatalogItemId(),v.active(),v.defaultMapping(),v.updatedByIamUserId(),Timestamp.from(v.updatedAt()));else jdbc.update("INSERT INTO service_system_catalog_mapping (system_code,service_catalog_item_id,active,is_default,version,updated_by_iam_user_id,updated_at) VALUES (?,?,?, ?,1,?,?)",v.systemCode(),v.serviceCatalogItemId(),v.active(),v.defaultMapping(),v.updatedByIamUserId(),Timestamp.from(v.updatedAt()));}else if(changed==0)throw new ServiceSystemConflictException();return (module?findModuleCatalogMappings(v.systemCode(),v.moduleCode()):findSystemCatalogMappings(v.systemCode())).stream().filter(x->x.serviceCatalogItemId().equals(v.serviceCatalogItemId())).findFirst().orElseThrow();}
    @Override public void saveTicketSnapshot(TicketServiceSystemSnapshot v){jdbc.update("INSERT INTO ticket_service_system_snapshot (ticket_id,system_code,system_name,module_code,module_name,service_catalog_item_id,registry_version,captured_at) VALUES (?,?,?,?,?,?,?,?)",v.ticketId(),v.systemCode(),v.systemName(),v.moduleCode(),v.moduleName(),v.serviceCatalogItemId(),v.registryVersion(),Timestamp.from(v.capturedAt()));}
    @Override public Optional<TicketServiceSystemSnapshot> findTicketSnapshot(String id){return jdbc.query("SELECT * FROM ticket_service_system_snapshot WHERE ticket_id=?",(rs,n)->new TicketServiceSystemSnapshot(rs.getString("ticket_id"),rs.getString("system_code"),rs.getString("system_name"),rs.getString("module_code"),rs.getString("module_name"),rs.getString("service_catalog_item_id"),rs.getLong("registry_version"),rs.getTimestamp("captured_at").toInstant()),id).stream().findFirst();}
    @Override public void recordLifecycleEvent(String systemCode,long version,ServiceSystemStatus status,String action,String actor,String reason,java.time.Instant at){jdbc.update("INSERT INTO service_system_registry_publication_history (system_code,registry_version,lifecycle_status,action,actor_iam_user_id,reason,occurred_at) VALUES (?,?,?,?,?,?,?)",systemCode,version,status.name(),action,actor,reason,Timestamp.from(at));}
    private ServiceSystem system(java.sql.ResultSet rs)throws java.sql.SQLException{return new ServiceSystem(rs.getString("system_code"),rs.getString("system_name"),rs.getString("ci_id"),rs.getString("owner_iam_user_id"),rs.getString("owning_organization_id"),ServiceSystemStatus.valueOf(rs.getString("lifecycle_status")),rs.getLong("version"),rs.getString("change_reason"),rs.getString("created_by_iam_user_id"),rs.getString("updated_by_iam_user_id"),rs.getTimestamp("created_at").toInstant(),rs.getTimestamp("updated_at").toInstant(),rs.getTimestamp("published_at")==null?null:rs.getTimestamp("published_at").toInstant());}
    private ServiceSystemModule module(java.sql.ResultSet rs)throws java.sql.SQLException{return new ServiceSystemModule(rs.getString("system_code"),rs.getString("module_code"),rs.getString("module_name"),rs.getString("module_path"),rs.getBoolean("active"),rs.getInt("sort_order"),rs.getLong("version"),rs.getString("updated_by_iam_user_id"),rs.getTimestamp("updated_at").toInstant());}
    private ServiceSystemCatalogMapping mapping(java.sql.ResultSet rs,String module)throws java.sql.SQLException{return new ServiceSystemCatalogMapping(rs.getString("system_code"),module,rs.getString("service_catalog_item_id"),rs.getBoolean("active"),rs.getBoolean("is_default"),rs.getLong("version"),rs.getString("updated_by_iam_user_id"),rs.getTimestamp("updated_at").toInstant());}
    private Timestamp timestamp(java.time.Instant v){return v==null?null:Timestamp.from(v);}
}
