package cn.servicehub.workflow.infrastructure;

import cn.servicehub.ticket.domain.TicketStatus;
import cn.servicehub.workflow.domain.CollaborationRole;
import cn.servicehub.workflow.domain.ControlledJumpRequest;
import cn.servicehub.workflow.domain.ApprovalPolicySnapshot;
import cn.servicehub.workflow.domain.TicketWorkflowRepository;
import cn.servicehub.workflow.domain.WorkflowComment;
import cn.servicehub.workflow.domain.WorkflowInstance;
import cn.servicehub.workflow.domain.WorkflowTask;
import cn.servicehub.workflow.domain.WorkflowTaskStatus;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
@Profile("mysql")
public class MySqlTicketWorkflowRepository implements TicketWorkflowRepository {
    private final JdbcTemplate jdbc;
    private final ObjectMapper objectMapper;
    public MySqlTicketWorkflowRepository(JdbcTemplate jdbc, ObjectMapper objectMapper) { this.jdbc = jdbc; this.objectMapper = objectMapper; }
    @Override public void create(WorkflowInstance i, WorkflowTask t) { jdbc.update("INSERT INTO ticket_workflow_instance (ticket_id, engine_instance_id, current_node, status, resume_status, escalation_level, primary_assignee_iam_user_id, version, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", i.ticketId(), i.engineInstanceId(), i.currentNode(), i.status().name(), name(i.resumeStatus()), i.escalationLevel(), i.primaryAssigneeIamUserId(), i.version(), ts(i.createdAt()), ts(i.updatedAt())); saveTask(t); }
    @Override public Optional<WorkflowInstance> findInstance(String ticketId) { return jdbc.query("SELECT * FROM ticket_workflow_instance WHERE ticket_id = ?", (rs, n) -> new WorkflowInstance(rs.getString("ticket_id"), rs.getString("engine_instance_id"), rs.getString("current_node"), TicketStatus.valueOf(rs.getString("status")), enumOrNull(rs.getString("resume_status"), TicketStatus.class), rs.getInt("escalation_level"), rs.getString("primary_assignee_iam_user_id"), rs.getLong("version"), rs.getTimestamp("created_at").toInstant(), rs.getTimestamp("updated_at").toInstant()), ticketId).stream().findFirst(); }
    @Override public boolean updateInstance(WorkflowInstance i, long expected) { return jdbc.update("UPDATE ticket_workflow_instance SET engine_instance_id=?, current_node=?, status=?, resume_status=?, escalation_level=?, primary_assignee_iam_user_id=?, version=?, updated_at=? WHERE ticket_id=? AND version=?", i.engineInstanceId(), i.currentNode(), i.status().name(), name(i.resumeStatus()), i.escalationLevel(), i.primaryAssigneeIamUserId(), i.version(), ts(i.updatedAt()), i.ticketId(), expected) == 1; }
    @Override public Optional<WorkflowTask> findOpenTask(String ticketId, String node) { return jdbc.query("SELECT * FROM ticket_workflow_task WHERE ticket_id=? AND node_key=? AND status IN ('OPEN','CLAIMED') ORDER BY created_at LIMIT 1", (rs, n) -> task(rs), ticketId, node).stream().findFirst(); }
    @Override public void saveTask(WorkflowTask t) { jdbc.update("INSERT INTO ticket_workflow_task (id, ticket_id, engine_task_id, node_key, status, candidate_role, candidate_iam_user_id, assignee_iam_user_id, collaboration_role, version, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE engine_task_id=VALUES(engine_task_id), node_key=VALUES(node_key), status=VALUES(status), candidate_role=VALUES(candidate_role), candidate_iam_user_id=VALUES(candidate_iam_user_id), assignee_iam_user_id=VALUES(assignee_iam_user_id), collaboration_role=VALUES(collaboration_role), version=VALUES(version), updated_at=VALUES(updated_at)", t.id(), t.ticketId(), t.engineTaskId(), t.nodeKey(), t.status().name(), t.candidateRole(), t.candidateIamUserId(), t.assigneeIamUserId(), name(t.collaborationRole()), t.version(), ts(t.createdAt()), ts(t.updatedAt())); }
    @Override public List<WorkflowTask> findTasks(String ticketId) { return jdbc.query("SELECT * FROM ticket_workflow_task WHERE ticket_id=? ORDER BY created_at", (rs, n) -> task(rs), ticketId); }
    @Override public List<String> findTodoTicketIds(String iamUserId, java.util.Set<String> authorities) {
        String roles = authorities.isEmpty() ? "''" : String.join(",", authorities.stream().map(value -> "?").toList());
        String sql = "SELECT DISTINCT ticket_id FROM ticket_workflow_task WHERE status IN ('OPEN','CLAIMED') AND (assignee_iam_user_id=? OR (assignee_iam_user_id IS NULL AND (candidate_iam_user_id=? OR candidate_role IN (" + roles + "))))";
        java.util.List<Object> arguments = new java.util.ArrayList<>(); arguments.add(iamUserId); arguments.add(iamUserId); arguments.addAll(authorities);
        return jdbc.queryForList(sql, String.class, arguments.toArray());
    }
    @Override public List<String> findCompletedTicketIds(String iamUserId) { return jdbc.queryForList("SELECT DISTINCT ticket_id FROM ticket_workflow_task WHERE status='COMPLETED' AND assignee_iam_user_id=?", String.class, iamUserId); }
    @Override public void addCoHandler(String ticketId, String user, Instant at) { jdbc.update("INSERT IGNORE INTO ticket_co_handler (ticket_id, iam_user_id, added_at) VALUES (?, ?, ?)", ticketId, user, ts(at)); }
    @Override public boolean hasCoHandler(String ticketId, String user) { return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM ticket_co_handler WHERE ticket_id=? AND iam_user_id=?)", Boolean.class, ticketId, user)); }
    @Override public void replacePrimaryParticipant(String ticketId, cn.servicehub.ticket.domain.IdentitySnapshot identity, Instant at) {
        jdbc.update("UPDATE ticket_workflow_participant SET active=FALSE, unassigned_at=? WHERE ticket_id=? AND role='PRIMARY' AND active=TRUE", ts(at), ticketId);
        saveParticipant(ticketId, cn.servicehub.workflow.domain.CollaborationRole.PRIMARY, identity, at);
    }
    @Override public void addCoHandlerParticipant(String ticketId, cn.servicehub.ticket.domain.IdentitySnapshot identity, Instant at) { saveParticipant(ticketId, cn.servicehub.workflow.domain.CollaborationRole.CO_HANDLER, identity, at); }
    @Override public void clearPrimaryParticipant(String ticketId, Instant at) { jdbc.update("UPDATE ticket_workflow_participant SET active=FALSE, unassigned_at=? WHERE ticket_id=? AND role='PRIMARY' AND active=TRUE", ts(at), ticketId); }
    @Override public List<cn.servicehub.workflow.domain.WorkflowParticipant> findActiveParticipants(String ticketId) { return jdbc.query("SELECT * FROM ticket_workflow_participant WHERE ticket_id=? AND active=TRUE ORDER BY assigned_at", (rs, n) -> new cn.servicehub.workflow.domain.WorkflowParticipant(rs.getString("ticket_id"), cn.servicehub.workflow.domain.CollaborationRole.valueOf(rs.getString("role")), new cn.servicehub.ticket.domain.IdentitySnapshot(rs.getString("iam_user_id"), rs.getString("display_name"), rs.getString("organization_id"), rs.getString("organization_name"), rs.getString("position_name"), rs.getTimestamp("captured_at").toInstant()), rs.getTimestamp("assigned_at").toInstant()), ticketId); }
    @Override public void addComment(WorkflowComment c) { jdbc.update("INSERT INTO ticket_internal_comment (id, ticket_id, author_iam_user_id, body, created_at) VALUES (?, ?, ?, ?, ?)", c.id(), c.ticketId(), c.authorIamUserId(), c.body(), ts(c.createdAt())); }
    @Override public List<WorkflowComment> findComments(String ticketId) { return jdbc.query("SELECT * FROM ticket_internal_comment WHERE ticket_id=? ORDER BY created_at", (rs, n) -> new WorkflowComment(rs.getString("id"), rs.getString("ticket_id"), rs.getString("author_iam_user_id"), rs.getString("body"), rs.getTimestamp("created_at").toInstant()), ticketId); }
    @Override public void addJumpRequest(ControlledJumpRequest r) { try { ApprovalPolicySnapshot policy = r.approvalPolicy(); jdbc.update("INSERT INTO ticket_controlled_jump_request (id, approval_engine_instance_id, approval_process_key, approval_process_definition_id, approval_process_version, approval_candidate_roles_json, approval_candidate_iam_user_ids_json, approval_decision_mode, approval_timeout_policy_version, approval_escalation_policy_version, approval_policy_captured_at, ticket_id, applicant_iam_user_id, source_node, source_ticket_version, source_workflow_version, target_node, reason, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", r.id(), r.approvalEngineInstanceId(), policy.processKey(), policy.processDefinitionId(), policy.processVersion(), objectMapper.writeValueAsString(policy.candidateRoles()), objectMapper.writeValueAsString(policy.candidateIamUserIds()), policy.decisionMode(), policy.timeoutPolicyVersion(), policy.escalationPolicyVersion(), ts(policy.capturedAt()), r.ticketId(), r.applicantIamUserId(), r.sourceNode(), r.sourceTicketVersion(), r.sourceWorkflowVersion(), r.targetNode(), r.reason(), r.status(), ts(r.createdAt())); } catch (Exception exception) { throw new IllegalStateException("Approval policy snapshot cannot be persisted", exception); } }
    @Override public List<ControlledJumpRequest> findJumpRequests(String ticketId) { return jdbc.query("SELECT * FROM ticket_controlled_jump_request WHERE ticket_id=? ORDER BY created_at", (rs, n) -> jumpRequest(rs), ticketId); }
    @Override public Optional<ControlledJumpRequest> findJumpRequest(String ticketId, String requestId) { return jdbc.query("SELECT * FROM ticket_controlled_jump_request WHERE ticket_id=? AND id=?", (rs, n) -> jumpRequest(rs), ticketId, requestId).stream().findFirst(); }
    @Override public Optional<ControlledJumpRequest> findJumpRequestById(String requestId) { return jdbc.query("SELECT * FROM ticket_controlled_jump_request WHERE id=?", (rs, n) -> jumpRequest(rs), requestId).stream().findFirst(); }
    @Override public boolean finalizeJumpRequestApproval(String ticketId, String requestId, String decision, String approver, String reason, Instant at) { return jdbc.update("UPDATE ticket_controlled_jump_request SET status=?, approver_iam_user_id=?, decision_reason=?, decided_at=? WHERE ticket_id=? AND id=? AND status='PENDING_APPROVAL'", decision, approver, reason, ts(at), ticketId, requestId) == 1; }
    @Override public void appendApprovalDecision(cn.servicehub.workflow.domain.ApprovalDecisionRecord decision) { jdbc.update("INSERT INTO ticket_controlled_jump_approval_decision_event (id, approval_request_id, engine_task_id, approver_iam_user_id, decision, reason, decided_at) VALUES (?, ?, ?, ?, ?, ?, ?)", decision.id(), decision.approvalRequestId(), decision.engineTaskId(), decision.approverIamUserId(), decision.decision(), decision.reason(), ts(decision.decidedAt())); }
    @Override public List<cn.servicehub.workflow.domain.ApprovalDecisionRecord> findApprovalDecisions(String ticketId, String requestId) { return jdbc.query("SELECT d.* FROM ticket_controlled_jump_approval_decision_event d JOIN ticket_controlled_jump_request r ON r.id=d.approval_request_id WHERE r.ticket_id=? AND d.approval_request_id=? ORDER BY d.decided_at, d.id", (rs, n) -> new cn.servicehub.workflow.domain.ApprovalDecisionRecord(rs.getString("id"), rs.getString("approval_request_id"), rs.getString("engine_task_id"), rs.getString("approver_iam_user_id"), rs.getString("decision"), rs.getString("reason"), rs.getTimestamp("decided_at").toInstant()), ticketId, requestId); }
    @Override public boolean claimJumpExecution(String ticketId, String requestId, long sourceTicketVersion, long sourceWorkflowVersion, String executor, Instant startedAt) { return jdbc.update("UPDATE ticket_controlled_jump_request SET status='EXECUTING', executor_iam_user_id=?, execution_started_at=?, execution_failure_reason=NULL WHERE ticket_id=? AND id=? AND status='APPROVED' AND source_ticket_version=? AND source_workflow_version=?", executor, ts(startedAt), ticketId, requestId, sourceTicketVersion, sourceWorkflowVersion) == 1; }
    @Override public boolean completeJumpExecution(String ticketId, String requestId, String from, String to, Instant executedAt) { return jdbc.update("UPDATE ticket_controlled_jump_request SET status='EXECUTED', executed_at=?, executed_from_node=?, executed_to_node=? WHERE ticket_id=? AND id=? AND status='EXECUTING'", ts(executedAt), from, to, ticketId, requestId) == 1; }
    @Override public boolean releaseJumpExecution(String ticketId, String requestId) { return jdbc.update("UPDATE ticket_controlled_jump_request SET status='APPROVED', executor_iam_user_id=NULL, execution_started_at=NULL, execution_failure_reason='ENGINE_EXECUTION_FAILED' WHERE ticket_id=? AND id=? AND status='EXECUTING'", ticketId, requestId) == 1; }
    @Override public void appendEvent(String ticketId, String action, String actor, String requestId, java.util.Map<String, String> attributes, Instant occurredAt) { try { jdbc.update("INSERT INTO ticket_workflow_event (ticket_id, action, actor_iam_user_id, request_id, attributes, occurred_at) VALUES (?, ?, ?, ?, ?, ?)", ticketId, action, actor, requestId, objectMapper.writeValueAsString(attributes), ts(occurredAt)); } catch (Exception exception) { throw new IllegalStateException("Workflow audit event cannot be persisted", exception); } }
    @Override public List<cn.servicehub.workflow.domain.WorkflowEvent> findEvents(String ticketId) { return jdbc.query("SELECT id, ticket_id, action, actor_iam_user_id, request_id, occurred_at FROM ticket_workflow_event WHERE ticket_id=? ORDER BY occurred_at, id", (rs, n) -> new cn.servicehub.workflow.domain.WorkflowEvent(rs.getLong("id"), rs.getString("ticket_id"), rs.getString("action"), rs.getString("actor_iam_user_id"), rs.getString("request_id"), java.util.Map.of(), rs.getTimestamp("occurred_at").toInstant()), ticketId); }
    private WorkflowTask task(java.sql.ResultSet rs) throws java.sql.SQLException { return new WorkflowTask(rs.getString("id"), rs.getString("ticket_id"), rs.getString("engine_task_id"), rs.getString("node_key"), WorkflowTaskStatus.valueOf(rs.getString("status")), rs.getString("candidate_role"), rs.getString("candidate_iam_user_id"), rs.getString("assignee_iam_user_id"), enumOrNull(rs.getString("collaboration_role"), CollaborationRole.class), rs.getLong("version"), rs.getTimestamp("created_at").toInstant(), rs.getTimestamp("updated_at").toInstant()); }
    private ControlledJumpRequest jumpRequest(java.sql.ResultSet rs) throws java.sql.SQLException { return new ControlledJumpRequest(rs.getString("id"), rs.getString("ticket_id"), rs.getString("applicant_iam_user_id"), rs.getString("source_node"), rs.getString("target_node"), rs.getString("reason"), rs.getString("status"), rs.getTimestamp("created_at").toInstant(), rs.getString("approver_iam_user_id"), rs.getString("decision_reason"), rs.getTimestamp("decided_at") == null ? null : rs.getTimestamp("decided_at").toInstant(), rs.getString("approval_engine_instance_id"), (Long) rs.getObject("source_ticket_version"), (Long) rs.getObject("source_workflow_version"), rs.getString("executor_iam_user_id"), instantOrNull(rs, "execution_started_at"), instantOrNull(rs, "executed_at"), rs.getString("executed_from_node"), rs.getString("executed_to_node"), rs.getString("execution_failure_reason"), approvalPolicy(rs)); }
    private ApprovalPolicySnapshot approvalPolicy(java.sql.ResultSet rs) throws java.sql.SQLException { try { return new ApprovalPolicySnapshot(rs.getString("approval_process_key"), rs.getString("approval_process_definition_id"), rs.getInt("approval_process_version"), objectMapper.readValue(rs.getString("approval_candidate_roles_json"), new com.fasterxml.jackson.core.type.TypeReference<java.util.Set<String>>() {}), rs.getString("approval_decision_mode"), rs.getString("approval_timeout_policy_version"), rs.getString("approval_escalation_policy_version"), rs.getTimestamp("approval_policy_captured_at").toInstant(), objectMapper.readValue(rs.getString("approval_candidate_iam_user_ids_json"), new com.fasterxml.jackson.core.type.TypeReference<java.util.Set<String>>() {})); } catch (Exception exception) { throw new java.sql.SQLException("Approval policy snapshot is unreadable", exception); } }
    private void saveParticipant(String ticketId, CollaborationRole role, cn.servicehub.ticket.domain.IdentitySnapshot identity, Instant at) { jdbc.update("INSERT INTO ticket_workflow_participant (ticket_id, role, iam_user_id, display_name, organization_id, organization_name, position_name, captured_at, assigned_at, active) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, TRUE) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name), organization_id=VALUES(organization_id), organization_name=VALUES(organization_name), position_name=VALUES(position_name), captured_at=VALUES(captured_at), assigned_at=VALUES(assigned_at), active=TRUE, unassigned_at=NULL", ticketId, role.name(), identity.iamUserId(), identity.displayName(), identity.organizationId(), identity.organizationName(), identity.positionName(), ts(identity.capturedAt()), ts(at)); }
    private static Timestamp ts(Instant value) { return Timestamp.from(value); }
    private static Instant instantOrNull(java.sql.ResultSet rs, String column) throws java.sql.SQLException { Timestamp timestamp = rs.getTimestamp(column); return timestamp == null ? null : timestamp.toInstant(); }
    private static String name(Enum<?> value) { return value == null ? null : value.name(); }
    private static <T extends Enum<T>> T enumOrNull(String value, Class<T> type) { return value == null ? null : Enum.valueOf(type, value); }
}
