package cn.servicehub.knowledge.infrastructure;
import cn.servicehub.knowledge.domain.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Repository;
@Repository @Profile("!mysql") public class InMemoryKnowledgeRepository implements KnowledgeRepository {
 private final Map<String,KnowledgeDocument> docs=new ConcurrentHashMap<>(); private final Map<String,KnowledgeDocumentVersion> versions=new ConcurrentHashMap<>(); private final Map<String,KnowledgeImportTask> tasks=new ConcurrentHashMap<>(); private final Map<String,KnowledgeFeedback> feedback=new ConcurrentHashMap<>();
 public void save(KnowledgeDocument d,KnowledgeDocumentVersion v,KnowledgeImportTask t){ if(docs.putIfAbsent(d.id(),d)!=null)throw new IllegalStateException("Knowledge document collision"); versions.put(v.id(),v);tasks.put(t.id(),t); }
 public void saveVersion(KnowledgeDocumentVersion v,KnowledgeImportTask t){ if(!docs.containsKey(v.documentId())||versions.putIfAbsent(v.id(),v)!=null)throw new IllegalArgumentException();tasks.put(t.id(),t); }
 public Optional<KnowledgeDocument> findDocument(String id){return Optional.ofNullable(docs.get(id));} public Optional<KnowledgeDocumentVersion> findVersion(String id){return Optional.ofNullable(versions.get(id));} public List<KnowledgeDocument> findDocuments(){return docs.values().stream().sorted(Comparator.comparing(KnowledgeDocument::updatedAt).reversed()).toList();}
 public List<KnowledgeDocumentVersion> findVersions(String did){return versions.values().stream().filter(v->v.documentId().equals(did)).sorted(Comparator.comparingInt(KnowledgeDocumentVersion::versionNumber).reversed()).toList();}
 public List<KnowledgeImportTask> findImportTasks(){return tasks.values().stream().sorted(Comparator.comparing(KnowledgeImportTask::createdAt).reversed()).toList();}
 public void publish(String did,String vid,String reviewer){ KnowledgeDocument d=docs.get(did);KnowledgeDocumentVersion v=versions.get(vid);if(d==null||v==null||!v.documentId().equals(did)||!Objects.equals(d.owningOrganizationId(),v.owningOrganizationId())||!d.serviceCatalogItemIds().equals(v.serviceCatalogItemIds()))throw new IllegalArgumentException(); Instant now=Instant.now(); versions.put(vid,new KnowledgeDocumentVersion(v.id(),v.documentId(),v.versionNumber(),v.attachmentStorageKey(),v.detectedMediaType(),v.sizeBytes(),v.owningOrganizationId(),v.serviceCatalogItemIds(),KnowledgePublicationStatus.PUBLISHED,reviewer,v.createdAt(),now));docs.put(did,new KnowledgeDocument(d.id(),d.title(),d.categoryCode(),d.tags(),d.owningOrganizationId(),d.serviceCatalogItemIds(),KnowledgePublicationStatus.PUBLISHED,vid,d.creatorIamUserId(),d.createdAt(),now,now.plus(java.time.Duration.ofDays(180)),reviewer,d.sourceTicketId())); }
 public void archive(String did,String reviewer){ KnowledgeDocument d=docs.get(did);if(d==null)throw new IllegalArgumentException(); Instant now=Instant.now(); docs.put(did,new KnowledgeDocument(d.id(),d.title(),d.categoryCode(),d.tags(),d.owningOrganizationId(),d.serviceCatalogItemIds(),KnowledgePublicationStatus.ARCHIVED,d.currentVersionId(),d.creatorIamUserId(),d.createdAt(),now,d.reviewDueAt(),d.reviewOwnerIamUserId(),d.sourceTicketId())); }
 public void completeReview(String did,String reviewer,Instant due){KnowledgeDocument d=docs.get(did);if(d==null||d.status()!=KnowledgePublicationStatus.PUBLISHED)throw new IllegalArgumentException();docs.put(did,new KnowledgeDocument(d.id(),d.title(),d.categoryCode(),d.tags(),d.owningOrganizationId(),d.serviceCatalogItemIds(),d.status(),d.currentVersionId(),d.creatorIamUserId(),d.createdAt(),Instant.now(),due,reviewer,d.sourceTicketId()));}
 public void saveFeedback(KnowledgeFeedback value){feedback.put(value.documentId()+"|"+value.versionId()+"|"+value.voterIamUserId(),value);}
 public List<KnowledgeFeedback> findFeedback(String did,String vid){return feedback.values().stream().filter(v->v.documentId().equals(did)&&v.versionId().equals(vid)).toList();}
}
