package cn.servicehub.knowledge.infrastructure;
import cn.servicehub.knowledge.domain.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.util.*;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
@Repository @Profile("mysql") public class MySqlKnowledgeRepository implements KnowledgeRepository {
 private final JdbcTemplate jdbc; private final ObjectMapper json; public MySqlKnowledgeRepository(JdbcTemplate j,ObjectMapper o){jdbc=j;json=o;}
 @Transactional public void save(KnowledgeDocument d,KnowledgeDocumentVersion v,KnowledgeImportTask t){try{jdbc.update("INSERT INTO knowledge_document (id,title,category_code,tags,status,current_version_id,creator_iam_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)",d.id(),d.title(),d.categoryCode(),json.writeValueAsString(d.tags()),d.status().name(),d.currentVersionId(),d.creatorIamUserId(),Timestamp.from(d.createdAt()),Timestamp.from(d.updatedAt()));jdbc.update("INSERT INTO knowledge_document_version (id,document_id,version_number,attachment_storage_key,detected_media_type,size_bytes,status,reviewer_iam_user_id,created_at,published_at) VALUES (?,?,?,?,?,?,?,?,?,?)",v.id(),v.documentId(),v.versionNumber(),v.attachmentStorageKey(),v.detectedMediaType(),v.sizeBytes(),v.status().name(),v.reviewerIamUserId(),Timestamp.from(v.createdAt()),null);jdbc.update("INSERT INTO knowledge_import_task (id,document_id,source_attachment_id,status,submitter_iam_user_id,error_code,created_at,completed_at) VALUES (?,?,?,?,?,?,?,?)",t.id(),t.documentId(),t.sourceAttachmentId(),t.status(),t.submitterIamUserId(),t.errorCode(),Timestamp.from(t.createdAt()),Timestamp.from(t.completedAt()));}catch(Exception e){throw new IllegalStateException("Knowledge metadata cannot be persisted",e);}}
 public Optional<KnowledgeDocument> findDocument(String id){return jdbc.query("SELECT * FROM knowledge_document WHERE id=?",(rs,row)->doc(rs),id).stream().findFirst();} public Optional<KnowledgeDocumentVersion> findVersion(String id){return jdbc.query("SELECT * FROM knowledge_document_version WHERE id=?",(rs,row)->ver(rs),id).stream().findFirst();} public List<KnowledgeDocument> findDocuments(){return jdbc.query("SELECT * FROM knowledge_document ORDER BY updated_at DESC",(rs,row)->doc(rs));}
 @Transactional public void publish(String did,String vid,String reviewer){if(jdbc.update("UPDATE knowledge_document_version SET status='PUBLISHED', reviewer_iam_user_id=?, published_at=? WHERE id=? AND document_id=? AND status='PENDING_REVIEW'",reviewer,Timestamp.from(java.time.Instant.now()),vid,did)!=1)throw new IllegalArgumentException();jdbc.update("UPDATE knowledge_document SET status='PUBLISHED',current_version_id=?,updated_at=? WHERE id=?",vid,Timestamp.from(java.time.Instant.now()),did);}
 private KnowledgeDocument doc(java.sql.ResultSet r)throws java.sql.SQLException{return new KnowledgeDocument(r.getString("id"),r.getString("title"),r.getString("category_code"),tags(r.getString("tags")),KnowledgePublicationStatus.valueOf(r.getString("status")),r.getString("current_version_id"),r.getString("creator_iam_user_id"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());} private KnowledgeDocumentVersion ver(java.sql.ResultSet r)throws java.sql.SQLException{return new KnowledgeDocumentVersion(r.getString("id"),r.getString("document_id"),r.getInt("version_number"),r.getString("attachment_storage_key"),r.getString("detected_media_type"),r.getLong("size_bytes"),KnowledgePublicationStatus.valueOf(r.getString("status")),r.getString("reviewer_iam_user_id"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("published_at")==null?null:r.getTimestamp("published_at").toInstant());} private List<String> tags(String v){try{return json.readValue(v,new TypeReference<List<String>>(){});}catch(Exception e){throw new IllegalStateException("Stored knowledge tags invalid",e);}}
}
