package cn.servicehub.knowledge.infrastructure;
import cn.servicehub.knowledge.domain.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.util.*;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
@Repository @Profile("mysql") public class MySqlKnowledgeRepository implements KnowledgeRepository {
 private final JdbcTemplate jdbc; private final ObjectMapper json; public MySqlKnowledgeRepository(JdbcTemplate j,ObjectMapper o){jdbc=j;json=o;}
 @Transactional public void save(KnowledgeDocument d,KnowledgeDocumentVersion v,KnowledgeImportTask t){try{jdbc.update("INSERT INTO knowledge_document (id,title,category_code,owning_organization_id,service_catalog_item_ids,tags,status,current_version_id,creator_iam_user_id,created_at,updated_at,review_due_at,review_owner_iam_user_id,source_ticket_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",d.id(),d.title(),d.categoryCode(),d.owningOrganizationId(),json.writeValueAsString(d.serviceCatalogItemIds()),json.writeValueAsString(d.tags()),d.status().name(),d.currentVersionId(),d.creatorIamUserId(),Timestamp.from(d.createdAt()),Timestamp.from(d.updatedAt()),d.reviewDueAt()==null?null:Timestamp.from(d.reviewDueAt()),d.reviewOwnerIamUserId(),d.sourceTicketId());jdbc.update("INSERT INTO knowledge_document_version (id,document_id,version_number,attachment_storage_key,detected_media_type,size_bytes,owning_organization_id,service_catalog_item_ids,status,reviewer_iam_user_id,created_at,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",v.id(),v.documentId(),v.versionNumber(),v.attachmentStorageKey(),v.detectedMediaType(),v.sizeBytes(),v.owningOrganizationId(),json.writeValueAsString(v.serviceCatalogItemIds()),v.status().name(),v.reviewerIamUserId(),Timestamp.from(v.createdAt()),null);jdbc.update("INSERT INTO knowledge_import_task (id,document_id,source_attachment_id,status,submitter_iam_user_id,error_code,created_at,completed_at) VALUES (?,?,?,?,?,?,?,?)",t.id(),t.documentId(),t.sourceAttachmentId(),t.status(),t.submitterIamUserId(),t.errorCode(),Timestamp.from(t.createdAt()),Timestamp.from(t.completedAt()));}catch(Exception e){throw new IllegalStateException("Knowledge metadata cannot be persisted",e);}}
 @Transactional public void saveDraft(KnowledgeDocument d,KnowledgeDocumentVersion v){try{jdbc.update("INSERT INTO knowledge_document (id,title,category_code,owning_organization_id,service_catalog_item_ids,tags,status,current_version_id,creator_iam_user_id,created_at,updated_at,review_due_at,review_owner_iam_user_id,source_ticket_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",d.id(),d.title(),d.categoryCode(),d.owningOrganizationId(),json.writeValueAsString(d.serviceCatalogItemIds()),json.writeValueAsString(d.tags()),d.status().name(),d.currentVersionId(),d.creatorIamUserId(),Timestamp.from(d.createdAt()),Timestamp.from(d.updatedAt()),null,null,d.sourceTicketId());jdbc.update("INSERT INTO knowledge_document_version (id,document_id,version_number,attachment_storage_key,detected_media_type,size_bytes,owning_organization_id,service_catalog_item_ids,status,reviewer_iam_user_id,created_at,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",v.id(),v.documentId(),v.versionNumber(),v.attachmentStorageKey(),v.detectedMediaType(),v.sizeBytes(),v.owningOrganizationId(),json.writeValueAsString(v.serviceCatalogItemIds()),v.status().name(),null,Timestamp.from(v.createdAt()),null);}catch(Exception e){throw new IllegalStateException("Knowledge draft cannot be persisted",e);}}
 @Transactional public void updateDraft(KnowledgeDocument d,KnowledgeDocumentVersion v,String expectedVersionId){try{jdbc.update("INSERT INTO knowledge_document_version (id,document_id,version_number,attachment_storage_key,detected_media_type,size_bytes,owning_organization_id,service_catalog_item_ids,status,reviewer_iam_user_id,created_at,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",v.id(),v.documentId(),v.versionNumber(),v.attachmentStorageKey(),v.detectedMediaType(),v.sizeBytes(),v.owningOrganizationId(),json.writeValueAsString(v.serviceCatalogItemIds()),v.status().name(),null,Timestamp.from(v.createdAt()),null);if(jdbc.update("UPDATE knowledge_document SET title=?,category_code=?,service_catalog_item_ids=?,tags=?,current_version_id=?,updated_at=? WHERE id=? AND creator_iam_user_id=? AND status='DRAFT' AND current_version_id=?",d.title(),d.categoryCode(),json.writeValueAsString(d.serviceCatalogItemIds()),json.writeValueAsString(d.tags()),v.id(),Timestamp.from(d.updatedAt()),d.id(),d.creatorIamUserId(),expectedVersionId)!=1)throw new cn.servicehub.knowledge.application.KnowledgeDraftConflictException();if(jdbc.update("UPDATE knowledge_document_version SET status='SUPERSEDED' WHERE id=? AND document_id=? AND status='DRAFT'",expectedVersionId,d.id())!=1)throw new cn.servicehub.knowledge.application.KnowledgeDraftConflictException();}catch(cn.servicehub.knowledge.application.KnowledgeDraftConflictException|org.springframework.dao.DuplicateKeyException e){throw new cn.servicehub.knowledge.application.KnowledgeDraftConflictException();}catch(Exception e){throw new IllegalStateException("Knowledge draft cannot be updated",e);}}
 @Transactional public void saveVersion(KnowledgeDocumentVersion v,KnowledgeImportTask t){try{jdbc.update("INSERT INTO knowledge_document_version (id,document_id,version_number,attachment_storage_key,detected_media_type,size_bytes,owning_organization_id,service_catalog_item_ids,status,reviewer_iam_user_id,created_at,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",v.id(),v.documentId(),v.versionNumber(),v.attachmentStorageKey(),v.detectedMediaType(),v.sizeBytes(),v.owningOrganizationId(),json.writeValueAsString(v.serviceCatalogItemIds()),v.status().name(),null,Timestamp.from(v.createdAt()),null);jdbc.update("INSERT INTO knowledge_import_task (id,document_id,source_attachment_id,status,submitter_iam_user_id,error_code,created_at,completed_at) VALUES (?,?,?,?,?,?,?,?)",t.id(),t.documentId(),t.sourceAttachmentId(),t.status(),t.submitterIamUserId(),t.errorCode(),Timestamp.from(t.createdAt()),Timestamp.from(t.completedAt()));}catch(Exception e){throw new IllegalStateException("Knowledge version cannot be persisted",e);}}
 public Optional<KnowledgeDocument> findDocument(String id){return jdbc.query("SELECT * FROM knowledge_document WHERE id=?",(rs,row)->doc(rs),id).stream().findFirst();} public Optional<KnowledgeDocumentVersion> findVersion(String id){return jdbc.query("SELECT * FROM knowledge_document_version WHERE id=?",(rs,row)->ver(rs),id).stream().findFirst();} public List<KnowledgeDocument> findDocuments(){return jdbc.query("SELECT * FROM knowledge_document ORDER BY updated_at DESC",(rs,row)->doc(rs));}
 public List<KnowledgeDocumentVersion> findVersions(String did){return jdbc.query("SELECT * FROM knowledge_document_version WHERE document_id=? ORDER BY version_number DESC",(rs,row)->ver(rs),did);} public List<KnowledgeImportTask> findImportTasks(){return jdbc.query("SELECT * FROM knowledge_import_task ORDER BY created_at DESC",(rs,row)->task(rs));}
 @Transactional public void publish(String did,String vid,String reviewer){java.time.Instant now=java.time.Instant.now();jdbc.update("UPDATE knowledge_document_version SET status='SUPERSEDED' WHERE document_id=? AND status='PUBLISHED'",did);if(jdbc.update("UPDATE knowledge_document_version SET status='PUBLISHED', reviewer_iam_user_id=?, published_at=? WHERE id=? AND document_id=? AND status='PENDING_REVIEW'",reviewer,Timestamp.from(now),vid,did)!=1)throw new IllegalArgumentException();if(jdbc.update("UPDATE knowledge_document SET status='PUBLISHED',current_version_id=?,updated_at=?,review_due_at=?,review_owner_iam_user_id=? WHERE id=? AND status IN ('PENDING_REVIEW','PUBLISHED')",vid,Timestamp.from(now),Timestamp.from(now.plus(java.time.Duration.ofDays(180))),reviewer,did)!=1)throw new IllegalArgumentException();}
 @Transactional public void archive(String did,String reviewer){if(jdbc.update("UPDATE knowledge_document SET status='ARCHIVED',updated_at=? WHERE id=? AND status='PUBLISHED'",Timestamp.from(java.time.Instant.now()),did)!=1)throw new IllegalArgumentException();}
 public void completeReview(String did,String reviewer,java.time.Instant due){if(jdbc.update("UPDATE knowledge_document SET review_due_at=?,review_owner_iam_user_id=?,updated_at=? WHERE id=? AND status='PUBLISHED'",Timestamp.from(due),reviewer,Timestamp.from(java.time.Instant.now()),did)!=1)throw new IllegalArgumentException();}
 @Transactional public void submitDraft(String did,String vid,String actor,java.time.Instant submitted){if(jdbc.update("UPDATE knowledge_document_version SET status='PENDING_REVIEW' WHERE id=? AND document_id=? AND status='DRAFT'",vid,did)!=1)throw new IllegalArgumentException();if(jdbc.update("UPDATE knowledge_document SET status='PENDING_REVIEW',updated_at=? WHERE id=? AND current_version_id=? AND creator_iam_user_id=? AND status='DRAFT'",Timestamp.from(submitted),did,vid,actor)!=1)throw new IllegalArgumentException();}
 @Transactional public boolean deleteDraft(String did,String creator){if(jdbc.queryForObject("SELECT COUNT(*) FROM knowledge_document WHERE id=? AND creator_iam_user_id=? AND status='DRAFT'",Long.class,did,creator)!=1)return false;jdbc.update("DELETE FROM knowledge_document_version WHERE document_id=?",did);return jdbc.update("DELETE FROM knowledge_document WHERE id=? AND creator_iam_user_id=? AND status='DRAFT'",did,creator)==1;}
 public boolean isFavorite(String user,String did){Long count=jdbc.queryForObject("SELECT COUNT(*) FROM knowledge_document_favorite WHERE iam_user_id=? AND document_id=?",Long.class,user,did);return count!=null&&count==1;}
 public void saveFavorite(String user,String did,java.time.Instant at){jdbc.update("INSERT INTO knowledge_document_favorite (iam_user_id,document_id,created_at) VALUES (?,?,?) ON DUPLICATE KEY UPDATE created_at=created_at",user,did,Timestamp.from(at));}
 public void deleteFavorite(String user,String did){jdbc.update("DELETE FROM knowledge_document_favorite WHERE iam_user_id=? AND document_id=?",user,did);}
 public List<String> findFavoriteDocumentIds(String user){return jdbc.queryForList("SELECT document_id FROM knowledge_document_favorite WHERE iam_user_id=? ORDER BY created_at DESC",String.class,user);}
 public void saveFeedback(KnowledgeFeedback f){jdbc.update("INSERT INTO knowledge_feedback (document_id,version_id,voter_iam_user_id,feedback_value,reason_code,created_at) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE feedback_value=VALUES(feedback_value),reason_code=VALUES(reason_code),created_at=VALUES(created_at)",f.documentId(),f.versionId(),f.voterIamUserId(),f.value().name(),f.reasonCode(),Timestamp.from(f.createdAt()));}
 public List<KnowledgeFeedback> findFeedback(String did,String vid){return jdbc.query("SELECT * FROM knowledge_feedback WHERE document_id=? AND version_id=?",(r,row)->new KnowledgeFeedback(r.getString("document_id"),r.getString("version_id"),r.getString("voter_iam_user_id"),KnowledgeFeedback.FeedbackValue.valueOf(r.getString("feedback_value")),r.getString("reason_code"),r.getTimestamp("created_at").toInstant()),did,vid);}
 private KnowledgeDocument doc(java.sql.ResultSet r)throws java.sql.SQLException{var due=r.getTimestamp("review_due_at");return new KnowledgeDocument(r.getString("id"),r.getString("title"),r.getString("category_code"),tags(r.getString("tags")),r.getString("owning_organization_id"),tags(r.getString("service_catalog_item_ids")),KnowledgePublicationStatus.valueOf(r.getString("status")),r.getString("current_version_id"),r.getString("creator_iam_user_id"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant(),due==null?null:due.toInstant(),r.getString("review_owner_iam_user_id"),r.getString("source_ticket_id"));} private KnowledgeDocumentVersion ver(java.sql.ResultSet r)throws java.sql.SQLException{return new KnowledgeDocumentVersion(r.getString("id"),r.getString("document_id"),r.getInt("version_number"),r.getString("attachment_storage_key"),r.getString("detected_media_type"),r.getLong("size_bytes"),r.getString("owning_organization_id"),tags(r.getString("service_catalog_item_ids")),KnowledgePublicationStatus.valueOf(r.getString("status")),r.getString("reviewer_iam_user_id"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("published_at")==null?null:r.getTimestamp("published_at").toInstant());} private KnowledgeImportTask task(java.sql.ResultSet r)throws java.sql.SQLException{return new KnowledgeImportTask(r.getString("id"),r.getString("document_id"),r.getString("source_attachment_id"),r.getString("status"),r.getString("submitter_iam_user_id"),r.getString("error_code"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("completed_at")==null?null:r.getTimestamp("completed_at").toInstant());} private List<String> tags(String v){if(v==null)return List.of();try{return json.readValue(v,new TypeReference<List<String>>(){});}catch(Exception e){throw new IllegalStateException("Stored knowledge tags invalid",e);}}
}
