package cn.servicehub.catalog.config;

import cn.servicehub.audit.AuditEvent;
import cn.servicehub.audit.AuditEventPublisher;
import cn.servicehub.catalog.domain.DictionaryDefinition;
import cn.servicehub.catalog.domain.ServiceCatalogRepository;
import cn.servicehub.security.CurrentUser;
import cn.servicehub.security.CurrentUserProvider;
import cn.servicehub.ticket.domain.TicketType;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Clock;
import java.time.Instant;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.slf4j.MDC;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Back-office-only configuration boundary. It accepts metadata, never executable behaviour or system field overrides. */
@Service
public class FormConfigurationService {
    private static final Set<String> WRITE_ROLES = Set.of("ROLE_SERVICE_MANAGER", "ROLE_PLATFORM_ADMIN");
    private static final Set<String> READ_ROLES = Set.of("ROLE_SERVICE_MANAGER", "ROLE_PLATFORM_ADMIN", "ROLE_AUDITOR");
    private static final Set<String> SYSTEM_FIELD_CODES = Set.of("id", "ticket_id", "ticket_no", "status", "priority", "requester", "requester_id", "requester_department", "iam_user_id", "organization", "organization_id", "handler", "assignee", "processor", "workflow", "workflow_instance", "process_instance", "audit", "created_at", "updated_at", "attachments");
    private final FormConfigurationRepository repository; private final ServiceCatalogRepository catalog; private final CurrentUserProvider users; private final AuditEventPublisher audit; private final Clock clock = Clock.systemUTC();
    public FormConfigurationService(FormConfigurationRepository repository, ServiceCatalogRepository catalog, CurrentUserProvider users, AuditEventPublisher audit) { this.repository=repository; this.catalog=catalog; this.users=users; this.audit=audit; }

    public List<ManagedFormConfiguration> list() { CurrentUser actor = requireRead(); List<ManagedFormConfiguration> values = repository.findAll().stream().filter(v -> inScope(actor, v.applicableOrganizationIds())).toList(); publishAudit(actor,"SERVICE_CATALOG_CONFIGURATION_LISTED","collection",Map.of("returned",String.valueOf(values.size()))); return values; }
    public ManagedFormConfiguration get(String id) { CurrentUser actor=requireRead(); ManagedFormConfiguration value = scoped(actor, required(id)); publishAudit(actor,"SERVICE_CATALOG_CONFIGURATION_READ",id,Map.of("version",String.valueOf(value.version()))); return value; }

    @Transactional public ManagedFormConfiguration create(DraftInput input) {
        CurrentUser actor=requireWrite(); validate(input, actor); Instant now=clock.instant(); String id="SC-"+input.code().toLowerCase(java.util.Locale.ROOT).replace('_','-');
        if (repository.findById(id).isPresent()) throw new FormConfigurationConflictException();
        ManagedFormConfiguration value = new ManagedFormConfiguration(id,input.code(),input.name().trim(),cleanOptional(input.summary()),input.ticketType(),input.categoryCode().trim(),sortedDistinct(input.applicableOrganizationIds()),sortedFields(input.fields()),normalizePolicy(input.tagPolicy()),FormConfigurationStatus.DRAFT,0,1,schemaHash(input),input.reason().trim(),actor.iamUserId(),actor.iamUserId(),now,now,null);
        repository.save(value,0); publishAudit(actor,"SERVICE_CATALOG_DRAFT_CREATED",id,Map.of("code",value.code(),"fieldCount",String.valueOf(value.fields().size()))); return value;
    }
    @Transactional public ManagedFormConfiguration update(String id, DraftInput input) {
        CurrentUser actor=requireWrite(); ManagedFormConfiguration before=scoped(actor,required(id)); if (before.status()!=FormConfigurationStatus.DRAFT && before.status()!=FormConfigurationStatus.REJECTED) throw new FormConfigurationValidationException(); if (input.version()!=before.version()) throw new FormConfigurationConflictException(); validate(input,actor); Instant now=clock.instant();
        ManagedFormConfiguration value=new ManagedFormConfiguration(before.id(),input.code(),input.name().trim(),cleanOptional(input.summary()),input.ticketType(),input.categoryCode().trim(),sortedDistinct(input.applicableOrganizationIds()),sortedFields(input.fields()),normalizePolicy(input.tagPolicy()),FormConfigurationStatus.DRAFT,before.version()+1,before.formVersion(),schemaHash(input),input.reason().trim(),before.createdByIamUserId(),actor.iamUserId(),before.createdAt(),now,null);
        repository.save(value,before.version()); publishAudit(actor,"SERVICE_CATALOG_DRAFT_UPDATED",id,Map.of("fromVersion",String.valueOf(before.version()),"toVersion",String.valueOf(value.version()))); return value;
    }
    @Transactional public FormPublicationRequest requestPublication(String id,long version,String reason) {
        CurrentUser actor=requireWrite(); ManagedFormConfiguration c=scoped(actor,required(id)); if(c.status()!=FormConfigurationStatus.DRAFT||c.version()!=version||!validReason(reason)) throw new FormConfigurationValidationException(); validateConfiguration(c,actor); Instant now=clock.instant(); ManagedFormConfiguration pending=copy(c,FormConfigurationStatus.PENDING_REVIEW,c.version()+1,c.formVersion(),actor.iamUserId(),now,null); repository.save(pending,c.version()); FormPublicationRequest request=new FormPublicationRequest("FPR-"+UUID.randomUUID(),id,pending.version(),reason.trim(),actor.iamUserId(),FormConfigurationStatus.PENDING_REVIEW,now,null,null); repository.savePublicationRequest(request); publishAudit(actor,"SERVICE_CATALOG_PUBLICATION_REQUESTED",id,Map.of("requestId",request.id(),"version",String.valueOf(pending.version()))); return request;
    }
    /** Four-eyes release: requester cannot approve own configuration. */
    @Transactional public ManagedFormConfiguration approvePublication(String id,String requestId) {
        CurrentUser actor=requireWrite(); FormPublicationRequest request=repository.findPublicationRequest(requestId).orElseThrow(FormConfigurationValidationException::new); if(!request.catalogItemId().equals(id)||request.status()!=FormConfigurationStatus.PENDING_REVIEW||actor.iamUserId().equals(request.applicantIamUserId())) throw new AccessDeniedException("Publication approval is not authorized"); ManagedFormConfiguration pending=scoped(actor,required(id)); if(pending.status()!=FormConfigurationStatus.PENDING_REVIEW||pending.version()!=request.requestedVersion()) throw new FormConfigurationConflictException(); validateConfiguration(pending,actor); Instant now=clock.instant();
        // Existing published revisions remain immutable history. The approved configuration becomes the current published revision.
        ManagedFormConfiguration published=copy(pending,FormConfigurationStatus.PUBLISHED,pending.version()+1,pending.formVersion()+1,actor.iamUserId(),now,now); repository.save(published,pending.version()); repository.savePublishedSnapshot(published); repository.savePublicationRequest(new FormPublicationRequest(request.id(),request.catalogItemId(),request.requestedVersion(),request.reason(),request.applicantIamUserId(),FormConfigurationStatus.PUBLISHED,request.requestedAt(),actor.iamUserId(),now)); publishAudit(actor,"SERVICE_CATALOG_PUBLICATION_APPROVED",id,Map.of("requestId",requestId,"formVersion",String.valueOf(published.formVersion()))); return published;
    }
    @Transactional public ManagedFormConfiguration retire(String id,long version,String reason) { CurrentUser actor=requireWrite(); ManagedFormConfiguration c=scoped(actor,required(id)); if(c.version()!=version||c.status()!=FormConfigurationStatus.PUBLISHED||!validReason(reason))throw new FormConfigurationValidationException(); ManagedFormConfiguration retired=copy(c,FormConfigurationStatus.RETIRED,c.version()+1,c.formVersion(),actor.iamUserId(),clock.instant(),c.publishedAt());repository.save(retired,c.version());publishAudit(actor,"SERVICE_CATALOG_RETIRED",id,Map.of("reasonLength",String.valueOf(reason.trim().length())));return retired; }
    /** Rollback creates a new draft copied from a prior immutable published revision; it never reopens history. */
    @Transactional public ManagedFormConfiguration rollback(String id,int sourceFormVersion,String reason) { CurrentUser actor=requireWrite(); ManagedFormConfiguration current=scoped(actor,required(id)); if(!validReason(reason))throw new FormConfigurationValidationException(); ManagedFormConfiguration source=repository.findPublishedHistory(current.code()).stream().filter(v->v.formVersion()==sourceFormVersion).findFirst().orElseThrow(FormConfigurationValidationException::new); Instant now=clock.instant(); ManagedFormConfiguration draft=new ManagedFormConfiguration(current.id(),source.code(),source.name(),source.summary(),source.ticketType(),source.categoryCode(),source.applicableOrganizationIds(),source.fields(),source.tagPolicy(),FormConfigurationStatus.DRAFT,current.version()+1,current.formVersion()+1,source.schemaHash(),reason.trim(),current.createdByIamUserId(),actor.iamUserId(),current.createdAt(),now,null);repository.save(draft,current.version());publishAudit(actor,"SERVICE_CATALOG_ROLLBACK_DRAFT_CREATED",id,Map.of("sourceFormVersion",String.valueOf(sourceFormVersion)));return draft; }

    private ManagedFormConfiguration required(String id){return repository.findById(id).orElseThrow(FormConfigurationValidationException::new);} private ManagedFormConfiguration scoped(CurrentUser actor,ManagedFormConfiguration value){if(!inScope(actor,value.applicableOrganizationIds()))throw new AccessDeniedException("Service catalog data scope is not authorized");return value;}
    private CurrentUser requireRead(){CurrentUser a=users.requireCurrentUser();if(a.authorities().stream().noneMatch(READ_ROLES::contains))throw new AccessDeniedException("Service catalog administration is not authorized");return a;} private CurrentUser requireWrite(){CurrentUser a=users.requireCurrentUser();if(a.authorities().stream().noneMatch(WRITE_ROLES::contains))throw new AccessDeniedException("Service catalog administration is not authorized");return a;}
    private boolean inScope(CurrentUser actor,List<String> organizations){if(actor.authorities().contains("ROLE_PLATFORM_ADMIN"))return true;if(organizations.isEmpty())return false;return organizations.stream().allMatch(org->actor.authorities().contains("DATA_SCOPE_ORGANIZATION:"+org));}
    private void validate(DraftInput input,CurrentUser actor){if(input==null||input.version()<0||!validCode(input.code())||blank(input.name())||input.name().trim().length()>200||input.ticketType()==null||blank(input.categoryCode())||input.categoryCode().trim().length()>64||!validReason(input.reason())||input.fields()==null||input.fields().isEmpty()||input.fields().size()>200)throw new FormConfigurationValidationException();if(!inScope(actor,sortedDistinct(input.applicableOrganizationIds())))throw new AccessDeniedException("Service catalog organization data scope is not authorized");validateFields(input.fields());normalizePolicy(input.tagPolicy());}
    private void validateConfiguration(ManagedFormConfiguration c,CurrentUser actor){validate(new DraftInput(c.version(),c.code(),c.name(),c.summary(),c.ticketType(),c.categoryCode(),c.applicableOrganizationIds(),c.fields(),c.tagPolicy(),c.changeReason()),actor);}
    private void validateFields(List<ConfiguredFormField> fields){Set<String> seen=new HashSet<>();Set<Integer> orders=new HashSet<>();for(ConfiguredFormField f:fields){if(f==null||!validFieldCode(f.code())||SYSTEM_FIELD_CODES.contains(f.code())||!seen.add(f.code())||blank(f.label())||f.label().trim().length()>80||f.type()==null||f.displayOrder()<1||f.displayOrder()>500||!orders.add(f.displayOrder())||containsMarkup(f.label())||containsMarkup(f.helpText())||f.helpText()!=null&&f.helpText().length()>300||f.maxLength()!=null&&(f.maxLength()<1||f.maxLength()>4000))throw new FormConfigurationValidationException();
            // Rich text is deliberately a layout alias for the core ticket description, which already has server-side
            // OWASP sanitization, managed image URLs and attachment scan enforcement. Arbitrary dynamic HTML fields
            // would otherwise create a second unsafe rendering/storage path.
            if (f.type()==ConfigurableFormFieldType.RICH_TEXT && !"description".equals(f.code())) throw new FormConfigurationValidationException();
            // The core description and the governed tag area are layout-level controls, not optional arbitrary fields.
            // Hiding either would make the browser/server required semantics diverge, so only conditional requiredness is allowed.
            if ((f.type()==ConfigurableFormFieldType.RICH_TEXT||f.type()==ConfigurableFormFieldType.TAGS) && !f.visibleWhen().isEmpty()) throw new FormConfigurationValidationException();
            if((f.type()==ConfigurableFormFieldType.SINGLE_SELECT||f.type()==ConfigurableFormFieldType.MULTI_SELECT)&&(f.dictionaryCode()==null||catalog.findDictionary(f.dictionaryCode()).filter(d->d.publicationStatus()==cn.servicehub.catalog.domain.CatalogPublicationStatus.PUBLISHED).isEmpty()))throw new FormConfigurationValidationException();if(f.type()!=ConfigurableFormFieldType.SINGLE_SELECT&&f.type()!=ConfigurableFormFieldType.MULTI_SELECT&&f.dictionaryCode()!=null)throw new FormConfigurationValidationException();if(f.defaultValue()!=null&&(f.defaultValue().length()>4000||containsMarkup(f.defaultValue())))throw new FormConfigurationValidationException();validateConditions(f.visibleWhen(),fields,f);validateConditions(f.requiredWhen(),fields,f);} }
    private void validateConditions(List<FormCondition> conditions,List<ConfiguredFormField> all,ConfiguredFormField self){if(conditions==null||conditions.size()>10)throw new FormConfigurationValidationException();Map<String,ConfiguredFormField> map=new HashMap<>();all.forEach(f->map.put(f.code(),f));for(FormCondition c:conditions){if(c==null)throw new FormConfigurationValidationException();ConfiguredFormField dependency=map.get(c.fieldCode());if(dependency==null||dependency.displayOrder()>=self.displayOrder()||c.operator()==null||c.values().size()>50||((c.operator()==FormConditionOperator.HAS_VALUE||c.operator()==FormConditionOperator.NO_VALUE)?!c.values().isEmpty():c.values().isEmpty())||c.values().stream().anyMatch(v->v==null||v.length()>200||containsMarkup(v)))throw new FormConfigurationValidationException();}}
    private TagPolicy normalizePolicy(TagPolicy policy){if(policy==null||policy.maxTags()<0||policy.maxTags()>20||policy.allowedStandardTagCodes().size()>100||policy.allowedStandardTagCodes().stream().anyMatch(v->v==null||!v.matches("^TAG-[A-Za-z0-9_-]{3,60}$")))throw new FormConfigurationValidationException();return new TagPolicy(policy.allowStandardTags(),policy.allowFreeTags(),policy.maxTags(),policy.allowedStandardTagCodes().stream().distinct().sorted().toList());}
    private List<ConfiguredFormField> sortedFields(List<ConfiguredFormField> values){return values.stream().sorted(Comparator.comparingInt(ConfiguredFormField::displayOrder).thenComparing(ConfiguredFormField::code)).toList();} private List<String> sortedDistinct(List<String> values){if(values==null)return List.of();if(values.size()>500||values.stream().anyMatch(v->v==null||!v.matches("^[A-Za-z0-9:_-]{2,128}$")))throw new FormConfigurationValidationException();return values.stream().distinct().sorted().toList();}
    private ManagedFormConfiguration copy(ManagedFormConfiguration c,FormConfigurationStatus status,long version,int formVersion,String actor,Instant now,Instant publishedAt){return new ManagedFormConfiguration(c.id(),c.code(),c.name(),c.summary(),c.ticketType(),c.categoryCode(),c.applicableOrganizationIds(),c.fields(),c.tagPolicy(),status,version,formVersion,c.schemaHash(),c.changeReason(),c.createdByIamUserId(),actor,c.createdAt(),now,publishedAt);}
    private String schemaHash(DraftInput in){String material=in.code()+"\u001f"+in.ticketType()+"\u001f"+sortedFields(in.fields())+"\u001f"+normalizePolicy(in.tagPolicy());try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(material.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("SHA-256 unavailable",e);}}
    private boolean validCode(String v){return v!=null&&v.matches("^[A-Z][A-Z0-9_]{2,63}$");} private boolean validFieldCode(String v){return v!=null&&v.matches("^[a-z][a-z0-9_]{0,63}$");}private boolean validReason(String v){return v!=null&&v.trim().length()>=4&&v.trim().length()<=500&&!containsMarkup(v);}private boolean blank(String v){return v==null||v.trim().isBlank();}private String cleanOptional(String v){if(v==null)return null;if(v.trim().length()>500||containsMarkup(v))throw new FormConfigurationValidationException();return v.trim();}private boolean containsMarkup(String v){return v!=null&&(v.indexOf('<')>=0||v.indexOf('>')>=0||v.chars().anyMatch(Character::isISOControl));}
    private void publishAudit(CurrentUser actor,String action,String resourceId,Map<String,String> attributes){String requestId=MDC.get("requestId");audit.publish(new AuditEvent(clock.instant(),requestId==null?"system":requestId,actor.iamUserId(),action,"service-catalog-form",resourceId,attributes));}
    public record DraftInput(long version,String code,String name,String summary,TicketType ticketType,String categoryCode,List<String> applicableOrganizationIds,List<ConfiguredFormField> fields,TagPolicy tagPolicy,String reason) { }
}
