CREATE TABLE support_queue_command_idempotency (
 actor_iam_user_id VARCHAR(128) NOT NULL,idempotency_key CHAR(36) NOT NULL,operation VARCHAR(64) NOT NULL,resource_type VARCHAR(64) NOT NULL,resource_code VARCHAR(128) NOT NULL,request_fingerprint CHAR(43) NOT NULL,status VARCHAR(24) NOT NULL,response_status INT NULL,response_summary JSON NULL,error_code VARCHAR(80) NULL,created_at DATETIME(6) NOT NULL,completed_at DATETIME(6) NULL,expires_at DATETIME(6) NOT NULL,version BIGINT NOT NULL DEFAULT 0,
 PRIMARY KEY(actor_iam_user_id,idempotency_key),KEY idx_support_queue_command_expiry(status,expires_at),KEY idx_support_queue_command_resource(resource_type,resource_code,created_at),
 CONSTRAINT ck_support_queue_command_status CHECK(status IN('IN_PROGRESS','SUCCEEDED','FAILED_RETRYABLE','FAILED_FINAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE support_queue_migration_plan (
 id VARCHAR(72) NOT NULL,source_queue_code VARCHAR(64) NOT NULL,source_queue_version BIGINT NOT NULL,target_queue_code VARCHAR(64) NOT NULL,target_queue_version BIGINT NOT NULL,owning_organization_id VARCHAR(128) NOT NULL,service_catalog_item_ids_json JSON NOT NULL,service_system_codes_json JSON NOT NULL,configuration_item_count INT NOT NULL,scope_hash CHAR(43) NOT NULL,status VARCHAR(32) NOT NULL,plan_version BIGINT NOT NULL DEFAULT 0,list_snapshot_at DATETIME(6) NOT NULL,checklist_hash CHAR(43) NOT NULL,unclaimed_item_count INT NOT NULL,in_progress_handover_count INT NOT NULL,blocked_item_count INT NOT NULL,succeeded_item_count INT NOT NULL DEFAULT 0,retryable_failed_item_count INT NOT NULL DEFAULT 0,failed_item_count INT NOT NULL DEFAULT 0,created_by_iam_user_id VARCHAR(128) NOT NULL,approved_by_iam_user_id VARCHAR(128) NULL,reason VARCHAR(500) NOT NULL,created_at DATETIME(6) NOT NULL,approved_at DATETIME(6) NULL,execution_started_at DATETIME(6) NULL,completed_at DATETIME(6) NULL,audit_event_id VARCHAR(128) NULL,lease_owner VARCHAR(128) NULL,lease_until DATETIME(6) NULL,
 active_source_queue_code VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN status IN('PENDING_APPROVAL','APPROVED','EXECUTING','PARTIALLY_COMPLETED') THEN source_queue_code ELSE NULL END) STORED,
 PRIMARY KEY(id),UNIQUE KEY uk_support_queue_active_plan(active_source_queue_code),KEY idx_support_queue_plan_status(status,lease_until,created_at),
 CONSTRAINT fk_support_queue_plan_source FOREIGN KEY(source_queue_code) REFERENCES support_queue(queue_code),CONSTRAINT fk_support_queue_plan_target FOREIGN KEY(target_queue_code) REFERENCES support_queue(queue_code),
 CONSTRAINT ck_support_queue_plan_status CHECK(status IN('DRAFT','PREFLIGHT_FAILED','PENDING_APPROVAL','APPROVED','EXECUTING','PARTIALLY_COMPLETED','COMPLETED','FAILED','STALE','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE support_queue_migration_plan_item (
 plan_id VARCHAR(72) NOT NULL,item_id VARCHAR(72) NOT NULL,item_type VARCHAR(32) NOT NULL,status VARCHAR(24) NOT NULL,ticket_id VARCHAR(24) NOT NULL,source_workflow_task_id CHAR(36) NOT NULL,source_ticket_version BIGINT NOT NULL,source_workflow_version BIGINT NOT NULL,source_task_version BIGINT NOT NULL,source_task_status VARCHAR(16) NOT NULL,source_assignee_iam_user_id VARCHAR(128) NULL,source_queue_code VARCHAR(64) NOT NULL,target_queue_code VARCHAR(64) NOT NULL,attempt_count INT NOT NULL DEFAULT 0,retryable BOOLEAN NOT NULL DEFAULT FALSE,result_code VARCHAR(80) NULL,error_code VARCHAR(80) NULL,result_resource_id VARCHAR(128) NULL,handover_task_id VARCHAR(128) NULL,checklist_summary JSON NULL,version BIGINT NOT NULL DEFAULT 0,
 PRIMARY KEY(plan_id,item_id),UNIQUE KEY uk_support_queue_plan_task(plan_id,source_workflow_task_id),KEY idx_support_queue_plan_item_status(plan_id,status,item_type,item_id),
 CONSTRAINT fk_support_queue_plan_item_plan FOREIGN KEY(plan_id) REFERENCES support_queue_migration_plan(id),CONSTRAINT fk_support_queue_plan_item_ticket FOREIGN KEY(ticket_id) REFERENCES ticket(id),CONSTRAINT fk_support_queue_plan_item_task FOREIGN KEY(source_workflow_task_id) REFERENCES ticket_workflow_task(id),
 CONSTRAINT ck_support_queue_plan_item_type CHECK(item_type IN('UNCLAIMED_TASK_MIGRATION','IN_PROGRESS_HANDOVER')),CONSTRAINT ck_support_queue_plan_item_status CHECK(status IN('PENDING','BLOCKED','EXECUTING','SUCCEEDED','RETRYABLE_FAILED','FAILED','STALE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
