package cn.servicehub.ticket.domain;

public enum TicketStatus {
    DRAFT, SUBMITTED, PENDING_CLASSIFICATION, PENDING_ASSIGNMENT, PENDING_ACCEPTANCE, IN_PROGRESS,
    RESOLVED, PENDING_USER_FEEDBACK, CLOSED, CANCELLED, ON_HOLD
}
