const translations: Record<string, string> = {
  'Activate hand tool': '移动画布',
  'Activate lasso tool': '框选多个节点',
  'Activate create/remove space tool': '增加或收拢间距',
  'Activate global connect tool': '连接节点',
  'Create start event': '创建开始事件',
  'Create intermediate/boundary event': '创建中间或边界事件',
  'Create end event': '创建结束事件',
  'Create gateway': '创建分支网关',
  'Create task': '创建任务（可切换为审批/办理任务）',
  'Create data object reference': '创建数据对象引用',
  'Create data store reference': '创建数据存储引用',
  'Create expanded sub-process': '创建展开子流程',
  'Create pool/participant': '创建参与者泳池',
  'Create group': '创建分组',
  'Append end event': '连接结束事件',
  'Append gateway': '连接分支网关',
  'Append task': '连接任务',
  'Append intermediate/boundary event': '连接中间或边界事件',
  'Append receive task': '连接接收任务',
  'Append message intermediate catch event': '连接消息捕获事件',
  'Append timer intermediate catch event': '连接定时捕获事件',
  'Append conditional intermediate catch event': '连接条件捕获事件',
  'Append signal intermediate catch event': '连接信号捕获事件',
  'Append compensation activity': '连接补偿活动',
  'Add lane above': '在上方增加泳道',
  'Add lane below': '在下方增加泳道',
  'Divide into two lanes': '划分为两条泳道',
  'Divide into three lanes': '划分为三条泳道',
  'Change element': '更换节点类型',
  'Add text annotation': '添加文字说明',
  'Connect to other element': '连接其他节点',
  'Connect using association': '使用关联线连接',
  'Connect using data input association': '连接数据输入关联',
  'Delete': '删除',
  'Task': '普通任务',
  'User task': '审批 / 办理任务',
  'Service task': '服务任务（仅设计）',
  'Send task': '发送任务',
  'Receive task': '接收任务',
  'Manual task': '人工任务',
  'Business rule task': '业务规则任务（仅设计）',
  'Script task': '脚本任务（本期不支持保存）',
  'Call activity': '调用活动（仅设计）',
  'Sub-process': '子流程',
  'Expanded sub-process': '展开子流程',
  'Collapsed sub-process': '折叠子流程',
  'Event sub-process': '事件子流程',
  'Ad-hoc sub-process': '即席子流程',
  'Transaction': '事务子流程',
  'Start event': '开始事件',
  'Intermediate throw event': '中间抛出事件',
  'End event': '结束事件',
  'Exclusive gateway': '排他网关',
  'Parallel gateway': '并行网关',
  'Inclusive gateway': '包容网关',
  'Complex gateway': '复杂网关',
  'Event-based gateway': '事件网关',
  'Sequence flow': '顺序流',
  'Default flow': '默认流',
  'Conditional flow': '条件流（本期不支持执行表达式）',
  'Parallel multi-instance': '并行多实例',
  'Sequential multi-instance': '串行多实例',
  'Loop': '循环',
  'Collection': '集合',
  'Participant multiplicity': '参与者多实例',
  'Toggle non-interrupting': '切换非中断模式',
  'Data object reference': '数据对象引用',
  'Data store reference': '数据存储引用',
  'Empty pool/participant': '空泳池 / 参与者',
  'Empty pool/participant (removes content)': '空泳池 / 参与者（将移除内部内容）',
  'Expanded pool/participant': '展开泳池 / 参与者',
  'Search': '搜索节点类型',
  'No results found': '没有匹配的节点类型',
}

export function translateBpmn(template: string, replacements?: Record<string, unknown>): string {
  const text = translations[template] ?? template
  return text.replace(/\{([^}]+)\}/g, (placeholder: string, key: string) => {
    const value = replacements?.[key]
    return value === undefined ? placeholder : String(value)
  })
}
