package cn.servicehub.servicesystem.application;

import cn.servicehub.audit.AuditEvent;
import cn.servicehub.audit.AuditEventPublisher;
import cn.servicehub.catalog.application.ServiceCatalogService;
import cn.servicehub.iam.domain.IamUserProjectionRepository;
import cn.servicehub.security.CurrentUser;
import cn.servicehub.security.CurrentUserProvider;
import cn.servicehub.servicesystem.domain.ServiceSystem;
import cn.servicehub.servicesystem.domain.ServiceSystemCatalogMapping;
import cn.servicehub.servicesystem.domain.ServiceSystemModule;
import cn.servicehub.servicesystem.domain.ServiceSystemRepository;
import cn.servicehub.servicesystem.domain.ServiceSystemStatus;
import cn.servicehub.servicesystem.domain.TicketServiceSystemSnapshot;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import org.slf4j.MDC;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Controlled registry for the requester-facing "affected system" field.  The browser never
 * supplies a display name, organization or routing decision; it supplies only codes which are
 * re-resolved against a published system and an active mapping here.
 */
@Service
public class ServiceSystemRegistryService {
    private static final Set<String> MANAGER_ROLES=Set.of("ROLE_SERVICE_MANAGER","ROLE_PLATFORM_ADMIN");
    private final ServiceSystemRepository repository; private final ServiceCatalogService catalogs;
    private final CurrentUserProvider users; private final IamUserProjectionRepository iamUsers;
    private final AuditEventPublisher audit; private final Clock clock=Clock.systemUTC();
    public ServiceSystemRegistryService(ServiceSystemRepository repository, ServiceCatalogService catalogs, CurrentUserProvider users,
                                        IamUserProjectionRepository iamUsers, AuditEventPublisher audit) { this.repository=repository;this.catalogs=catalogs;this.users=users;this.iamUsers=iamUsers;this.audit=audit; }

    public List<ServiceSystem> listManaged() { CurrentUser a=manager(); List<ServiceSystem> all=repository.findAll().stream().filter(v->inScope(a,v.owningOrganizationId())).toList(); audit(a,"SERVICE_SYSTEM_LISTED","collection",Map.of("returned",String.valueOf(all.size())));return all; }
    public ServiceSystem getManaged(String code) { CurrentUser a=manager(); ServiceSystem v=scoped(a,required(code)); audit(a,"SERVICE_SYSTEM_READ",code,Map.of());return v; }
    @Transactional public ServiceSystem create(SystemInput input) { CurrentUser a=manager(); validateInput(input); if(repository.findByCode(input.code()).isPresent())throw new ServiceSystemConflictException(); requireScope(a,input.owningOrganizationId()); Instant now=clock.instant(); ServiceSystem saved=repository.saveSystem(new ServiceSystem(input.code(),clean(input.name()),cleanNull(input.configurationItemId()),cleanNull(input.ownerIamUserId()),input.owningOrganizationId(),ServiceSystemStatus.DRAFT,0,clean(input.reason()),a.iamUserId(),a.iamUserId(),now,now,null),0);repository.recordLifecycleEvent(saved.code(),saved.version(),saved.status(),"CREATED",a.iamUserId(),saved.changeReason(),now);audit(a,"SERVICE_SYSTEM_CREATED",saved.code(),Map.of("organizationId",saved.owningOrganizationId(),"version",String.valueOf(saved.version())));return saved; }
    @Transactional public ServiceSystem update(String code,SystemInput input) { CurrentUser a=manager(); ServiceSystem current=scoped(a,required(code)); if(current.status()!=ServiceSystemStatus.DRAFT||input.version()!=current.version()||!code.equals(input.code()))throw new ServiceSystemConflictException();validateInput(input);requireScope(a,input.owningOrganizationId());Instant now=clock.instant();ServiceSystem saved=repository.saveSystem(new ServiceSystem(current.code(),clean(input.name()),cleanNull(input.configurationItemId()),cleanNull(input.ownerIamUserId()),input.owningOrganizationId(),ServiceSystemStatus.DRAFT,current.version(),clean(input.reason()),current.createdByIamUserId(),a.iamUserId(),current.createdAt(),now,null),current.version());repository.recordLifecycleEvent(saved.code(),saved.version(),saved.status(),"UPDATED",a.iamUserId(),saved.changeReason(),now);audit(a,"SERVICE_SYSTEM_UPDATED",code,Map.of("version",String.valueOf(saved.version())));return saved; }
    @Transactional public ServiceSystem publish(String code,long version,String reason) { CurrentUser a=manager(); ServiceSystem current=scoped(a,required(code));if(current.status()!=ServiceSystemStatus.DRAFT||current.version()!=version||!validReason(reason))throw new ServiceSystemValidationException();if(!hasActiveMapping(code))throw new ServiceSystemValidationException();Instant now=clock.instant();ServiceSystem saved=repository.saveSystem(new ServiceSystem(current.code(),current.name(),current.configurationItemId(),current.ownerIamUserId(),current.owningOrganizationId(),ServiceSystemStatus.PUBLISHED,current.version(),clean(reason),current.createdByIamUserId(),a.iamUserId(),current.createdAt(),now,now),current.version());repository.recordLifecycleEvent(saved.code(),saved.version(),saved.status(),"PUBLISHED",a.iamUserId(),saved.changeReason(),now);audit(a,"SERVICE_SYSTEM_PUBLISHED",code,Map.of("version",String.valueOf(saved.version())));return saved; }
    @Transactional public ServiceSystem retire(String code,long version,String reason) { CurrentUser a=manager();ServiceSystem current=scoped(a,required(code));if(current.status()!=ServiceSystemStatus.PUBLISHED||current.version()!=version||!validReason(reason))throw new ServiceSystemValidationException();Instant now=clock.instant();ServiceSystem saved=repository.saveSystem(new ServiceSystem(current.code(),current.name(),current.configurationItemId(),current.ownerIamUserId(),current.owningOrganizationId(),ServiceSystemStatus.RETIRED,current.version(),clean(reason),current.createdByIamUserId(),a.iamUserId(),current.createdAt(),now,current.publishedAt()),current.version());repository.recordLifecycleEvent(saved.code(),saved.version(),saved.status(),"RETIRED",a.iamUserId(),saved.changeReason(),now);audit(a,"SERVICE_SYSTEM_RETIRED",code,Map.of("version",String.valueOf(saved.version())));return saved; }

    public List<ServiceSystemModule> modulesManaged(String code){CurrentUser a=manager();scoped(a,required(code));return repository.findModules(code);}
    @Transactional public ServiceSystemModule saveModule(String code,ModuleInput input){CurrentUser a=manager();ServiceSystem s=scoped(a,required(code));requireDraft(s);if(!code.equals(input.systemCode())||!validModule(input))throw new ServiceSystemValidationException();ServiceSystemModule current=repository.findModule(code,input.code()).orElse(null);if((current==null&&input.version()!=0)||(current!=null&&input.version()!=current.version()))throw new ServiceSystemConflictException();ServiceSystemModule saved=repository.saveModule(new ServiceSystemModule(code,input.code(),clean(input.name()),cleanNull(input.path()),input.active(),input.sortOrder(),input.version(),a.iamUserId(),clock.instant()),input.version());audit(a,"SERVICE_SYSTEM_MODULE_SAVED",code+":"+input.code(),Map.of("version",String.valueOf(saved.version())));return saved;}
    public List<ServiceSystemCatalogMapping> systemMappingsManaged(String code){CurrentUser a=manager();scoped(a,required(code));return repository.findSystemCatalogMappings(code);}
    public List<ServiceSystemCatalogMapping> moduleMappingsManaged(String code,String module){CurrentUser a=manager();scoped(a,required(code));if(repository.findModule(code,module).isEmpty())throw new ServiceSystemValidationException();return repository.findModuleCatalogMappings(code,module);}
    @Transactional public ServiceSystemCatalogMapping saveSystemMapping(String code,MappingInput input){CurrentUser a=manager();ServiceSystem s=scoped(a,required(code));requireDraft(s);return saveMapping(a,s,null,input);}
    @Transactional public ServiceSystemCatalogMapping saveModuleMapping(String code,String module,MappingInput input){CurrentUser a=manager();ServiceSystem s=scoped(a,required(code));requireDraft(s);ServiceSystemModule m=repository.findModule(code,module).orElseThrow(ServiceSystemValidationException::new);if(!m.active())throw new ServiceSystemValidationException();return saveMapping(a,s,module,input);}

    /** Requester endpoint: published systems within their current IAM organization only. */
    public List<ServiceSystem> listAvailable(){CurrentUser a=users.requireCurrentUser();String org=currentOrganization(a);List<ServiceSystem> values=repository.findAll().stream().filter(v->v.status()==ServiceSystemStatus.PUBLISHED&&v.owningOrganizationId().equals(org)).toList();audit(a,"SERVICE_SYSTEM_AVAILABLE_LISTED","collection",Map.of("returned",String.valueOf(values.size())));return values;}
    public List<ServiceSystemModule> listAvailableModules(String code){ServiceSystem s=available(required(code));return repository.findModules(s.code()).stream().filter(ServiceSystemModule::active).toList();}
    public List<ServiceSystemCatalogMapping> listAvailableMappings(String code,String moduleCode){ServiceSystem s=available(required(code));if(moduleCode!=null&&!moduleCode.isBlank()){ServiceSystemModule m=repository.findModule(code,moduleCode).filter(ServiceSystemModule::active).orElseThrow(ServiceSystemValidationException::new);List<ServiceSystemCatalogMapping> module=repository.findModuleCatalogMappings(s.code(),m.code()).stream().filter(ServiceSystemCatalogMapping::active).toList();if(!module.isEmpty())return module;}return repository.findSystemCatalogMappings(s.code()).stream().filter(ServiceSystemCatalogMapping::active).toList();}

    /** Complete, server-filtered portal catalog. Mapping precedence is decided before visibility
     * filtering, so an unavailable module offering cannot silently reopen the system defaults. */
    public List<cn.servicehub.catalog.domain.ServiceCatalogItem> listAvailableCatalogItems(String code, String moduleCode) {
        List<ServiceSystemCatalogMapping> mappings = listAvailableMappings(code, moduleCode);
        Set<String> mappedIds = mappings.stream().map(ServiceSystemCatalogMapping::serviceCatalogItemId).collect(java.util.stream.Collectors.toSet());
        String organizationId = currentOrganization(users.requireCurrentUser());
        return catalogs.listPublishedItemsForOrganization(organizationId).stream()
            .filter(item -> mappedIds.contains(item.id())).toList();
    }

    /** Validates the codes before ticket persistence; caller saves the returned immutable snapshot after ID allocation. */
    public ResolvedTicketSelection validateForTicket(String systemCode,String moduleCode,String catalogItemId){if(systemCode==null||systemCode.isBlank()){if(moduleCode!=null&&!moduleCode.isBlank())throw new ServiceSystemValidationException();return null;}ServiceSystem s=available(required(systemCode));ServiceSystemModule module=null;if(moduleCode!=null&&!moduleCode.isBlank())module=repository.findModule(s.code(),moduleCode).filter(ServiceSystemModule::active).orElseThrow(ServiceSystemValidationException::new);List<ServiceSystemCatalogMapping> allowed=module==null?repository.findSystemCatalogMappings(s.code()).stream().filter(ServiceSystemCatalogMapping::active).toList():listAvailableMappings(s.code(),module.code());if(allowed.stream().noneMatch(v->v.serviceCatalogItemId().equals(catalogItemId)))throw new ServiceSystemValidationException();return new ResolvedTicketSelection(s,module,catalogItemId);}
    public void captureTicketSnapshot(String ticketId,ResolvedTicketSelection value){if(value!=null)repository.saveTicketSnapshot(new TicketServiceSystemSnapshot(ticketId,value.system().code(),value.system().name(),value.module()==null?null:value.module().code(),value.module()==null?null:value.module().name(),value.catalogItemId(),value.system().version(),clock.instant()));}
    public Optional<TicketServiceSystemSnapshot> ticketSnapshot(String ticketId){return repository.findTicketSnapshot(ticketId);}

    private ServiceSystemCatalogMapping saveMapping(CurrentUser a,ServiceSystem s,String module,MappingInput input){if(input==null||!validCatalog(input.serviceCatalogItemId())||input.version()<0)throw new ServiceSystemValidationException();catalogs.getPublishedItem(input.serviceCatalogItemId());ServiceSystemCatalogMapping current=(module==null?repository.findSystemCatalogMappings(s.code()):repository.findModuleCatalogMappings(s.code(),module)).stream().filter(v->v.serviceCatalogItemId().equals(input.serviceCatalogItemId())).findFirst().orElse(null);if((current==null&&input.version()!=0)||(current!=null&&input.version()!=current.version()))throw new ServiceSystemConflictException();ServiceSystemCatalogMapping saved=repository.saveCatalogMapping(new ServiceSystemCatalogMapping(s.code(),module,input.serviceCatalogItemId(),input.active(),input.defaultMapping(),input.version(),a.iamUserId(),clock.instant()),input.version());audit(a,"SERVICE_SYSTEM_CATALOG_MAPPING_SAVED",s.code()+":"+(module==null?"system":module)+":"+input.serviceCatalogItemId(),Map.of("active",String.valueOf(saved.active()),"version",String.valueOf(saved.version())));return saved;}
    private boolean hasActiveMapping(String systemCode){if(repository.findSystemCatalogMappings(systemCode).stream().anyMatch(ServiceSystemCatalogMapping::active))return true;return repository.findModules(systemCode).stream().flatMap(module->repository.findModuleCatalogMappings(systemCode,module.code()).stream()).anyMatch(ServiceSystemCatalogMapping::active);}
    private ServiceSystem available(ServiceSystem s){CurrentUser a=users.requireCurrentUser();if(s.status()!=ServiceSystemStatus.PUBLISHED||!s.owningOrganizationId().equals(currentOrganization(a)))throw new AccessDeniedException("Affected system is not available in current IAM organization");return s;}
    private String currentOrganization(CurrentUser a){return iamUsers.findActiveByIamUserId(a.iamUserId()).orElseThrow(()->new AccessDeniedException("Active IAM projection is required")).organization().iamOrganizationId();}
    private CurrentUser manager(){CurrentUser a=users.requireCurrentUser();if(a.authorities().stream().noneMatch(MANAGER_ROLES::contains))throw new AccessDeniedException("Service system administration is not authorized");return a;}
    private ServiceSystem required(String code){return repository.findByCode(code).orElseThrow(ServiceSystemValidationException::new);} private ServiceSystem scoped(CurrentUser a,ServiceSystem s){requireScope(a,s.owningOrganizationId());return s;} private void requireScope(CurrentUser a,String org){if(!inScope(a,org))throw new AccessDeniedException("Service system organization scope is not authorized");} private boolean inScope(CurrentUser a,String org){return a.authorities().contains("ROLE_PLATFORM_ADMIN")||a.authorities().contains("DATA_SCOPE_ORGANIZATION:"+org);} private void requireDraft(ServiceSystem s){if(s.status()!=ServiceSystemStatus.DRAFT)throw new ServiceSystemValidationException();}
    private void validateInput(SystemInput v){if(v==null||!validSystem(v.code())||blank(v.name())||v.name().trim().length()>200||!validOrg(v.owningOrganizationId())||!validReason(v.reason())||v.version()<0)throw new ServiceSystemValidationException();} private boolean validModule(ModuleInput v){return v!=null&&validModuleCode(v.code())&&!blank(v.name())&&v.name().trim().length()<=200&&v.sortOrder()>=0&&v.sortOrder()<=10000&&v.version()>=0&&(v.path()==null||v.path().trim().length()<=500);} private boolean validSystem(String v){return v!=null&&v.matches("^[A-Z][A-Z0-9_]{2,63}$");} private boolean validModuleCode(String v){return v!=null&&v.matches("^[A-Z][A-Z0-9_]{1,63}$");} private boolean validCatalog(String v){return v!=null&&v.matches("^[A-Za-z0-9_-]{3,64}$");} private boolean validOrg(String v){return v!=null&&v.matches("^[A-Za-z0-9._:-]{1,128}$");} private boolean validReason(String v){return !blank(v)&&v.trim().length()>=4&&v.trim().length()<=500;} private boolean blank(String v){return v==null||v.trim().isEmpty();} private String clean(String v){return v.trim();} private String cleanNull(String v){return blank(v)?null:v.trim();}
    private void audit(CurrentUser a,String action,String id,Map<String,String> attrs){audit.publish(new AuditEvent(clock.instant(),MDC.get("requestId")==null?"system":MDC.get("requestId"),a.iamUserId(),action,"service-system",id,attrs));}
    public record SystemInput(String code,String name,String configurationItemId,String ownerIamUserId,String owningOrganizationId,long version,String reason){} public record ModuleInput(String systemCode,String code,String name,String path,boolean active,int sortOrder,long version){} public record MappingInput(String serviceCatalogItemId,boolean active,boolean defaultMapping,long version){} public record ResolvedTicketSelection(ServiceSystem system,ServiceSystemModule module,String catalogItemId){}
}
