package cn.servicehub.workflow.team;

import java.time.Instant;import java.util.Map;import java.util.Optional;import java.util.concurrent.ConcurrentHashMap;import org.springframework.context.annotation.Profile;import org.springframework.stereotype.Repository;
@Repository @Profile("!mysql") public class InMemorySupportQueueCommandRepository implements SupportQueueCommandRepository{
 private final Map<String,SupportQueueCommandRecord>values=new ConcurrentHashMap<>();private String k(String a,String k){return a+"\n"+k;}
 public Optional<SupportQueueCommandRecord>find(String a,String key){return Optional.ofNullable(values.get(k(a,key)));}
 public boolean reserve(SupportQueueCommandRecord r){return values.putIfAbsent(k(r.actorIamUserId(),r.idempotencyKey()),r)==null;}
 public synchronized boolean takeover(String a,String key,long v,String old,String owner,Instant lease){SupportQueueCommandRecord r=values.get(k(a,key));if(r==null||r.version()!=v||!"IN_PROGRESS".equals(r.status())||!java.util.Objects.equals(old,r.leaseOwner())||r.leaseExpiresAt()==null||!r.leaseExpiresAt().isBefore(Instant.now()))return false;values.put(k(a,key),copy(r,"IN_PROGRESS",v+1,owner,lease,r.attemptCount()+1,null,null,null,null));return true;}
 public synchronized boolean completeByReconciliation(String a,String key,long v,String old,int status,String response,String type,String id){SupportQueueCommandRecord r=values.get(k(a,key));if(r==null||r.version()!=v||!java.util.Objects.equals(old,r.leaseOwner()))return false;values.put(k(a,key),copy(r,"SUCCEEDED",v+1,r.leaseOwner(),r.leaseExpiresAt(),r.attemptCount(),type,id,response,status));return true;}
 public synchronized boolean heartbeat(String a,String key,long v,String owner,Instant lease){SupportQueueCommandRecord r=values.get(k(a,key));if(r==null||r.version()!=v||!"IN_PROGRESS".equals(r.status())||!owner.equals(r.leaseOwner()))return false;values.put(k(a,key),new SupportQueueCommandRecord(r.actorIamUserId(),r.idempotencyKey(),r.operation(),r.resourceType(),r.resourceCode(),r.requestFingerprint(),r.status(),r.responseStatus(),r.responseSummary(),r.errorCode(),r.createdAt(),r.completedAt(),r.expiresAt(),v+1,owner,lease,r.attemptCount(),r.keyVersion(),r.resultResourceType(),r.resultResourceId(),Instant.now()));return true;}
 public synchronized boolean reconciliationRequired(String a,String key,long v,String owner,String error){SupportQueueCommandRecord r=values.get(k(a,key));if(r==null||r.version()!=v||!"IN_PROGRESS".equals(r.status())||!java.util.Objects.equals(owner,r.leaseOwner()))return false;values.put(k(a,key),new SupportQueueCommandRecord(r.actorIamUserId(),r.idempotencyKey(),r.operation(),r.resourceType(),r.resourceCode(),r.requestFingerprint(),"RECONCILIATION_REQUIRED",null,null,error,r.createdAt(),Instant.now(),r.expiresAt(),v+1,owner,r.leaseExpiresAt(),r.attemptCount(),r.keyVersion(),r.resultResourceType(),r.resultResourceId(),Instant.now()));return true;}
 public synchronized boolean resolveReconciliation(String a,String key,long v,String decision,String type,String id,String approver){SupportQueueCommandRecord r=values.get(k(a,key));if(r==null||r.version()!=v||!"RECONCILIATION_REQUIRED".equals(r.status())||!"LEGACY_UNVERIFIABLE".equals(r.keyVersion()))return false;values.put(k(a,key),new SupportQueueCommandRecord(r.actorIamUserId(),r.idempotencyKey(),r.operation(),r.resourceType(),r.resourceCode(),r.requestFingerprint(),decision,null,null,"MANUAL_RECONCILIATION",r.createdAt(),Instant.now(),r.expiresAt(),v+1,null,null,r.attemptCount(),r.keyVersion(),type,id,Instant.now()));return true;}
 public synchronized void complete(String a,String key,long v,String owner,int status,String response,String type,String id){SupportQueueCommandRecord r=values.get(k(a,key));if(r==null||r.version()!=v||!owner.equals(r.leaseOwner()))throw new cn.servicehub.workflow.application.WorkflowConflictException();values.put(k(a,key),copy(r,"SUCCEEDED",v+1,owner,r.leaseExpiresAt(),r.attemptCount(),type,id,response,status));}
 public void fail(String a,String key,long v,boolean retry,String error){values.compute(k(a,key),(x,r)->r!=null&&r.version()==v?new SupportQueueCommandRecord(r.actorIamUserId(),r.idempotencyKey(),r.operation(),r.resourceType(),r.resourceCode(),r.requestFingerprint(),retry?"FAILED_RETRYABLE":"FAILED_FINAL",null,null,error,r.createdAt(),Instant.now(),r.expiresAt(),v+1,r.leaseOwner(),r.leaseExpiresAt(),r.attemptCount(),r.keyVersion(),r.resultResourceType(),r.resultResourceId(),Instant.now()):r);}
 private SupportQueueCommandRecord copy(SupportQueueCommandRecord r,String state,long version,String owner,Instant lease,int attempts,String type,String id,String response,Integer responseStatus){return new SupportQueueCommandRecord(r.actorIamUserId(),r.idempotencyKey(),r.operation(),r.resourceType(),r.resourceCode(),r.requestFingerprint(),state,responseStatus,response,r.errorCode(),r.createdAt(),"SUCCEEDED".equals(state)?Instant.now():r.completedAt(),r.expiresAt(),version,owner,lease,attempts,r.keyVersion(),type,id,Instant.now());}
}
