package cn.servicehub.workflow.team;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import java.sql.Timestamp;import java.util.List;import java.util.Optional;import java.util.Set;import org.springframework.context.annotation.Profile;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository @Profile("mysql") public class MySqlSupportQueueMigrationRepository implements SupportQueueMigrationRepository{
 private final JdbcTemplate jdbc;private final ObjectMapper json;public MySqlSupportQueueMigrationRepository(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
 public Optional<SupportQueueMigrationPlan>findPlan(String id){return jdbc.query("SELECT * FROM support_queue_migration_plan WHERE id=?",(rs,n)->plan(rs),id).stream().findFirst();}
 public Optional<SupportQueueMigrationPlan>findActiveBySource(String source){return jdbc.query("SELECT * FROM support_queue_migration_plan WHERE active_source_queue_code=?",(rs,n)->plan(rs),source).stream().findFirst();}
 public List<SupportQueueMigrationPlanItem>findItems(String id){return jdbc.query("SELECT * FROM support_queue_migration_plan_item WHERE plan_id=? ORDER BY item_id",(rs,n)->item(rs),id);}
 public void create(SupportQueueMigrationPlan p,List<SupportQueueMigrationPlanItem>items){try{jdbc.update("INSERT INTO support_queue_migration_plan(id,source_queue_code,source_queue_version,target_queue_code,target_queue_version,owning_organization_id,service_catalog_item_ids_json,service_system_codes_json,configuration_item_count,scope_hash,status,plan_version,list_snapshot_at,checklist_hash,unclaimed_item_count,in_progress_handover_count,blocked_item_count,succeeded_item_count,retryable_failed_item_count,failed_item_count,created_by_iam_user_id,reason,created_at,audit_event_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",p.id(),p.sourceQueueCode(),p.sourceQueueVersion(),p.targetQueueCode(),p.targetQueueVersion(),p.scopeSummary().owningOrganizationId(),json.writeValueAsString(p.scopeSummary().serviceCatalogItemIds()),json.writeValueAsString(p.scopeSummary().serviceSystemCodes()),p.scopeSummary().configurationItemCount(),p.scopeSummary().scopeHash(),p.status().name(),p.planVersion(),ts(p.listSnapshotAt()),p.checklistHash(),p.unclaimedItemCount(),p.inProgressHandoverCount(),p.blockedItemCount(),0,0,0,p.createdByIamUserId(),p.reason(),ts(p.createdAt()),p.auditEventId());for(SupportQueueMigrationPlanItem i:items)jdbc.update("INSERT INTO support_queue_migration_plan_item(plan_id,item_id,item_type,status,ticket_id,source_workflow_task_id,source_ticket_version,source_workflow_version,source_task_version,source_task_status,source_assignee_iam_user_id,source_queue_code,target_queue_code,attempt_count,retryable,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)",p.id(),i.itemId(),i.itemType().name(),i.status().name(),i.ticketId(),i.sourceWorkflowTaskId(),i.sourceTicketVersion(),i.sourceWorkflowVersion(),i.sourceTaskVersion(),i.sourceTaskStatus(),i.sourceAssigneeIamUserId(),i.sourceQueueCode(),i.targetQueueCode(),i.attemptCount(),i.retryable());}catch(org.springframework.dao.DuplicateKeyException e){throw new cn.servicehub.workflow.application.WorkflowConflictException();}catch(Exception e){throw new IllegalStateException("Queue migration plan cannot be persisted",e);}}
 public boolean updatePlan(SupportQueueMigrationPlan p,long v,SupportQueueMigrationPlanStatus expected){return jdbc.update("UPDATE support_queue_migration_plan SET status=?,plan_version=?,succeeded_item_count=?,retryable_failed_item_count=?,failed_item_count=?,approved_by_iam_user_id=?,approved_at=?,execution_started_at=?,completed_at=?,audit_event_id=? WHERE id=? AND plan_version=? AND status=?",p.status().name(),p.planVersion(),p.succeededItemCount(),p.retryableFailedItemCount(),p.failedItemCount(),p.approvedByIamUserId(),ts(p.approvedAt()),ts(p.executionStartedAt()),ts(p.completedAt()),p.auditEventId(),p.id(),v,expected.name())==1;}
 public boolean updateItem(String plan,SupportQueueMigrationPlanItem i,long v,SupportQueueMigrationItemStatus expected){return jdbc.update("UPDATE support_queue_migration_plan_item SET status=?,attempt_count=?,retryable=?,result_code=?,error_code=?,result_resource_id=?,handover_task_id=?,checklist_summary=?,version=? WHERE plan_id=? AND item_id=? AND version=? AND status=?",i.status().name(),i.attemptCount(),i.retryable(),i.resultCode(),i.errorCode(),i.resultResourceId(),i.handoverTaskId(),i.checklistSummary(),i.version(),plan,i.itemId(),v,expected.name())==1;}
 private SupportQueueMigrationPlan plan(java.sql.ResultSet r)throws java.sql.SQLException{try{return new SupportQueueMigrationPlan(r.getString("id"),r.getString("source_queue_code"),r.getLong("source_queue_version"),r.getString("target_queue_code"),r.getLong("target_queue_version"),new SupportQueueMigrationPlan.ScopeSummary(r.getString("owning_organization_id"),json.readValue(r.getString("service_catalog_item_ids_json"),new TypeReference<Set<String>>(){}),json.readValue(r.getString("service_system_codes_json"),new TypeReference<Set<String>>(){}),r.getInt("configuration_item_count"),r.getString("scope_hash")),SupportQueueMigrationPlanStatus.valueOf(r.getString("status")),r.getLong("plan_version"),r.getTimestamp("list_snapshot_at").toInstant(),r.getString("checklist_hash"),r.getLong("unclaimed_item_count"),r.getLong("in_progress_handover_count"),r.getLong("blocked_item_count"),r.getLong("succeeded_item_count"),r.getLong("retryable_failed_item_count"),r.getLong("failed_item_count"),r.getString("created_by_iam_user_id"),r.getString("approved_by_iam_user_id"),r.getString("reason"),r.getTimestamp("created_at").toInstant(),instant(r.getTimestamp("approved_at")),instant(r.getTimestamp("execution_started_at")),instant(r.getTimestamp("completed_at")),r.getString("audit_event_id"));}catch(Exception e){throw new java.sql.SQLException(e);}}
 private SupportQueueMigrationPlanItem item(java.sql.ResultSet r)throws java.sql.SQLException{return new SupportQueueMigrationPlanItem(r.getString("item_id"),SupportQueueMigrationItemType.valueOf(r.getString("item_type")),SupportQueueMigrationItemStatus.valueOf(r.getString("status")),r.getString("ticket_id"),r.getString("source_workflow_task_id"),r.getLong("source_ticket_version"),r.getLong("source_workflow_version"),r.getLong("source_task_version"),r.getString("source_task_status"),r.getString("source_assignee_iam_user_id"),r.getString("source_queue_code"),r.getString("target_queue_code"),r.getInt("attempt_count"),r.getBoolean("retryable"),r.getString("result_code"),r.getString("error_code"),r.getString("result_resource_id"),r.getString("handover_task_id"),r.getString("checklist_summary"),r.getLong("version"));}
 private static Timestamp ts(java.time.Instant i){return i==null?null:Timestamp.from(i);}private static java.time.Instant instant(Timestamp t){return t==null?null:t.toInstant();}
}
