package cn.servicehub.workflow.team;

import java.sql.Timestamp;import java.util.Optional;import org.springframework.context.annotation.Profile;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository @Profile("mysql") public class MySqlSupportQueueCommandRepository implements SupportQueueCommandRepository{
 private final JdbcTemplate jdbc;public MySqlSupportQueueCommandRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public Optional<SupportQueueCommandRecord>find(String a,String key){return jdbc.query("SELECT * FROM support_queue_command_idempotency WHERE actor_iam_user_id=? AND idempotency_key=?",(rs,n)->new SupportQueueCommandRecord(rs.getString("actor_iam_user_id"),rs.getString("idempotency_key"),rs.getString("operation"),rs.getString("resource_type"),rs.getString("resource_code"),rs.getString("request_fingerprint"),rs.getString("status"),(Integer)rs.getObject("response_status"),rs.getString("response_summary"),rs.getString("error_code"),rs.getTimestamp("created_at").toInstant(),instant(rs.getTimestamp("completed_at")),rs.getTimestamp("expires_at").toInstant(),rs.getLong("version"),rs.getString("lease_owner"),instant(rs.getTimestamp("lease_expires_at")),rs.getInt("attempt_count"),rs.getString("key_version"),rs.getString("result_resource_type"),rs.getString("result_resource_id"),instant(rs.getTimestamp("heartbeat_at"))),a,key).stream().findFirst();}
 public boolean reserve(SupportQueueCommandRecord r){try{return jdbc.update("INSERT INTO support_queue_command_idempotency(actor_iam_user_id,idempotency_key,operation,resource_type,resource_code,request_fingerprint,status,created_at,expires_at,version,lease_owner,lease_expires_at,attempt_count,key_version,heartbeat_at) VALUES(?,?,?,?,?,?,'IN_PROGRESS',?,?,0,?,?,1,?,?)",r.actorIamUserId(),r.idempotencyKey(),r.operation(),r.resourceType(),r.resourceCode(),r.requestFingerprint(),Timestamp.from(r.createdAt()),Timestamp.from(r.expiresAt()),r.leaseOwner(),Timestamp.from(r.leaseExpiresAt()),r.keyVersion(),Timestamp.from(r.heartbeatAt()))==1;}catch(org.springframework.dao.DuplicateKeyException e){return false;}}
 public boolean takeover(String a,String key,long v,String old,String owner,java.time.Instant lease){return jdbc.update("UPDATE support_queue_command_idempotency SET lease_owner=?,lease_expires_at=?,heartbeat_at=UTC_TIMESTAMP(6),attempt_count=attempt_count+1,version=version+1 WHERE actor_iam_user_id=? AND idempotency_key=? AND version=? AND status='IN_PROGRESS' AND lease_owner=? AND lease_expires_at<UTC_TIMESTAMP(6)",owner,Timestamp.from(lease),a,key,v,old)==1;}
 public boolean completeByReconciliation(String a,String key,long v,String old,int status,String response,String type,String id){return jdbc.update("UPDATE support_queue_command_idempotency SET status='SUCCEEDED',response_status=?,response_summary=?,result_resource_type=?,result_resource_id=?,completed_at=UTC_TIMESTAMP(6),version=version+1 WHERE actor_iam_user_id=? AND idempotency_key=? AND version=? AND status IN('IN_PROGRESS','RECONCILIATION_REQUIRED') AND lease_owner=?",status,response,type,id,a,key,v,old)==1;}
 public boolean heartbeat(String a,String key,long v,String owner,java.time.Instant lease){return jdbc.update("UPDATE support_queue_command_idempotency SET lease_expires_at=?,heartbeat_at=UTC_TIMESTAMP(6),version=version+1 WHERE actor_iam_user_id=? AND idempotency_key=? AND version=? AND status='IN_PROGRESS' AND lease_owner=?",Timestamp.from(lease),a,key,v,owner)==1;}
 public boolean reconciliationRequired(String a,String key,long v,String owner,String error){return jdbc.update("UPDATE support_queue_command_idempotency SET status='RECONCILIATION_REQUIRED',error_code=?,completed_at=UTC_TIMESTAMP(6),version=version+1 WHERE actor_iam_user_id=? AND idempotency_key=? AND version=? AND status='IN_PROGRESS' AND lease_owner=?",error,a,key,v,owner)==1;}
 public boolean resolveReconciliation(String a,String key,long v,String decision,String type,String id,String approver){return jdbc.update("UPDATE support_queue_command_idempotency SET status=?,result_resource_type=?,result_resource_id=?,response_summary=NULL,error_code='MANUAL_RECONCILIATION',lease_owner=NULL,lease_expires_at=NULL,heartbeat_at=NULL,completed_at=UTC_TIMESTAMP(6),version=version+1 WHERE actor_iam_user_id=? AND idempotency_key=? AND version=? AND status='RECONCILIATION_REQUIRED' AND key_version='LEGACY_UNVERIFIABLE'",decision,type,id,a,key,v)==1;}
 public void complete(String a,String key,long v,String owner,int status,String response,String type,String id){if(jdbc.update("UPDATE support_queue_command_idempotency SET status='SUCCEEDED',response_status=?,response_summary=?,result_resource_type=?,result_resource_id=?,completed_at=UTC_TIMESTAMP(6),version=version+1 WHERE actor_iam_user_id=? AND idempotency_key=? AND version=? AND status='IN_PROGRESS' AND lease_owner=?",status,response,type,id,a,key,v,owner)!=1)throw new cn.servicehub.workflow.application.WorkflowConflictException();}
 public void fail(String a,String key,long v,boolean retry,String error){jdbc.update("UPDATE support_queue_command_idempotency SET status=?,error_code=?,completed_at=UTC_TIMESTAMP(6),version=version+1 WHERE actor_iam_user_id=? AND idempotency_key=? AND version=?",retry?"FAILED_RETRYABLE":"FAILED_FINAL",error,a,key,v);}
 private static java.time.Instant instant(Timestamp v){return v==null?null:v.toInstant();}
}
