package cn.servicehub.workflow.team;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

@RestController @Validated @RequestMapping("/api/v1/admin/support-queues")
public class SupportQueueAdminController {
    private static final String CODE="^[A-Z][A-Z0-9_-]{1,63}$";
    private final SupportQueueService service;private final SupportQueueCommandIdempotencyService idempotency;private final SupportQueueMigrationService migrations;private final SupportQueueReconciliationService reconciliations;public SupportQueueAdminController(SupportQueueService service,SupportQueueCommandIdempotencyService idempotency,SupportQueueMigrationService migrations,SupportQueueReconciliationService reconciliations){this.service=service;this.idempotency=idempotency;this.migrations=migrations;this.reconciliations=reconciliations;}
    @GetMapping Page list(@RequestParam(defaultValue="1")@Min(1)int page,@RequestParam(defaultValue="20")@Min(1)@Max(100)int pageSize,@RequestParam(required=false)SupportQueueStatus status){return Page.from(service.list(page,pageSize,status));}
    @GetMapping("/commands/{key}")SupportQueueCommandIdempotencyService.CommandStatus commandStatus(@PathVariable@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key){return idempotency.status(key);}
    @PostMapping("/commands/{targetActor}/{key}/reconciliation-requests")@ResponseStatus(HttpStatus.CREATED)SupportQueueReconciliationRequest requestReconciliation(@PathVariable@Pattern(regexp="^[A-Za-z0-9._:-]{1,128}$")String targetActor,@PathVariable@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody ReconciliationRequest r){return reconciliations.request(targetActor,key,r.commandVersion(),r.decision(),r.resultResourceType(),r.resultResourceId(),r.reason());}
    @PostMapping("/reconciliation-requests/{requestId}/approve")SupportQueueReconciliationRequest approveReconciliation(@PathVariable@Pattern(regexp="^SQRR-[A-Za-z0-9_-]{8,64}$")String requestId,@Valid@RequestBody ReconciliationApproveRequest r){return reconciliations.approve(requestId,r.expectedVersion(),r.reason());}
    @PostMapping @ResponseStatus(HttpStatus.CREATED) Response create(@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody CreateRequest r){return idempotency.execute(key,"CREATE","support-queue",r.code(),r,201,Response.class,()->Response.from(service.create(r.input())));}
    @GetMapping("/{code}") Response get(@PathVariable@Pattern(regexp=CODE)String code){return Response.from(service.get(code));}
    @PutMapping("/{code}") Response update(@PathVariable@Pattern(regexp=CODE)String code,@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody UpdateRequest r){return idempotency.execute(key,"UPDATE","support-queue",code,r,200,Response.class,()->Response.from(service.update(code,r.input(code))));}
    @PostMapping("/{code}/activate") Response activate(@PathVariable@Pattern(regexp=CODE)String code,@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody StateRequest r){return idempotency.execute(key,"ACTIVATE","support-queue",code,r,200,Response.class,()->Response.from(service.activate(code,r.expectedVersion(),r.reason())));}
    @PostMapping("/{code}/deactivate") SupportQueueService.DeactivationResult deactivate(@PathVariable@Pattern(regexp=CODE)String code,@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody StateRequest r){return idempotency.execute(key,"DEACTIVATE","support-queue",code,r,200,SupportQueueService.DeactivationResult.class,()->service.deactivate(code,r.expectedVersion(),r.reason(),r.replacementQueueCode()));}
    @PostMapping("/{code}/migration-plans")@ResponseStatus(HttpStatus.CREATED) SupportQueueMigrationPlan preflight(@PathVariable@Pattern(regexp=CODE)String code,@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody MigrationCreateRequest r){return idempotency.execute(key,"MIGRATION_PREFLIGHT","support-queue",code,r,201,SupportQueueMigrationPlan.class,()->migrations.preflight(code,r.sourceQueueExpectedVersion(),r.targetQueueCode(),r.targetQueueExpectedVersion(),r.reason()));}
    @GetMapping("/{code}/migration-plans/{planId}")SupportQueueMigrationService.PlanView migration(@PathVariable@Pattern(regexp=CODE)String code,@PathVariable@Pattern(regexp="^SQMP-[A-Za-z0-9_-]{8,64}$")String planId,@RequestParam(defaultValue="1")@Min(1)int page,@RequestParam(defaultValue="20")@Min(1)@Max(100)int pageSize){return migrations.get(code,planId,page,pageSize);}
    @PostMapping("/{code}/migration-plans/{planId}/approve")SupportQueueMigrationPlan approve(@PathVariable@Pattern(regexp=CODE)String code,@PathVariable@Pattern(regexp="^SQMP-[A-Za-z0-9_-]{8,64}$")String planId,@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody MigrationCommandRequest r){return command(key,"MIGRATION_APPROVE",code,planId,r,()->migrations.approve(code,planId,r.expectedPlanVersion(),r.reason()));}
    @PostMapping("/{code}/migration-plans/{planId}/execute")@ResponseStatus(HttpStatus.ACCEPTED)SupportQueueMigrationPlan execute(@PathVariable@Pattern(regexp=CODE)String code,@PathVariable@Pattern(regexp="^SQMP-[A-Za-z0-9_-]{8,64}$")String planId,@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody MigrationCommandRequest r){return command(key,"MIGRATION_EXECUTE",code,planId,r,()->migrations.execute(code,planId,r.expectedPlanVersion(),r.reason(),false));}
    @PostMapping("/{code}/migration-plans/{planId}/retry")@ResponseStatus(HttpStatus.ACCEPTED)SupportQueueMigrationPlan retry(@PathVariable@Pattern(regexp=CODE)String code,@PathVariable@Pattern(regexp="^SQMP-[A-Za-z0-9_-]{8,64}$")String planId,@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody MigrationCommandRequest r){return command(key,"MIGRATION_RETRY",code,planId,r,()->migrations.execute(code,planId,r.expectedPlanVersion(),r.reason(),true));}
    @PostMapping("/{code}/migration-plans/{planId}/cancel")SupportQueueMigrationPlan cancel(@PathVariable@Pattern(regexp=CODE)String code,@PathVariable@Pattern(regexp="^SQMP-[A-Za-z0-9_-]{8,64}$")String planId,@RequestHeader("Idempotency-Key")@Pattern(regexp="^[0-9a-fA-F-]{36}$")String key,@Valid@RequestBody MigrationCommandRequest r){return command(key,"MIGRATION_CANCEL",code,planId,r,()->migrations.cancel(code,planId,r.expectedPlanVersion(),r.reason()));}
    private SupportQueueMigrationPlan command(String key,String operation,String code,String planId,MigrationCommandRequest request,java.util.function.Supplier<SupportQueueMigrationPlan>action){return idempotency.execute(key,operation,"support-queue-migration",code+":"+planId,request,200,SupportQueueMigrationPlan.class,action);}
    public record ScopeRequest(@NotNull SupportQueueScopeType scopeType,@NotBlank@Size(max=128)String scopeId){SupportQueueScope domain(){return new SupportQueueScope(scopeType,scopeId.trim());}}
    public record MemberRequest(@NotBlank@Size(max=128)String iamUserId,@NotNull SupportQueueMemberRole role,@NotNull Instant effectiveFrom,Instant effectiveUntil){SupportQueueMember domain(){return new SupportQueueMember(iamUserId.trim(),role,effectiveFrom,effectiveUntil);}}
    public record CreateRequest(@NotBlank@Pattern(regexp=CODE)String code,@NotBlank@Size(min=2,max=200)String name,@NotBlank@Size(max=128)String owningOrganizationId,@NotEmpty@Size(max=100)Set<@NotBlank@Size(max=64)String>serviceCatalogItemIds,@NotEmpty@Size(max=200)List<@Valid ScopeRequest>scopes,@NotEmpty@Size(max=500)List<@Valid MemberRequest>members,boolean sharedClaimEnabled,@Min(1)@Max(100000)Integer capacityLimit,@NotNull Instant effectiveFrom,Instant effectiveUntil,@NotBlank@Size(min=4,max=500)String reason){SupportQueueService.Input input(){return new SupportQueueService.Input(code,name,owningOrganizationId,serviceCatalogItemIds,scopes.stream().map(ScopeRequest::domain).collect(java.util.stream.Collectors.toSet()),members.stream().map(MemberRequest::domain).toList(),sharedClaimEnabled,capacityLimit,effectiveFrom,effectiveUntil,reason,0);}}
    public record UpdateRequest(@NotBlank@Size(min=2,max=200)String name,@NotBlank@Size(max=128)String owningOrganizationId,@NotEmpty@Size(max=100)Set<@NotBlank@Size(max=64)String>serviceCatalogItemIds,@NotEmpty@Size(max=200)List<@Valid ScopeRequest>scopes,@NotEmpty@Size(max=500)List<@Valid MemberRequest>members,boolean sharedClaimEnabled,@Min(1)@Max(100000)Integer capacityLimit,@NotNull Instant effectiveFrom,Instant effectiveUntil,@NotBlank@Size(min=4,max=500)String reason,@Min(0)long expectedVersion){SupportQueueService.Input input(String code){return new SupportQueueService.Input(code,name,owningOrganizationId,serviceCatalogItemIds,scopes.stream().map(ScopeRequest::domain).collect(java.util.stream.Collectors.toSet()),members.stream().map(MemberRequest::domain).toList(),sharedClaimEnabled,capacityLimit,effectiveFrom,effectiveUntil,reason,expectedVersion);}}
    public record StateRequest(@Min(0)long expectedVersion,@NotBlank@Size(min=4,max=500)String reason,Instant effectiveAt,@Pattern(regexp=CODE)String replacementQueueCode){}
    public record MigrationCreateRequest(@Min(0)long sourceQueueExpectedVersion,@NotBlank@Pattern(regexp=CODE)String targetQueueCode,@Min(0)long targetQueueExpectedVersion,@NotBlank@Size(min=4,max=500)String reason,Instant effectiveAt){}
    public record MigrationCommandRequest(@Min(0)long expectedPlanVersion,@NotBlank@Size(min=4,max=500)String reason){}
    public record ReconciliationRequest(@Min(0)long commandVersion,@NotBlank@Pattern(regexp="^(LEGACY_RESULT_ONLY|FAILED_FINAL)$")String decision,@Size(max=64)String resultResourceType,@Size(max=128)String resultResourceId,@NotBlank@Size(min=4,max=500)String reason){}
    public record ReconciliationApproveRequest(@Min(0)long expectedVersion,@NotBlank@Size(min=4,max=500)String reason){}
    public record Response(String code,String name,String owningOrganizationId,Set<String>serviceCatalogItemIds,Set<SupportQueueScope>scopes,List<SupportQueueMember>members,boolean sharedClaimEnabled,Integer capacityLimit,Instant effectiveFrom,Instant effectiveUntil,SupportQueueStatus status,long version){static Response from(SupportQueue q){return new Response(q.code(),q.name(),q.owningOrganizationId(),q.serviceCatalogItemIds(),q.scopes(),q.members(),q.sharedClaimEnabled(),q.capacityLimit(),q.effectiveFrom(),q.effectiveUntil(),q.status(),q.version());}}
    public record Page(List<Response>items,int page,int pageSize,long total){static Page from(SupportQueueService.QueuePage p){return new Page(p.items().stream().map(Response::from).toList(),p.page(),p.pageSize(),p.total());}}
}
