package cn.servicehub.workflow.team;

import cn.servicehub.security.CurrentUserProvider;import cn.servicehub.workflow.application.WorkflowConflictException;import com.fasterxml.jackson.databind.JsonNode;import com.fasterxml.jackson.databind.ObjectMapper;import java.nio.charset.StandardCharsets;import java.time.Instant;import java.time.temporal.ChronoUnit;import java.util.ArrayList;import java.util.Base64;import java.util.Iterator;import java.util.List;import java.util.Map;import java.util.TreeMap;import java.util.UUID;import java.util.function.Supplier;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;import org.springframework.stereotype.Service;
@Service public class SupportQueueCommandIdempotencyService{
 private final SupportQueueCommandRepository repository;private final CurrentUserProvider users;private final ObjectMapper json;private final SupportQueueRepository queues;private final SupportQueueMigrationRepository migrations;private final SupportQueueIdempotencyProperties properties;
 public SupportQueueCommandIdempotencyService(SupportQueueCommandRepository repository,CurrentUserProvider users,ObjectMapper json,SupportQueueRepository queues,SupportQueueMigrationRepository migrations,SupportQueueIdempotencyProperties properties){this.repository=repository;this.users=users;this.json=json;this.queues=queues;this.migrations=migrations;this.properties=properties;}
 public <T>T execute(String key,String operation,String type,String resource,Object request,int responseStatus,Class<T>responseType,Supplier<T>action){String actor=users.requireCurrentUser().iamUserId();SupportQueueCommandRecord existing=repository.find(actor,key).orElse(null);if(existing!=null&&"LEGACY_UNVERIFIABLE".equals(existing.keyVersion()))throw new WorkflowConflictException();String version=existing==null?properties.currentKeyVersion():existing.keyVersion(),fingerprint=fingerprint(request,version);String owner=UUID.randomUUID().toString();Instant now=Instant.now(),lease=now.plus(properties.leaseDuration());long recordVersion=0;if(existing!=null){if(!binding(existing,operation,type,resource,fingerprint))throw new WorkflowConflictException();if("SUCCEEDED".equals(existing.status()))return replay(existing,operation,type,resource,fingerprint,responseType);if(!"IN_PROGRESS".equals(existing.status())||existing.leaseExpiresAt()==null||existing.leaseExpiresAt().isAfter(now))throw new WorkflowConflictException();if(existing.resultResourceId()!=null){T reconciled=reconcile(existing,responseType);if(reconciled==null||!repository.completeByReconciliation(actor,key,existing.version(),existing.leaseOwner(),responseStatus,summary(reconciled),existing.resultResourceType(),existing.resultResourceId()))throw new WorkflowConflictException();return reconciled;}if(!repository.reconciliationRequired(actor,key,existing.version(),existing.leaseOwner(),"RESULT_NOT_PROVABLE"))throw new WorkflowConflictException();throw new WorkflowConflictException();}else{SupportQueueCommandRecord reserved=new SupportQueueCommandRecord(actor,key,operation,type,resource,fingerprint,"IN_PROGRESS",null,null,null,now,null,now.plus(24,ChronoUnit.HOURS),0,owner,lease,1,version,null,null,now);if(!repository.reserve(reserved))throw new WorkflowConflictException();}try{T result=action.get();String[]ref=resultRef(result);repository.complete(actor,key,recordVersion,owner,responseStatus,summary(result),ref[0],ref[1]);return result;}catch(RuntimeException e){repository.fail(actor,key,recordVersion,false,e instanceof WorkflowConflictException?"CONFLICT":"COMMAND_FAILED");throw e;}catch(Exception e){repository.fail(actor,key,recordVersion,false,"SERIALIZATION_FAILED");throw new IllegalStateException(e);}}
 private boolean binding(SupportQueueCommandRecord r,String op,String type,String resource,String fp){return r.operation().equals(op)&&r.resourceType().equals(type)&&r.resourceCode().equals(resource)&&r.requestFingerprint().equals(fp);}
 @SuppressWarnings("unchecked") private <T>T reconcile(SupportQueueCommandRecord r,Class<T>type){if(r.resultResourceId()==null)return null;if(type==SupportQueueAdminController.Response.class||type==SupportQueueService.DeactivationResult.class){SupportQueue q=queues.findByCode(r.resultResourceId()).orElse(null);if(q==null)return null;return type==SupportQueueAdminController.Response.class?(T)SupportQueueAdminController.Response.from(q):(T)new SupportQueueService.DeactivationResult(q,0,0,"RECONCILED");}if(type==SupportQueueMigrationPlan.class)return(T)migrations.findPlan(r.resultResourceId()).orElse(null);return null;}
 @SuppressWarnings("unchecked") private <T>T replay(SupportQueueCommandRecord r,String op,String type,String resource,String fingerprint,Class<T>responseType){if(!r.operation().equals(op)||!r.resourceType().equals(type)||!r.resourceCode().equals(resource)||!r.requestFingerprint().equals(fingerprint))throw new WorkflowConflictException();if("IN_PROGRESS".equals(r.status()))throw new WorkflowConflictException();if(!"SUCCEEDED".equals(r.status())||r.responseSummary()==null)throw new WorkflowConflictException();try{JsonNode s=json.readTree(r.responseSummary());if(responseType==SupportQueueAdminController.Response.class){SupportQueue q=queues.findByCode(s.required("resourceCode").asText()).orElseThrow(WorkflowConflictException::new);return(T)SupportQueueAdminController.Response.from(q);}if(responseType==SupportQueueService.DeactivationResult.class){SupportQueue q=queues.findByCode(s.required("resourceCode").asText()).orElseThrow(WorkflowConflictException::new);return(T)new SupportQueueService.DeactivationResult(q,s.path("migratedUnclaimedCount").asLong(),s.path("retainedInProgressCount").asLong(),s.path("auditEventId").asText());}if(responseType==SupportQueueMigrationPlan.class){return(T)migrations.findPlan(s.required("planId").asText()).orElseThrow(WorkflowConflictException::new);}throw new WorkflowConflictException();}catch(WorkflowConflictException e){throw e;}catch(Exception e){throw new IllegalStateException("Stored queue response summary is unreadable",e);}}
 private String summary(Object result){var out=json.createObjectNode();if(result instanceof SupportQueueAdminController.Response r){out.put("resourceCode",r.code());out.put("resourceVersion",r.version());out.put("status",r.status().name());}else if(result instanceof SupportQueueService.DeactivationResult r){out.put("resourceCode",r.queue().code());out.put("resourceVersion",r.queue().version());out.put("status",r.queue().status().name());out.put("migratedUnclaimedCount",r.migratedUnclaimedCount());out.put("retainedInProgressCount",r.retainedInProgressCount());out.put("auditEventId",r.auditEventId());}else if(result instanceof SupportQueueMigrationPlan p){out.put("planId",p.id());out.put("planVersion",p.planVersion());out.put("status",p.status().name());}else throw new IllegalArgumentException("Unsupported queue command response");return out.toString();}
 private String fingerprint(Object value,String version){try{byte[]key=properties.keys().get(version);if(key==null)throw new IllegalArgumentException("Unknown idempotency key version");Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(key,"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(mac.doFinal(canonical(json.valueToTree(value)).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalArgumentException("Queue command cannot be fingerprinted",e);}}
 private String[]resultRef(Object result){if(result instanceof SupportQueueAdminController.Response r)return new String[]{"support-queue",r.code()};if(result instanceof SupportQueueService.DeactivationResult r)return new String[]{"support-queue",r.queue().code()};if(result instanceof SupportQueueMigrationPlan p)return new String[]{"support-queue-migration",p.id()};throw new IllegalArgumentException("Unsupported result");}
 private String canonical(JsonNode n){if(n==null||n.isNull())return"null";if(n.isObject()){Map<String,String>m=new TreeMap<>();Iterator<String>it=n.fieldNames();while(it.hasNext()){String k=it.next();m.put(k,canonical(n.get(k)));}return m.entrySet().stream().map(e->jsonString(e.getKey())+":"+e.getValue()).collect(java.util.stream.Collectors.joining(",","{","}"));}if(n.isArray()){List<String>v=new ArrayList<>();n.forEach(x->v.add(canonical(x)));v.sort(String::compareTo);return String.join(",",v).transform(s->"["+s+"]");}return n.toString();}
 private String jsonString(String v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}}
 public CommandStatus status(String key){String actor=users.requireCurrentUser().iamUserId();SupportQueueCommandRecord r=repository.find(actor,key).orElseThrow(()->new cn.servicehub.ticket.application.TicketNotFoundException(key));return new CommandStatus(r.operation(),r.resourceType(),r.resourceCode(),r.status(),r.attemptCount(),r.leaseExpiresAt(),r.resultResourceType(),r.resultResourceId(),r.errorCode());}
 public record CommandStatus(String operation,String resourceType,String resourceCode,String status,int attemptCount,Instant leaseExpiresAt,String resultResourceType,String resultResourceId,String errorCode){}
}
