package cn.servicehub.workflow.team;

import cn.servicehub.audit.AuditEvent;import cn.servicehub.audit.AuditEventPublisher;import cn.servicehub.security.CurrentUser;import cn.servicehub.ticket.application.TicketObjectContextResolver;import cn.servicehub.ticket.domain.TicketRepository;import cn.servicehub.workflow.application.WorkflowConflictException;import cn.servicehub.workflow.domain.TicketWorkflowRepository;import cn.servicehub.workflow.domain.WorkflowTask;import cn.servicehub.workflow.domain.WorkflowTaskStatus;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Instant;import java.util.ArrayList;import java.util.Base64;import java.util.List;import java.util.Map;import java.util.Set;import java.util.UUID;import java.util.stream.Collectors;import org.slf4j.MDC;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class SupportQueueMigrationService{
 private final SupportQueueMigrationRepository plans;private final SupportQueueService queues;private final SupportQueueRepository queueRepository;private final TicketWorkflowRepository workflows;private final TicketRepository tickets;private final TicketObjectContextResolver contexts;private final SupportQueueEligibilityService eligibility;private final AuditEventPublisher audit;
 public SupportQueueMigrationService(SupportQueueMigrationRepository plans,SupportQueueService queues,SupportQueueRepository queueRepository,TicketWorkflowRepository workflows,TicketRepository tickets,TicketObjectContextResolver contexts,SupportQueueEligibilityService eligibility,AuditEventPublisher audit){this.plans=plans;this.queues=queues;this.queueRepository=queueRepository;this.workflows=workflows;this.tickets=tickets;this.contexts=contexts;this.eligibility=eligibility;this.audit=audit;}
 @Transactional public SupportQueueMigrationPlan preflight(String source,long sourceVersion,String targetCode,long targetVersion,String reason){CurrentUser actor=queues.migrationActor();SupportQueue sourceQueue=queues.migrationQueue(actor,source),target=queues.migrationQueue(actor,targetCode);if(source.equals(targetCode)||sourceQueue.version()!=sourceVersion||target.version()!=targetVersion||sourceQueue.status()!=SupportQueueStatus.ACTIVE||target.status()!=SupportQueueStatus.ACTIVE)throw new WorkflowConflictException();if(plans.findActiveBySource(source).isPresent())throw new WorkflowConflictException();boolean superset=target.serviceCatalogItemIds().containsAll(sourceQueue.serviceCatalogItemIds())&&target.scopes().containsAll(sourceQueue.scopes());List<SupportQueueMigrationPlanItem>items=new ArrayList<>();long blocked=0,open=0,claimed=0;for(WorkflowTask task:workflows.findActiveTasksByQueue(source)){var ticket=tickets.findById(task.ticketId()).orElse(null);var workflow=workflows.findInstance(task.ticketId()).orElse(null);boolean invalid=ticket==null||workflow==null||!superset;SupportQueueMigrationItemType type=task.status()==WorkflowTaskStatus.OPEN&&task.assigneeIamUserId()==null?SupportQueueMigrationItemType.UNCLAIMED_TASK_MIGRATION:SupportQueueMigrationItemType.IN_PROGRESS_HANDOVER;if(type==SupportQueueMigrationItemType.UNCLAIMED_TASK_MIGRATION)open++;else claimed++;if(invalid)blocked++;items.add(new SupportQueueMigrationPlanItem("SQMPI-"+compact(),type,invalid?SupportQueueMigrationItemStatus.BLOCKED:SupportQueueMigrationItemStatus.PENDING,task.ticketId(),task.id(),ticket==null?0:ticket.version(),workflow==null?0:workflow.version(),task.version(),task.status().name(),task.assigneeIamUserId(),source,targetCode,0,false,null,invalid?"PREFLIGHT_BLOCKED":null,null,null,null,0));}
  Instant now=Instant.now();String checklist=hash(items.stream().map(i->i.itemId()+":"+i.sourceWorkflowTaskId()+":"+i.sourceTaskVersion()+":"+i.sourceTaskStatus()).sorted().collect(Collectors.joining("\n")));SupportQueueMigrationPlan.ScopeSummary summary=summary(sourceQueue);SupportQueueMigrationPlanStatus status=blocked>0?SupportQueueMigrationPlanStatus.PREFLIGHT_FAILED:SupportQueueMigrationPlanStatus.PENDING_APPROVAL;String id="SQMP-"+compact(),auditId=record(actor,"SUPPORT_QUEUE_MIGRATION_PREFLIGHTED",id,Map.of("source",source,"target",targetCode,"items",String.valueOf(items.size())));SupportQueueMigrationPlan plan=new SupportQueueMigrationPlan(id,source,sourceVersion,targetCode,targetVersion,summary,status,0,now,checklist,open,claimed,blocked,0,0,0,actor.iamUserId(),null,reason,now,null,null,null,auditId);plans.create(plan,items);return plan; }
 public PlanView get(String source,String id,int page,int size){CurrentUser actor=queues.migrationActor();queues.migrationQueue(actor,source);SupportQueueMigrationPlan p=required(source,id);List<SupportQueueMigrationPlanItem>all=plans.findItems(id);int from=Math.min((page-1)*size,all.size()),to=Math.min(from+size,all.size());return new PlanView(p,all.subList(from,to),page,size,all.size());}
 @Transactional public SupportQueueMigrationPlan approve(String source,String id,long expected,String reason){CurrentUser actor=queues.migrationActor();SupportQueueMigrationPlan p=required(source,id);if(p.planVersion()!=expected||p.status()!=SupportQueueMigrationPlanStatus.PENDING_APPROVAL||actor.iamUserId().equals(p.createdByIamUserId()))throw new AccessDeniedException("Migration approval is not authorized");validateFrozenQueues(actor,p);Instant now=Instant.now();SupportQueueMigrationPlan changed=copy(p,SupportQueueMigrationPlanStatus.APPROVED,p.planVersion()+1,actor.iamUserId(),now,p.executionStartedAt(),p.completedAt(),p.succeededItemCount(),p.retryableFailedItemCount(),p.failedItemCount(),record(actor,"SUPPORT_QUEUE_MIGRATION_APPROVED",id,Map.of()));if(!plans.updatePlan(changed,p.planVersion(),p.status()))throw new WorkflowConflictException();return changed;}
 @Transactional public SupportQueueMigrationPlan cancel(String source,String id,long expected,String reason){CurrentUser actor=queues.migrationActor();SupportQueueMigrationPlan p=required(source,id);if(p.planVersion()!=expected||!Set.of(SupportQueueMigrationPlanStatus.PREFLIGHT_FAILED,SupportQueueMigrationPlanStatus.PENDING_APPROVAL,SupportQueueMigrationPlanStatus.APPROVED).contains(p.status()))throw new WorkflowConflictException();SupportQueueMigrationPlan changed=copy(p,SupportQueueMigrationPlanStatus.CANCELLED,p.planVersion()+1,p.approvedByIamUserId(),p.approvedAt(),p.executionStartedAt(),Instant.now(),p.succeededItemCount(),p.retryableFailedItemCount(),p.failedItemCount(),record(actor,"SUPPORT_QUEUE_MIGRATION_CANCELLED",id,Map.of()));if(!plans.updatePlan(changed,p.planVersion(),p.status()))throw new WorkflowConflictException();return changed;}
 @Transactional public SupportQueueMigrationPlan execute(String source,String id,long expected,String reason,boolean retry){
  CurrentUser actor=queues.migrationActor();SupportQueueMigrationPlan p=required(source,id);Set<SupportQueueMigrationPlanStatus>allowed=retry?Set.of(SupportQueueMigrationPlanStatus.PARTIALLY_COMPLETED,SupportQueueMigrationPlanStatus.FAILED):Set.of(SupportQueueMigrationPlanStatus.APPROVED);if(p.planVersion()!=expected||!allowed.contains(p.status()))throw new WorkflowConflictException();
  try{validateFrozenQueues(actor,p);}catch(RuntimeException blocked){return failBeforeExecution(p,actor,"PLAN_SNAPSHOT_INVALID");}
  Instant now=Instant.now();SupportQueueMigrationPlan executing=copy(p,SupportQueueMigrationPlanStatus.EXECUTING,p.planVersion()+1,p.approvedByIamUserId(),p.approvedAt(),now,null,p.succeededItemCount(),p.retryableFailedItemCount(),p.failedItemCount(),p.auditEventId());if(!plans.updatePlan(executing,p.planVersion(),p.status()))throw new WorkflowConflictException();
  try{
   for(SupportQueueMigrationPlanItem item:plans.findItems(id)){
    if(!(item.status()==SupportQueueMigrationItemStatus.PENDING||(retry&&item.status()==SupportQueueMigrationItemStatus.RETRYABLE_FAILED)))continue;
    try{CurrentUser current=queues.migrationActor();if(!current.iamUserId().equals(actor.iamUserId()))throw new AccessDeniedException("Executor changed");validateFrozenQueues(current,p);processItem(id,item,current,now);record(current,"SUPPORT_QUEUE_MIGRATION_ITEM_PROCESSED",item.itemId(),Map.of("ticketId",item.ticketId(),"itemType",item.itemType().name()));}
    catch(RuntimeException itemFailure){markItemFailure(id,item,actor,"ITEM_EXECUTION_FAILED");}
   }
   List<SupportQueueMigrationPlanItem>after=plans.findItems(id);long succeeded=after.stream().filter(i->i.status()==SupportQueueMigrationItemStatus.SUCCEEDED).count(),retryable=after.stream().filter(i->i.status()==SupportQueueMigrationItemStatus.RETRYABLE_FAILED).count(),failed=after.stream().filter(i->Set.of(SupportQueueMigrationItemStatus.FAILED,SupportQueueMigrationItemStatus.STALE,SupportQueueMigrationItemStatus.BLOCKED).contains(i.status())).count();boolean complete=!after.isEmpty()&&succeeded==after.size();SupportQueueMigrationPlanStatus finalStatus=complete?SupportQueueMigrationPlanStatus.COMPLETED:retryable>0?SupportQueueMigrationPlanStatus.PARTIALLY_COMPLETED:SupportQueueMigrationPlanStatus.FAILED;String auditId=record(actor,complete?"SUPPORT_QUEUE_MIGRATION_COMPLETED":"SUPPORT_QUEUE_MIGRATION_FAILED",id,Map.of("succeeded",String.valueOf(succeeded),"failed",String.valueOf(failed)));SupportQueueMigrationPlan finished=copy(executing,finalStatus,executing.planVersion()+1,executing.approvedByIamUserId(),executing.approvedAt(),executing.executionStartedAt(),now,succeeded,retryable,failed,auditId);if(complete)queues.completeMigration(actor,source,p.sourceQueueVersion(),reason);if(!plans.updatePlan(finished,executing.planVersion(),SupportQueueMigrationPlanStatus.EXECUTING))throw new WorkflowConflictException();return finished;
  }catch(RuntimeException systemFailure){SupportQueueMigrationPlan failed=copy(executing,SupportQueueMigrationPlanStatus.FAILED,executing.planVersion()+1,executing.approvedByIamUserId(),executing.approvedAt(),executing.executionStartedAt(),Instant.now(),executing.succeededItemCount(),executing.retryableFailedItemCount(),executing.failedItemCount()+1,record(actor,"SUPPORT_QUEUE_MIGRATION_SYSTEM_FAILED",id,Map.of("errorCode","SYSTEM_FAILURE")));plans.updatePlan(failed,executing.planVersion(),SupportQueueMigrationPlanStatus.EXECUTING);return failed;}
 }
 private void processItem(String planId,SupportQueueMigrationPlanItem i,CurrentUser actor,Instant now){SupportQueueMigrationPlanItem result;if(i.itemType()==SupportQueueMigrationItemType.UNCLAIMED_TASK_MIGRATION){var currentTicket=tickets.findById(i.ticketId()).orElse(null);var currentWorkflow=workflows.findInstance(i.ticketId()).orElse(null);boolean moved=currentTicket!=null&&currentWorkflow!=null&&currentTicket.version()==i.sourceTicketVersion()&&currentWorkflow.version()==i.sourceWorkflowVersion()&&workflows.migrateOpenTask(i.sourceWorkflowTaskId(),i.sourceTaskVersion(),i.sourceQueueCode(),i.targetQueueCode(),i.ticketId(),i.sourceTicketVersion(),i.sourceWorkflowVersion(),now);if(moved){String resultId="SQM-"+compact();SupportQueue target=queueRepository.findByCode(i.targetQueueCode()).orElseThrow();var context=contexts.resolveForScope(i.ticketId());queueRepository.saveRoutingSnapshot(new WorkflowQueueRoutingSnapshot(UUID.randomUUID().toString(),i.ticketId(),i.sourceWorkflowTaskId(),"queue_migration",target.code(),new WorkflowQueueRoutingSnapshot.NodeAssignmentEvidence("QUEUE_MIGRATION",0),target.version(),eligibility.scopeDigest(target),Set.of(),eligibility.contextDigest(context),now));result=item(i,SupportQueueMigrationItemStatus.SUCCEEDED,false,"MIGRATED",null,resultId,null,null);}else result=item(i,SupportQueueMigrationItemStatus.STALE,false,null,"TASK_SNAPSHOT_CHANGED",null,null,null);}else{WorkflowTask current=workflows.findActiveTasksByQueue(i.sourceQueueCode()).stream().filter(t->t.id().equals(i.sourceWorkflowTaskId())).findFirst().orElse(null);if(current!=null&&current.version()==i.sourceTaskVersion()&&current.status()==WorkflowTaskStatus.CLAIMED){String checklist="主办="+safe(current.assigneeIamUserId())+";目标队列="+i.targetQueueCode()+";SLA连续;等待真实交接流程";result=item(i,SupportQueueMigrationItemStatus.BLOCKED,false,null,"HANDOVER_WORKFLOW_UNAVAILABLE",null,null,checklist);}else result=item(i,SupportQueueMigrationItemStatus.STALE,false,null,"IN_PROGRESS_SNAPSHOT_CHANGED",null,null,null);}if(!plans.updateItem(planId,result,i.version(),i.status()))throw new WorkflowConflictException();}
 private SupportQueueMigrationPlanItem item(SupportQueueMigrationPlanItem i,SupportQueueMigrationItemStatus s,boolean retry,String result,String error,String resource,String handover,String checklist){return new SupportQueueMigrationPlanItem(i.itemId(),i.itemType(),s,i.ticketId(),i.sourceWorkflowTaskId(),i.sourceTicketVersion(),i.sourceWorkflowVersion(),i.sourceTaskVersion(),i.sourceTaskStatus(),i.sourceAssigneeIamUserId(),i.sourceQueueCode(),i.targetQueueCode(),i.attemptCount()+1,retry,result,error,resource,handover,checklist,i.version()+1);}
 private void markItemFailure(String planId,SupportQueueMigrationPlanItem i,CurrentUser actor,String code){SupportQueueMigrationPlanItem failed=item(i,SupportQueueMigrationItemStatus.RETRYABLE_FAILED,true,null,code,null,null,null);plans.updateItem(planId,failed,i.version(),i.status());record(actor,"SUPPORT_QUEUE_MIGRATION_ITEM_FAILED",i.itemId(),Map.of("ticketId",i.ticketId(),"errorCode",code));}
 private SupportQueueMigrationPlan failBeforeExecution(SupportQueueMigrationPlan p,CurrentUser actor,String code){SupportQueueMigrationPlan failed=copy(p,SupportQueueMigrationPlanStatus.FAILED,p.planVersion()+1,p.approvedByIamUserId(),p.approvedAt(),p.executionStartedAt(),Instant.now(),p.succeededItemCount(),p.retryableFailedItemCount(),p.failedItemCount()+1,record(actor,"SUPPORT_QUEUE_MIGRATION_BLOCKED",p.id(),Map.of("errorCode",code)));if(!plans.updatePlan(failed,p.planVersion(),p.status()))throw new WorkflowConflictException();return failed;}
 private void validateFrozenQueues(CurrentUser actor,SupportQueueMigrationPlan p){SupportQueue source=queues.migrationQueue(actor,p.sourceQueueCode()),target=queues.migrationQueue(actor,p.targetQueueCode());SupportQueueMigrationPlan.ScopeSummary current=summary(source);if(source.version()!=p.sourceQueueVersion()||target.version()!=p.targetQueueVersion()||source.status()!=SupportQueueStatus.ACTIVE||target.status()!=SupportQueueStatus.ACTIVE||!current.scopeHash().equals(p.scopeSummary().scopeHash())||!target.scopes().containsAll(source.scopes())||!target.serviceCatalogItemIds().containsAll(source.serviceCatalogItemIds()))throw new WorkflowConflictException();}
 private SupportQueueMigrationPlan required(String source,String id){SupportQueueMigrationPlan p=plans.findPlan(id).orElseThrow(()->new cn.servicehub.ticket.application.TicketNotFoundException(id));if(!p.sourceQueueCode().equals(source))throw new cn.servicehub.ticket.application.TicketNotFoundException(id);return p;}
 private SupportQueueMigrationPlan.ScopeSummary summary(SupportQueue q){Set<String>systems=q.scopes().stream().filter(s->s.scopeType()==SupportQueueScopeType.SERVICE_SYSTEM).map(SupportQueueScope::scopeId).collect(Collectors.toSet());int ci=(int)q.scopes().stream().filter(s->s.scopeType()==SupportQueueScopeType.CONFIGURATION_ITEM).count();return new SupportQueueMigrationPlan.ScopeSummary(q.owningOrganizationId(),q.serviceCatalogItemIds(),systems,ci,hash(q.scopes().stream().map(s->s.scopeType()+":"+s.scopeId()).sorted().collect(Collectors.joining("\n"))));}
 private SupportQueueMigrationPlan copy(SupportQueueMigrationPlan p,SupportQueueMigrationPlanStatus status,long version,String approver,Instant approved,Instant started,Instant completed,long success,long retry,long failed,String auditId){return new SupportQueueMigrationPlan(p.id(),p.sourceQueueCode(),p.sourceQueueVersion(),p.targetQueueCode(),p.targetQueueVersion(),p.scopeSummary(),status,version,p.listSnapshotAt(),p.checklistHash(),p.unclaimedItemCount(),p.inProgressHandoverCount(),p.blockedItemCount(),success,retry,failed,p.createdByIamUserId(),approver,p.reason(),p.createdAt(),approved,started,completed,auditId);}
 private String record(CurrentUser actor,String action,String id,Map<String,String>attributes){String request=MDC.get("requestId")==null?"system":MDC.get("requestId");audit.publish(new AuditEvent(Instant.now(),request,actor.iamUserId(),action,"support-queue-migration",id,attributes));return request;}private String hash(String v){try{return Base64.getUrlEncoder().withoutPadding().encodeToString(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private String compact(){return UUID.randomUUID().toString().replace("-","");}private String safe(String s){return s==null?"UNASSIGNED":s;}
 public record PlanView(SupportQueueMigrationPlan plan,List<SupportQueueMigrationPlanItem>items,int page,int pageSize,long total){}
}
