package cn.servicehub.workflow.team;

import cn.servicehub.audit.AuditEvent;
import cn.servicehub.audit.AuditEventPublisher;
import cn.servicehub.security.CurrentUser;
import cn.servicehub.security.CurrentUserProvider;
import cn.servicehub.security.TicketAccessScopeResolver;
import cn.servicehub.ticket.application.TicketNotFoundException;
import cn.servicehub.workflow.application.WorkflowConflictException;
import cn.servicehub.workflow.domain.TicketWorkflowRepository;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.slf4j.MDC;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class SupportQueueService {
    private static final Set<String> READ=Set.of("ROLE_SERVICE_MANAGER","ROLE_PLATFORM_ADMIN","ROLE_AUDITOR"),WRITE=Set.of("ROLE_SERVICE_MANAGER","ROLE_PLATFORM_ADMIN"),SUPPORT=Set.of("ROLE_FIRST_LINE_SUPPORT","ROLE_SECOND_LINE_SUPPORT","ROLE_SERVICE_MANAGER");
    private final SupportQueueRepository repository;private final CurrentUserProvider users;private final TicketAccessScopeResolver scopes;private final cn.servicehub.security.PlatformAuthorizationResolver authorizations;private final TicketWorkflowRepository workflows;private final AuditEventPublisher audit;private final Clock clock=Clock.systemUTC();
    public SupportQueueService(SupportQueueRepository repository,CurrentUserProvider users,TicketAccessScopeResolver scopes,cn.servicehub.security.PlatformAuthorizationResolver authorizations,TicketWorkflowRepository workflows,AuditEventPublisher audit){this.repository=repository;this.users=users;this.scopes=scopes;this.authorizations=authorizations;this.workflows=workflows;this.audit=audit;}
    public QueuePage list(int page,int size,SupportQueueStatus status){CurrentUser a=actor(READ);List<SupportQueue> all=repository.findAll().stream().filter(q->status==null||q.status()==status).filter(q->canRead(a,q)).toList();int from=Math.min((page-1)*size,all.size()),to=Math.min(from+size,all.size());return new QueuePage(all.subList(from,to),page,size,all.size());}
    public SupportQueue get(String code){CurrentUser a=actor(READ);SupportQueue q=required(code);if(!canRead(a,q))throw new TicketNotFoundException(code);return q;}
    @Transactional public SupportQueue create(Input in){CurrentUser a=actor(WRITE);validate(in,true);if(repository.findByCode(in.code()).isPresent())throw new WorkflowConflictException();SupportQueue q=value(in,SupportQueueStatus.DRAFT,0);if(!canManageNew(a,q))throw new AccessDeniedException("Support queue management scope is not authorized");SupportQueue saved=repository.save(q,0,a.iamUserId());record(a,"SUPPORT_QUEUE_CREATED",saved.code(),in.reason());return saved;}
    @Transactional public SupportQueue update(String code,Input in){CurrentUser a=actor(WRITE);SupportQueue old=managed(a,code);if(!code.equals(in.code())||in.expectedVersion()!=old.version())throw new WorkflowConflictException();validate(in,false);SupportQueue replacement=value(in,old.status(),old.version());if(old.status()==SupportQueueStatus.ACTIVE&&(!old.owningOrganizationId().equals(replacement.owningOrganizationId())||!old.serviceCatalogItemIds().equals(replacement.serviceCatalogItemIds())||!old.scopes().equals(replacement.scopes())||!old.members().equals(replacement.members())))throw new WorkflowConflictException();SupportQueue saved=repository.save(replacement,old.version(),a.iamUserId());record(a,"SUPPORT_QUEUE_UPDATED",code,in.reason());return saved;}
    @Transactional public SupportQueue activate(String code,long expected,String reason){CurrentUser a=actor(WRITE);SupportQueue old=managed(a,code);if(old.version()!=expected||old.status()!=SupportQueueStatus.DRAFT||!validReason(reason))throw new WorkflowConflictException();validateActivation(old);SupportQueue saved=repository.save(copyStatus(old,SupportQueueStatus.ACTIVE),old.version(),a.iamUserId());record(a,"SUPPORT_QUEUE_ACTIVATED",code,reason);return saved;}
    @Transactional public DeactivationResult deactivate(String code,long expected,String reason,String replacement){CurrentUser a=actor(WRITE);SupportQueue old=managed(a,code);if(old.version()!=expected||old.status()!=SupportQueueStatus.ACTIVE||!validReason(reason))throw new WorkflowConflictException();long open=workflows.countOpenTasksByQueue(code),claimed=workflows.countClaimedTasksByQueue(code);if(open>0||claimed>0)throw new WorkflowConflictException();SupportQueue saved=repository.save(copyStatus(old,SupportQueueStatus.INACTIVE),old.version(),a.iamUserId());String auditId=record(a,"SUPPORT_QUEUE_DEACTIVATED",code,reason);return new DeactivationResult(saved,0,0,auditId);}
    private void validateActivation(SupportQueue q){Instant now=clock.instant();if(q.scopes().stream().noneMatch(s->s.scopeType()==SupportQueueScopeType.ORGANIZATION)||q.serviceCatalogItemIds().isEmpty())throw new IllegalArgumentException("Queue scopes are incomplete");boolean member=false,supervisor=false;for(SupportQueueMember m:q.members())if(m.activeAt(now)){CurrentUser u=authorizations.resolve(m.iamUserId(),"QUEUE_ADMIN");if(u.authorities().stream().noneMatch(SUPPORT::contains))throw new IllegalArgumentException("Queue member lacks active support role");member|=m.role()==SupportQueueMemberRole.MEMBER;supervisor|=m.role()==SupportQueueMemberRole.SUPERVISOR;}if(!member||!supervisor)throw new IllegalArgumentException("Queue requires active member and supervisor");}
    private void validate(Input v,boolean create){if(v==null||!v.code().matches("^[A-Z][A-Z0-9_-]{1,63}$")||v.name()==null||v.name().trim().length()<2||v.name().trim().length()>200||!v.owningOrganizationId().matches("^[A-Za-z0-9._:-]{1,128}$")||v.serviceCatalogItemIds()==null||v.serviceCatalogItemIds().isEmpty()||v.scopes()==null||v.scopes().isEmpty()||v.members()==null||v.members().isEmpty()||v.effectiveFrom()==null||(v.effectiveUntil()!=null&&!v.effectiveUntil().isAfter(v.effectiveFrom()))||!validReason(v.reason())||(!create&&v.expectedVersion()<1))throw new IllegalArgumentException("Support queue input is invalid");}
    private SupportQueue value(Input v,SupportQueueStatus status,long version){java.util.Set<SupportQueueScope>all=new java.util.LinkedHashSet<>(v.scopes());v.serviceCatalogItemIds().forEach(id->all.add(new SupportQueueScope(SupportQueueScopeType.SERVICE_CATALOG,id)));return new SupportQueue(v.code(),v.name().trim(),v.owningOrganizationId(),v.serviceCatalogItemIds(),all,v.members(),v.sharedClaimEnabled(),v.capacityLimit(),v.effectiveFrom(),v.effectiveUntil(),status,version);}
    private SupportQueue copyStatus(SupportQueue q,SupportQueueStatus s){return new SupportQueue(q.code(),q.name(),q.owningOrganizationId(),q.serviceCatalogItemIds(),q.scopes(),q.members(),q.sharedClaimEnabled(),q.capacityLimit(),q.effectiveFrom(),q.effectiveUntil(),s,q.version());}
    private SupportQueue managed(CurrentUser a,String code){SupportQueue q=required(code);if(!canManage(a,q))throw new TicketNotFoundException(code);return q;}private SupportQueue required(String c){return repository.findByCode(c).orElseThrow(()->new TicketNotFoundException(c));}
    private boolean canRead(CurrentUser a,SupportQueue q){var s=scopes.resolve(a);return (s.legacyDirectBypass()||s.organizationIds().contains(q.owningOrganizationId()))&&(a.authorities().contains("ROLE_PLATFORM_ADMIN")||a.authorities().contains("ROLE_AUDITOR")||isSupervisor(a,q));}
    private boolean canManage(CurrentUser a,SupportQueue q){var s=scopes.resolve(a);return (s.legacyDirectBypass()||s.organizationIds().contains(q.owningOrganizationId()))&&(a.authorities().contains("ROLE_PLATFORM_ADMIN")||isSupervisor(a,q));}
    private boolean canManageNew(CurrentUser a,SupportQueue q){return canManage(a,q)||q.members().stream().anyMatch(m->m.iamUserId().equals(a.iamUserId())&&m.role()==SupportQueueMemberRole.SUPERVISOR);}
    private boolean isSupervisor(CurrentUser a,SupportQueue q){Instant now=clock.instant();return q.members().stream().anyMatch(m->m.iamUserId().equals(a.iamUserId())&&m.role()==SupportQueueMemberRole.SUPERVISOR&&m.activeAt(now));}
    private CurrentUser actor(Set<String> roles){CurrentUser a=users.requireCurrentUser();if(a.authorities().stream().noneMatch(roles::contains))throw new AccessDeniedException("Support queue management role is required");return a;}
    CurrentUser migrationActor(){return actor(WRITE);}SupportQueue migrationQueue(CurrentUser actor,String code){return managed(actor,code);}
    @Transactional SupportQueue completeMigration(CurrentUser actor,String code,long expectedVersion,String reason){SupportQueue q=managed(actor,code);if(q.version()!=expectedVersion||q.status()!=SupportQueueStatus.ACTIVE)throw new WorkflowConflictException();SupportQueue saved=repository.save(copyStatus(q,SupportQueueStatus.INACTIVE),q.version(),actor.iamUserId());record(actor,"SUPPORT_QUEUE_MIGRATION_COMPLETED",code,reason);return saved;}
    private boolean validReason(String r){return r!=null&&r.trim().length()>=4&&r.trim().length()<=500;}private String record(CurrentUser a,String action,String id,String reason){String request=MDC.get("requestId")==null?"system":MDC.get("requestId");audit.publish(new AuditEvent(clock.instant(),request,a.iamUserId(),action,"support-queue",id,Map.of("reason",reason.trim())));return request;}
    public record Input(String code,String name,String owningOrganizationId,Set<String> serviceCatalogItemIds,Set<SupportQueueScope> scopes,List<SupportQueueMember> members,boolean sharedClaimEnabled,Integer capacityLimit,Instant effectiveFrom,Instant effectiveUntil,String reason,long expectedVersion){}
    public record QueuePage(List<SupportQueue> items,int page,int pageSize,long total){}
    public record DeactivationResult(SupportQueue queue,long migratedUnclaimedCount,long retainedInProgressCount,String auditEventId){}
}
