<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { ApiError } from '@/api/client'
import { knowledgeApi, type KnowledgeArticle, type KnowledgeAttachmentScanState, type KnowledgeFeedbackSummary } from '@/api/knowledge'

const route = useRoute()
const article = ref<KnowledgeArticle>()
const source = ref<'api' | 'demo'>('api')
const loading = ref(true)
const error = ref('')
const feedback = ref<KnowledgeFeedbackSummary>()
const feedbackNotice = ref('')
const scanLabel: Record<KnowledgeAttachmentScanState, string> = { RECEIVED: '已接收', SCANNING: '扫描中', SCAN_PASSED: '扫描通过', QUARANTINED: '已隔离', REJECTED: '扫描拒绝', SCAN_UNAVAILABLE: '扫描不可用' }
const canReadAttachments = computed(() => article.value?.attachments.filter((item) => item.downloadable && item.scanState === 'SCAN_PASSED') ?? [])
function size(bytes: number): string { return bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB` }
async function load(): Promise<void> { loading.value = true; error.value = ''; feedback.value = undefined; try { const result = await knowledgeApi.get(String(route.params.articleId)); article.value = result.data; source.value = result.source; if (result.source === 'api') feedback.value = await knowledgeApi.feedbackSummary(article.value.id) } catch (cause) { error.value = cause instanceof ApiError ? cause.message : '无法打开该知识，可能已退役或不在当前授权范围。'; article.value = undefined } finally { loading.value = false } }
async function vote(value: 'HELPFUL' | 'NOT_HELPFUL'): Promise<void> { if (!article.value || source.value !== 'api') return; feedbackNotice.value = ''; try { feedback.value = await knowledgeApi.feedback(article.value.id, value); feedbackNotice.value = value === 'HELPFUL' ? '已记录“有帮助”评价。' : '已记录“需复审”评价；不会提交自由文本或知识正文。' } catch (cause) { feedbackNotice.value = cause instanceof ApiError ? cause.message : '评价未提交，请稍后重试。' } }
onMounted(load); watch(() => route.params.articleId, load)
</script>

<template>
  <div class="detail-nav"><RouterLink to="/knowledge">← 返回知识库</RouterLink></div><div v-if="loading" class="panel compact-loading">正在读取知识内容…</div><div v-else-if="error" class="panel empty-state"><span class="empty-icon">!</span><h3>无法打开知识</h3><p>{{ error }}</p></div><template v-else-if="article"><div class="page-heading detail-heading"><div><div class="eyebrow">{{ article.id }} · v{{ article.version }}</div><h2>{{ article.title }}</h2><div class="tag-row"><span v-for="tag in article.tags" :key="tag.code ?? tag.name" class="tag tag--muted">{{ tag.name }}</span><span v-if="article.sourceType" class="tag tag--blue">{{ article.sourceType === 'RESOLVED_CASE' ? '已解决案例沉淀' : article.sourceType === 'IMPORTED' ? '受控导入' : '人工维护' }}</span></div></div></div><p v-if="source === 'demo'" class="demo-notice">开发演示数据：不可用于判断生产环境的授权、审核或扫描结果。</p><div class="knowledge-detail-layout"><article class="panel knowledge-content"><div class="panel-header"><div><h3>处理指引</h3><p>内容已按服务端当前授权范围返回；请勿在处理记录中填写凭据或令牌。</p></div></div><p v-if="article.content">{{ article.content }}</p><p v-else class="scan-notice">该受控源文件不提供浏览器正文预览（例如 PDF）；平台不会伪造、解析或展示隔离文件内容。</p><div v-if="source === 'api'" class="knowledge-feedback"><b>本指引是否有帮助？</b><span v-if="feedback">{{ feedback.helpfulCount }} 人认为有帮助 · {{ feedback.notHelpfulCount }} 人建议复审</span><div><button class="button button--secondary button--compact" type="button" @click="vote('HELPFUL')">有帮助</button><button class="button button--secondary button--compact" type="button" @click="vote('NOT_HELPFUL')">需复审</button></div><small v-if="feedbackNotice">{{ feedbackNotice }}</small></div></article><aside class="knowledge-side"><section class="panel"><div class="panel-header"><div><h3>关联范围</h3></div></div><dl class="knowledge-definition"><div><dt>发布状态</dt><dd>已发布</dd></div><div><dt>归属组织</dt><dd>{{ article.owningOrganizationId }}</dd></div><div><dt>关联服务目录</dt><dd>{{ article.serviceCatalogItems?.map((item) => item.name).join('、') ?? article.serviceCatalogItemIds.join('、') }}</dd></div><div v-if="article.relatedCases?.length"><dt>关联案例</dt><dd>{{ article.relatedCases.map((item) => item.title).join('、') }}</dd></div><div><dt>发布时间</dt><dd>{{ article.publishedAt.slice(0, 16).replace('T', ' ') }}</dd></div></dl></section><section class="panel"><div class="panel-header"><div><h3>受控附件</h3><p>仅展示服务端返回的扫描通过附件。</p></div></div><ul class="knowledge-attachment-list"><li v-for="file in article.attachments" :key="file.id"><div><b>{{ file.displayFileName }}</b><small>{{ size(file.sizeBytes) }} · {{ file.detectedMediaType }}</small><span :class="`scan-state scan-state--${file.scanState.toLowerCase()}`">{{ scanLabel[file.scanState] }}</span></div><span class="attachment-blocked">下载入口待服务端开放</span></li></ul><p v-if="!canReadAttachments.length" class="scan-notice">当前没有可下载附件；知识正文不展示隔离或未通过扫描的文件。</p></section></aside></div></template>
</template>
