<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { ApiError } from '@/api/client'
import { knowledgeApi, type KnowledgeArticleSummary, type KnowledgeImportRecord, type KnowledgePublicationStatus, type KnowledgeReviewCandidate } from '@/api/knowledge'

const articles = ref<KnowledgeArticleSummary[]>([])
const imports = ref<KnowledgeImportRecord[]>([])
const reviewCandidates = ref<KnowledgeReviewCandidate[]>([])
const reviewNotice = ref('')
const mode = ref<'read' | 'admin'>('read')
const source = ref<'api' | 'demo'>('api')
const query = ref('')
const loading = ref(false)
const error = ref('')
const showImport = ref(false)
const importForm = ref({ title: '', categoryCode: '', serviceCatalogItemIds: '', tagNames: '', file: null as File | null })
const importError = ref('')
const importNotice = ref('')
const submitting = ref(false)
const selectedCategory = ref('')

const statusLabel: Record<KnowledgePublicationStatus, string> = { DRAFT: '草稿', PENDING_REVIEW: '待审核', PUBLISHED: '已发布', SUPERSEDED: '已替代', REJECTED: '已驳回', ARCHIVED: '已归档', MIGRATION_PENDING: '迁移待定' }
const blockedImports = computed(() => imports.value.filter((item) => item.status !== 'DRAFT_CREATED').length)
const categories = computed(() => [...new Set(articles.value.map((item) => item.category).filter((item): item is string => Boolean(item)))].sort())
const filteredArticles = computed(() => selectedCategory.value ? articles.value.filter((item) => item.category === selectedCategory.value) : articles.value)

async function loadArticles(): Promise<void> { loading.value = true; error.value = ''; try { const result = await knowledgeApi.list({ q: query.value.trim() || undefined }); articles.value = result.data.items; source.value = result.source } catch (cause) { error.value = cause instanceof ApiError ? cause.message : '知识库暂不可用，请稍后重试。' } finally { loading.value = false } }
async function openAdmin(): Promise<void> { mode.value = 'admin'; error.value = ''; reviewNotice.value = ''; try { reviewCandidates.value = await knowledgeApi.reviewCandidates() } catch (cause) { reviewCandidates.value = []; error.value = cause instanceof ApiError ? cause.message : '无法读取知识复审待办。' } }
async function completeReview(documentId: string): Promise<void> { reviewNotice.value = ''; try { await knowledgeApi.completeReview(documentId); reviewCandidates.value = reviewCandidates.value.filter((item) => item.documentId !== documentId); reviewNotice.value = '已完成复审并重新计算下一复审日期。' } catch (cause) { reviewNotice.value = cause instanceof ApiError ? cause.message : '复审操作未完成。' } }
function chooseFile(event: Event): void { const input = event.target as HTMLInputElement; importForm.value.file = input.files?.[0] ?? null }
async function submitImport(): Promise<void> { importError.value = ''; importNotice.value = ''; const value = importForm.value; const serviceCatalogItemIds = [...new Set(value.serviceCatalogItemIds.split(',').map((item) => item.trim()).filter(Boolean))]; if (!value.title.trim() || !/^[A-Z][A-Z0-9_-]{1,63}$/.test(value.categoryCode.trim()) || !serviceCatalogItemIds.length || !value.file) { importError.value = '请填写标题、合法分类编码、至少一个服务目录 ID，并选择一个待上传文件。'; return }
  submitting.value = true
  try { const tags = value.tagNames.split(',').map((item) => item.trim()).filter(Boolean).map((name) => ({ code: name.slice(1).toUpperCase().replace(/[^A-Z0-9_]/g, '_').slice(0, 63) || 'TAG', name: name.startsWith('#') ? name : `#${name}`, kind: 'STANDARD' as const })); const result = await knowledgeApi.createImport({ title: value.title.trim(), categoryCode: value.categoryCode.trim(), serviceCatalogItemIds, tags, file: value.file }); imports.value = [result.data, ...imports.value]; showImport.value = false; importNotice.value = `服务端已按当前 IAM 组织 ${result.data.owningOrganizationId} 固化归属；文件扫描通过前不能下载、解析或发布。` } catch (cause) { importError.value = cause instanceof ApiError ? cause.message : '导入请求未完成。' } finally { submitting.value = false }
}
onMounted(loadArticles)
</script>

<template>
  <div class="page-heading"><div><h2>知识库</h2><p>只展示已按当前 IAM 数据范围授权的内容；案例匹配与知识阅读不改变工单状态。</p></div><div class="knowledge-tabs"><button :class="{ active: mode === 'read' }" type="button" @click="mode = 'read'; loadArticles()">检索与阅读</button><button :class="{ active: mode === 'admin' }" type="button" @click="openAdmin">导入与审核</button></div></div>
  <p v-if="source === 'demo'" class="demo-notice">开发演示数据：仅用于界面预览；不表示知识可见范围、审核状态或文件扫描结果。</p><p v-if="error" class="form-alert form-alert--error">{{ error }}</p>
  <template v-if="mode === 'read'"><section class="panel knowledge-search"><form @submit.prevent="loadArticles"><label class="field"><span>关键词 / 标签 / 分类</span><input v-model.trim="query" maxlength="100" placeholder="例如 #核协E+、查询超时、VPN" /></label><button class="button button--primary" type="submit" :disabled="loading">{{ loading ? '检索中…' : '检索' }}</button></form><p>支持标题、摘要、分类和标签检索；不执行 AI 问答或自动处置。</p></section>
    <div class="knowledge-workspace"><aside class="panel knowledge-category-tree"><b>知识分类</b><small>仅展示当前 IAM 已授权知识的分类。</small><button type="button" :class="{ active: !selectedCategory }" @click="selectedCategory = ''">全部知识</button><button v-for="category in categories" :key="category" type="button" :class="{ active: selectedCategory === category }" @click="selectedCategory = category">› {{ category }}</button><div class="knowledge-topic-box"><b>知识专题</b><p>页面体验 · 账号权限 · 网络服务</p><small>专题的发布范围和排序规则将由知识运营服务端管理。</small></div></aside>
      <section class="knowledge-card-list"><div class="knowledge-list-toolbar"><div><b>{{ selectedCategory || '全部知识' }}</b><small>共 {{ filteredArticles.length }} 篇当前权限可读知识</small></div><span>已发布内容</span></div><article v-for="article in filteredArticles" :key="article.id" class="panel knowledge-card"><div><div class="knowledge-card__meta"><span>{{ article.category ?? '知识文档' }}</span><span>组织 {{ article.owningOrganizationId }}</span><span>v{{ article.version }}</span><span :class="`knowledge-status knowledge-status--${article.publicationStatus?.toLowerCase() ?? 'published'}`">{{ article.publicationStatus ? statusLabel[article.publicationStatus] : '已发布' }}</span><span v-if="article.sourceType">{{ article.sourceType === 'RESOLVED_CASE' ? '已解决案例沉淀' : article.sourceType === 'IMPORTED' ? '受控导入' : '人工维护' }}</span></div><h3><RouterLink :to="`/knowledge/${article.id}`">{{ article.title }}</RouterLink></h3><p>{{ article.summary ?? '服务端未返回摘要。' }}</p><div class="tag-row"><span v-for="tag in article.tags" :key="tag.code ?? tag.name" class="tag tag--muted">{{ tag.name }}</span><span v-for="catalog in article.serviceCatalogItems ?? []" :key="catalog.id" class="tag tag--blue">{{ catalog.name }}</span></div></div><RouterLink class="button button--secondary button--compact" :to="`/knowledge/${article.id}`">阅读</RouterLink></article><p v-if="!loading && !filteredArticles.length" class="panel empty-state">未找到当前权限范围内的已发布知识。</p></section>
    </div>
  </template>
  <template v-else><section class="panel knowledge-admin-summary"><div><b>导入与审核</b><span>上传后由服务端完成类型校验、隔离与恶意文件扫描；本页不解析、预览或扫描文件。</span></div><button class="button button--primary" type="button" @click="showImport = true">导入知识文档</button></section><p v-if="importNotice" class="form-alert form-alert--success">{{ importNotice }}</p><p v-if="reviewNotice" class="form-alert form-alert--success">{{ reviewNotice }}</p>
    <section class="panel"><div class="panel-header"><div><h3>知识复审待办</h3><p>仅展示到期或低评分候选；不返回正文、附件、来源工单描述或评价人身份。</p></div><span class="readonly-badge">{{ reviewCandidates.length }} 项</span></div><div class="table-scroll"><table><thead><tr><th>知识</th><th>候选原因</th><th>复审责任人 / 到期日</th><th>有用性</th><th>操作</th></tr></thead><tbody><tr v-for="candidate in reviewCandidates" :key="candidate.documentId"><td><b>{{ candidate.title }}</b><span class="table-subtext">{{ candidate.documentId }}</span></td><td>{{ candidate.reasonCode === 'REVIEW_DUE' ? '已到复审日期' : '低有用性评分' }}</td><td>{{ candidate.reviewOwnerIamUserId ?? '待指定' }}<span class="table-subtext">{{ candidate.reviewDueAt?.slice(0, 10) ?? '—' }}</span></td><td>{{ candidate.helpfulCount }} 有帮助 / {{ candidate.notHelpfulCount }} 需复审</td><td><button class="button button--secondary button--compact" type="button" @click="completeReview(candidate.documentId)">完成复审</button></td></tr><tr v-if="!reviewCandidates.length"><td colspan="5" class="table-empty">当前没有需要复审的已发布知识。</td></tr></tbody></table></div></section>
    <section class="panel"><div class="panel-header"><div><h3>本次会话提交的导入任务</h3><p>审核队列、发布、下架和版本记录由服务端权限接口控制。</p></div><span class="readonly-badge">{{ blockedImports }} 项未完成</span></div><div class="table-scroll"><table><thead><tr><th>标题 / 任务</th><th>归属组织 / 服务目录</th><th>标签</th><th>导入状态</th><th>失败原因</th></tr></thead><tbody><tr v-for="record in imports" :key="record.id"><td><b>{{ record.title }}</b><span class="table-subtext">{{ record.id }} · {{ record.requestedAt.slice(0, 16).replace('T', ' ') }}</span></td><td><span>{{ record.owningOrganizationId }}</span><small class="table-subtext">{{ record.serviceCatalogItemIds.join('、') }}</small></td><td>{{ record.tags.map((tag) => tag.name).join(' ') || '无标签' }}</td><td><span class="knowledge-status knowledge-status--pending_review">{{ record.status }}</span></td><td>{{ record.reasonCode ?? '—' }}</td></tr><tr v-if="!imports.length"><td colspan="5" class="table-empty">当前会话还没有导入任务。</td></tr></tbody></table></div><p class="scan-notice">未通过或未完成扫描的文件已隔离，禁止下载、解析、发布、索引和用于案例匹配。</p></section>
    <div v-if="showImport" class="modal-backdrop" @mousedown.self="showImport = false"><section class="action-modal" role="dialog" aria-modal="true" aria-label="导入知识文档"><div class="modal-heading"><div><span class="eyebrow">知识库管理</span><h3>导入知识文档</h3><p>归属组织由服务端当前 IAM 主组织固化；文件直传隔离区。</p></div><button class="modal-close" type="button" aria-label="关闭" @click="showImport = false">×</button></div><form class="action-form" @submit.prevent="submitImport"><label class="field"><span>标题 <b>*</b></span><input v-model.trim="importForm.title" maxlength="200" /></label><label class="field"><span>分类编码 <b>*</b></span><input v-model.trim="importForm.categoryCode" maxlength="64" placeholder="例如 BROWSER" /><small>采用平台标准分类编码；大写字母开头。</small></label><label class="field"><span>服务目录 ID <b>*</b></span><input v-model.trim="importForm.serviceCatalogItemIds" maxlength="1000" placeholder="逗号分隔，例如 SC-browser-performance" /><small>服务端逐个校验已发布目录和当前组织数据范围；至少填写一个。</small></label><label class="field"><span>展示标签</span><input v-model.trim="importForm.tagNames" maxlength="500" placeholder="逗号分隔，例如 #ERP,#查询超时" /><small>服务端会校验标签格式。</small></label><label class="field"><span>待上传文件 <b>*</b></span><input type="file" @change="chooseFile" /><small>选择不表示已上传、已扫描或可发布；不支持文件预览。</small></label><p v-if="importError" class="form-alert form-alert--error">{{ importError }}</p><div class="modal-actions"><button class="button button--secondary" type="button" :disabled="submitting" @click="showImport = false">取消</button><button class="button button--primary" type="submit" :disabled="submitting">{{ submitting ? '提交中…' : '提交至隔离区' }}</button></div></form></section></div>
  </template>
</template>
