<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ApiError } from '@/api/client'
import { lifecycleApprovalPolicyApi, type LifecycleApprovalPolicy, type LifecycleApprovalPolicyInput } from '@/api/approval-policies'
import { useSessionStore } from '@/stores/session'

const session = useSessionStore(); const rows = ref<LifecycleApprovalPolicy[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(''); const notice = ref(''); const open = ref(false); const editing = ref<LifecycleApprovalPolicy>()
const canManage = computed(() => session.authorization?.roles.includes('PLATFORM_ADMIN') ?? false)
const labels: Record<string, string> = { HOLD: '挂起', ESCALATE: '升级', CANCEL: '撤销', REOPEN: '重开', ASSIGN: '分派', ACCEPT: '受理', RESOLVE: '解决', CLOSE: '关闭' }
const form = reactive<LifecycleApprovalPolicyInput>({ name: '', action: 'HOLD', candidateRoles: ['ROLE_SERVICE_MANAGER', 'ROLE_PLATFORM_ADMIN'], decisionMode: 'ANY_ONE', approvalThresholdPercent: 100, timeoutMinutes: 1440, timeoutPolicyVersion: 'DEFAULT-24H-V1', escalationPolicyVersion: 'AUDIT-ONLY-V1' })
function reset() { editing.value = undefined; Object.assign(form, { name: '', action: 'HOLD', serviceCatalogItemId: '', priority: undefined, candidateRoles: ['ROLE_SERVICE_MANAGER', 'ROLE_PLATFORM_ADMIN'], decisionMode: 'ANY_ONE', approvalThresholdPercent: 100, timeoutMinutes: 1440, timeoutPolicyVersion: 'DEFAULT-24H-V1', escalationPolicyVersion: 'AUDIT-ONLY-V1', expectedVersion: undefined }) }
function edit(row?: LifecycleApprovalPolicy) { if (!row) reset(); else { editing.value = row; Object.assign(form, { ...row, serviceCatalogItemId: row.serviceCatalogItemId ?? '', candidateRoles: [...row.candidateRoles], expectedVersion: row.version }) }; open.value = true; error.value = ''; notice.value = '' }
function toggle(role: 'ROLE_SERVICE_MANAGER' | 'ROLE_PLATFORM_ADMIN') { form.candidateRoles = form.candidateRoles.includes(role) ? form.candidateRoles.filter(item => item !== role) : [...form.candidateRoles, role] }
async function load() { loading.value = true; error.value = ''; try { rows.value = await lifecycleApprovalPolicyApi.list() } catch (cause) { error.value = cause instanceof ApiError ? cause.message : '无法读取审批策略。' } finally { loading.value = false } }
async function save() { if (!form.name.trim() || !form.candidateRoles.length) { error.value = '请填写策略名称并至少选择一个候选角色。'; return }; saving.value = true; error.value = ''; try { const input = { ...form, name: form.name.trim(), serviceCatalogItemId: form.serviceCatalogItemId?.trim() || undefined, candidateRoles: [...form.candidateRoles], approvalThresholdPercent: form.decisionMode === 'QUORUM' ? form.approvalThresholdPercent : 100 }; if (editing.value) await lifecycleApprovalPolicyApi.update(editing.value.id, input); else await lifecycleApprovalPolicyApi.create(input); notice.value = '草稿已保存，发布前不会影响线上审批。'; open.value = false; await load() } catch (cause) { error.value = cause instanceof ApiError ? cause.message : '保存失败，策略未改变。' } finally { saving.value = false } }
async function change(row: LifecycleApprovalPolicy, operation: 'publish' | 'retire') { saving.value = true; error.value = ''; try { await lifecycleApprovalPolicyApi[operation](row.id, row.version); notice.value = operation === 'publish' ? '策略已发布，后续审批将冻结该版本。' : '策略已停用；已发起审批继续按冻结快照处理。'; await load() } catch (cause) { error.value = cause instanceof ApiError ? cause.message : '操作失败，策略未改变。' } finally { saving.value = false } }
onMounted(async () => { try { await session.loadCurrentUser() } catch { /* server remains authoritative */ }; await load() })
</script>
<template>
  <div class="page-heading"><div><h2>生命周期审批策略</h2><p>草稿、发布、停用三态；服务端解析并冻结候选身份。</p></div><button v-if="canManage" class="button button--primary" @click="edit()">新建草稿</button></div>
  <p class="projection-notice"><b>安全控制：</b>仅平台管理员可维护；候选角色为服务端白名单，申请人自动排除；同一动作和匹配范围只能有一个生效策略。</p><p v-if="notice" class="form-alert form-alert--success">{{ notice }}</p><p v-if="error" class="form-alert form-alert--error">{{ error }}</p>
  <section class="panel table-panel"><div class="panel-header"><div><h3>策略版本</h3><p>目录和优先级为空表示该维度不限定；运行中审批不会被后续配置覆盖。</p></div></div><div v-if="loading" class="compact-loading">正在读取策略…</div><div v-else class="table-scroll"><table><thead><tr><th>策略 / 动作</th><th>匹配范围</th><th>决策方式</th><th>超时版本</th><th>版本</th><th>状态</th><th v-if="canManage">操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><b>{{ row.name }}</b><small class="table-subtext">{{ labels[row.action] }} · {{ row.action }}</small></td><td>{{ row.serviceCatalogItemId || '全部目录' }}<small class="table-subtext">{{ row.priority || '全部优先级' }}</small></td><td>{{ row.decisionMode === 'ANY_ONE' ? '或签' : row.decisionMode === 'ALL_OF' ? '会签' : `比例会签 ${row.approvalThresholdPercent}%` }}</td><td>{{ row.timeoutMinutes }} 分钟<small class="table-subtext">{{ row.timeoutPolicyVersion }}</small></td><td>v{{ row.version }}</td><td><span class="tag" :class="row.status === 'PUBLISHED' ? 'tag--green' : row.status === 'DRAFT' ? 'tag--blue' : 'tag--muted'">{{ row.status === 'PUBLISHED' ? '已发布' : row.status === 'DRAFT' ? '草稿' : '已停用' }}</span></td><td v-if="canManage"><div class="trusted-link-actions"><button v-if="row.status === 'DRAFT'" class="button button--secondary" :disabled="saving" @click="edit(row)">编辑</button><button v-if="row.status === 'DRAFT'" class="button button--primary" :disabled="saving" @click="change(row, 'publish')">发布</button><button v-if="row.status === 'PUBLISHED'" class="button button--secondary" :disabled="saving" @click="change(row, 'retire')">停用</button></div></td></tr></tbody></table></div><p v-if="!loading && !rows.length" class="compact-empty">暂无当前可查看的审批策略。</p></section>
  <section v-if="open" class="panel form-panel"><div class="panel-header"><div><h3>{{ editing ? '编辑审批策略草稿' : '新建审批策略草稿' }}</h3><p>浏览器不会选择或回传候选 IAM 用户。</p></div></div><form class="form-grid" @submit.prevent="save"><label class="field"><span>策略名称 <b>*</b></span><input v-model="form.name" maxlength="120" required /></label><label class="field"><span>工单动作</span><select v-model="form.action"><option v-for="(label, key) in labels" :key="key" :value="key">{{ label }} · {{ key }}</option></select></label><label class="field"><span>服务目录 ID</span><input v-model="form.serviceCatalogItemId" maxlength="128" placeholder="留空：全部目录" /></label><label class="field"><span>优先级</span><select v-model="form.priority"><option :value="undefined">全部优先级</option><option v-for="priority in ['P1','P2','P3','P4']" :key="priority" :value="priority">{{ priority }}</option></select></label><div class="field"><span>候选角色 <b>*</b></span><div class="checkbox-field"><label><input type="checkbox" :checked="form.candidateRoles.includes('ROLE_SERVICE_MANAGER')" @change="toggle('ROLE_SERVICE_MANAGER')" /> 服务平台主管</label><label><input type="checkbox" :checked="form.candidateRoles.includes('ROLE_PLATFORM_ADMIN')" @change="toggle('ROLE_PLATFORM_ADMIN')" /> 平台管理员</label></div></div><label class="field"><span>决策方式</span><select v-model="form.decisionMode"><option value="ANY_ONE">或签</option><option value="ALL_OF">会签</option><option value="QUORUM">比例会签</option></select></label><label v-if="form.decisionMode === 'QUORUM'" class="field"><span>通过阈值（%）</span><input v-model.number="form.approvalThresholdPercent" type="number" min="1" max="100" required /></label><label class="field"><span>超时（分钟）</span><input v-model.number="form.timeoutMinutes" type="number" min="1" max="43200" required /></label><label class="field"><span>超时策略版本</span><input v-model="form.timeoutPolicyVersion" maxlength="64" required /></label><label class="field"><span>升级策略版本</span><input v-model="form.escalationPolicyVersion" maxlength="64" required /></label><div class="form-actions"><button class="button button--secondary" type="button" :disabled="saving" @click="open = false">取消</button><button class="button button--primary" type="submit" :disabled="saving">{{ saving ? '保存中…' : '保存草稿' }}</button></div></form></section>
</template>
