package cn.servicehub.localauth.application;

import cn.servicehub.access.domain.BackofficeAccess;
import cn.servicehub.access.domain.BackofficeAccessRepository;
import cn.servicehub.access.domain.BackofficeDataScope;
import cn.servicehub.audit.AuditEvent;
import cn.servicehub.audit.AuditEventPublisher;
import cn.servicehub.localauth.domain.LocalAccount;
import cn.servicehub.localauth.domain.LocalAccountPage;
import cn.servicehub.localauth.domain.LocalAccountProjectionWriter;
import cn.servicehub.localauth.domain.LocalAccountRepository;
import cn.servicehub.security.CurrentUser;
import cn.servicehub.security.CurrentUserProvider;
import cn.servicehub.servicesystem.domain.ServiceSystemRepository;
import java.time.Clock;
import java.time.Instant;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.slf4j.MDC;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class LocalAccountAdminService {
    private static final Set<String> ASSIGNABLE=Set.of("ROLE_FIRST_LINE_SUPPORT","ROLE_SECOND_LINE_SUPPORT","ROLE_APPROVER","ROLE_SERVICE_MANAGER","ROLE_SLA_MANAGER","ROLE_PLATFORM_ADMIN","ROLE_AUDITOR");
    private final LocalAccountRepository accounts;private final LocalAccountProjectionWriter projections;private final BackofficeAccessRepository access;private final ServiceSystemRepository systems;private final CurrentUserProvider users;private final PasswordEncoder passwords;private final AuditEventPublisher audit;private final Clock clock=Clock.systemUTC();
    public LocalAccountAdminService(LocalAccountRepository accounts,LocalAccountProjectionWriter projections,BackofficeAccessRepository access,ServiceSystemRepository systems,CurrentUserProvider users,PasswordEncoder passwords,AuditEventPublisher audit){this.accounts=accounts;this.projections=projections;this.access=access;this.systems=systems;this.users=users;this.passwords=passwords;this.audit=audit;}

    public AccountPage list(int page,int pageSize,String query,String status){requireAdmin();if(page<1||pageSize<1||pageSize>100)throw new IllegalArgumentException();LocalAccountPage result=accounts.search(page,pageSize,query,normalizedStatus(status),clock.instant());return new AccountPage(result.items().stream().map(this::view).toList(),page,pageSize,result.total());}
    @Transactional public AccountView create(CreateCommand command){CurrentUser actor=requireAdmin();validate(command.organizationId(),command.roles(),command.systemCodes(),command.password());String normalized=LocalAuthenticationService.normalizeLogin(command.loginName());if(normalized==null)throw new IllegalArgumentException();if(accounts.findByNormalizedLoginName(normalized).isPresent())throw new LocalAccountConflictException();Instant now=clock.instant();String id="local-u-"+UUID.randomUUID();String display=clean(command.displayName(),100);String login=command.loginName().strip();LocalAccount created=new LocalAccount(id,login,normalized,passwords.encode(command.password()),display,command.organizationId(),true,0,null,now,1,1,actor.iamUserId(),actor.iamUserId(),now,now);projections.upsert(id,login,display,command.organizationId(),true,1,now);accounts.insert(created);saveAccess(id,true,command.roles(),command.systemCodes(),0,actor.iamUserId(),now);audit(actor,"LOCAL_ACCOUNT_CREATED",id,command.reason(),Map.of("enabled","true"));return view(created);}
    @Transactional public AccountView update(String id,UpdateCommand command){CurrentUser actor=requireAdmin();if(actor.iamUserId().equals(id))throw new AccessDeniedException("Administrators cannot alter their own account authorization");LocalAccount current=required(id);if(current.version()!=command.version())throw new LocalAccountConflictException();validate(command.organizationId(),command.roles(),command.systemCodes(),null);if(!command.enabled()&&access.findByIamUserId(id).filter(BackofficeAccess::enabled).filter(value->value.roleCodes().contains("ROLE_PLATFORM_ADMIN")).isPresent()&&access.countEnabledUsersWithRole("ROLE_PLATFORM_ADMIN")<=1)throw new IllegalArgumentException();Instant now=clock.instant();long sessionVersion=current.sessionVersion()+(command.enabled()==current.enabled()?0:1);LocalAccount changed=new LocalAccount(id,current.loginName(),current.normalizedLoginName(),current.passwordHash(),clean(command.displayName(),100),command.organizationId(),command.enabled(),current.failedLoginCount(),command.enabled()?current.lockedUntil():null,current.passwordChangedAt(),sessionVersion,current.version()+1,current.createdBy(),actor.iamUserId(),current.createdAt(),now);accounts.update(changed,current.version());projections.upsert(id,changed.loginName(),changed.displayName(),changed.organizationId(),changed.enabled(),changed.version(),now);BackofficeAccess old=access.findByIamUserId(id).orElse(null);saveAccess(id,command.enabled(),command.roles(),command.systemCodes(),old==null?0:old.version(),actor.iamUserId(),now);audit(actor,"LOCAL_ACCOUNT_UPDATED",id,command.reason(),Map.of("enabled",Boolean.toString(changed.enabled())));return view(changed);}
    @Transactional public AccountView resetPassword(String id,long expectedVersion,String password,String reason){CurrentUser actor=requireAdmin();validatePassword(password);LocalAccount current=required(id);if(current.version()!=expectedVersion)throw new LocalAccountConflictException();Instant now=clock.instant();LocalAccount changed=new LocalAccount(id,current.loginName(),current.normalizedLoginName(),passwords.encode(password),current.displayName(),current.organizationId(),current.enabled(),0,null,now,current.sessionVersion()+1,current.version()+1,current.createdBy(),actor.iamUserId(),current.createdAt(),now);accounts.update(changed,current.version());projections.upsert(id,changed.loginName(),changed.displayName(),changed.organizationId(),changed.enabled(),changed.version(),now);audit(actor,"LOCAL_ACCOUNT_PASSWORD_RESET",id,reason,Map.of("sessionsInvalidated","true"));return view(changed);}
    @Transactional public void disable(String id,long expectedVersion,String reason){CurrentUser actor=requireAdmin();if(actor.iamUserId().equals(id))throw new AccessDeniedException("Administrators cannot disable their own account");LocalAccount current=required(id);if(current.version()!=expectedVersion)throw new LocalAccountConflictException();BackofficeAccess currentAccess=access.findByIamUserId(id).orElse(null);if(currentAccess!=null&&currentAccess.enabled()&&currentAccess.roleCodes().contains("ROLE_PLATFORM_ADMIN")&&access.countEnabledUsersWithRole("ROLE_PLATFORM_ADMIN")<=1)throw new IllegalArgumentException();Instant now=clock.instant();LocalAccount changed=new LocalAccount(id,current.loginName(),current.normalizedLoginName(),current.passwordHash(),current.displayName(),current.organizationId(),false,current.failedLoginCount(),null,current.passwordChangedAt(),current.sessionVersion()+1,current.version()+1,current.createdBy(),actor.iamUserId(),current.createdAt(),now);accounts.update(changed,current.version());projections.upsert(id,changed.loginName(),changed.displayName(),changed.organizationId(),false,changed.version(),now);if(currentAccess!=null)access.save(new BackofficeAccess(id,false,currentAccess.roleCodes(),currentAccess.dataScopes(),currentAccess.version()+1,now),currentAccess.version(),actor.iamUserId());audit(actor,"LOCAL_ACCOUNT_DISABLED",id,reason,Map.of());}

    @Transactional public AccountView bootstrap(String login,String password,String display,String organization,String organizationName){if(accounts.count()!=0)throw new LocalAccountConflictException();Instant now=clock.instant();if(organization==null||!organization.matches("^[A-Za-z0-9._:-]{1,128}$"))throw new IllegalArgumentException();projections.ensureLocalOrganization(organization,clean(organizationName,200),now);validate(organization,Set.of("ROLE_PLATFORM_ADMIN"),Set.of(),password);String normalized=LocalAuthenticationService.normalizeLogin(login);if(normalized==null)throw new IllegalArgumentException();String id="local-u-"+UUID.randomUUID();LocalAccount account=new LocalAccount(id,login.strip(),normalized,passwords.encode(password),clean(display,100),organization,true,0,null,now,1,1,"LOCAL_AUTH_BOOTSTRAP","LOCAL_AUTH_BOOTSTRAP",now,now);projections.upsert(id,account.loginName(),account.displayName(),organization,true,1,now);accounts.insert(account);saveAccess(id,true,Set.of("ROLE_PLATFORM_ADMIN"),Set.of(),0,"LOCAL_AUTH_BOOTSTRAP",now);audit.publish(new AuditEvent(now,"startup","LOCAL_AUTH_BOOTSTRAP","LOCAL_ACCOUNT_BOOTSTRAPPED","local_account",id,Map.of("organizationId",organization)));return view(account);}
    @Transactional public void seedLocalDevelopment(String id,String login,String password,String display,String organization,Set<String> roles,Set<String> systemCodes){String normalized=LocalAuthenticationService.normalizeLogin(login);if(normalized==null||accounts.findByNormalizedLoginName(normalized).isPresent())return;validate(organization,roles,systemCodes,password);Instant now=clock.instant();LocalAccount account=new LocalAccount(id,login,normalized,passwords.encode(password),clean(display,100),organization,true,0,null,now,1,1,"LOCAL_DEV","LOCAL_DEV",now,now);projections.upsert(id,login,account.displayName(),organization,true,1,now);accounts.insert(account);saveAccess(id,true,roles,systemCodes,0,"LOCAL_DEV",now);audit.publish(new AuditEvent(now,"startup","LOCAL_DEV","LOCAL_ACCOUNT_DEVELOPMENT_SEEDED","local_account",id,Map.of("roles",Integer.toString(roles.size()),"systems",Integer.toString(systemCodes.size()))));}
    private void validate(String org,Set<String> roles,Set<String> systemCodes,String password){if(org==null||!org.matches("^[A-Za-z0-9._:-]{1,128}$")||!projections.activeOrganizationExists(org))throw new IllegalArgumentException();Set<String> normalized=normalizeRoles(roles);if(!ASSIGNABLE.containsAll(normalized))throw new IllegalArgumentException();for(String code:safe(systemCodes))if(code==null||systems.findByCode(code).isEmpty())throw new IllegalArgumentException();if(password!=null)validatePassword(password);}
    private void validatePassword(String password){if(password==null||password.length()<12||password.length()>128)throw new IllegalArgumentException();}
    private void saveAccess(String id,boolean enabled,Set<String> roles,Set<String> systemCodes,long version,String actor,Instant now){Set<BackofficeDataScope> scopes=new LinkedHashSet<>();for(String code:safe(systemCodes))scopes.add(new BackofficeDataScope("SERVICE_SYSTEM",code));access.save(new BackofficeAccess(id,enabled,normalizeRoles(roles),scopes,version+1,now),version,actor);}
    private AccountView view(LocalAccount account){BackofficeAccess grant=access.findByIamUserId(account.id()).orElse(null);Set<String> roles=new LinkedHashSet<>();roles.add("REQUESTER");Set<String> systemCodes=new LinkedHashSet<>();if(grant!=null){grant.roleCodes().stream().map(value->value.replaceFirst("^ROLE_","")).sorted().forEach(roles::add);grant.dataScopes().stream().filter(value->"SERVICE_SYSTEM".equals(value.scopeType())).map(BackofficeDataScope::scopeId).sorted().forEach(systemCodes::add);}return new AccountView(account.id(),account.loginName(),account.displayName(),account.organizationId(),account.enabled(),account.lockedUntil(),account.failedLoginCount(),roles,systemCodes,account.version(),account.updatedAt());}
    private CurrentUser requireAdmin(){CurrentUser user=users.requireCurrentUser();if(!user.authorities().contains("ROLE_PLATFORM_ADMIN"))throw new AccessDeniedException("Platform administrator authority is required");return user;}
    private LocalAccount required(String id){return accounts.findById(id).orElseThrow(LocalAccountNotFoundException::new);}private static String clean(String value,int max){if(value==null)throw new IllegalArgumentException();String clean=value.strip();if(clean.isBlank()||clean.length()>max)throw new IllegalArgumentException();return clean;}private static Set<String> safe(Set<String> value){return value==null?Set.of():Set.copyOf(value);}private static Set<String> normalizeRoles(Set<String> value){Set<String> result=new LinkedHashSet<>();for(String role:safe(value)){if(role==null)throw new IllegalArgumentException();String normalized=role.startsWith("ROLE_")?role:"ROLE_"+role;if(!"ROLE_REQUESTER".equals(normalized))result.add(normalized);}return Set.copyOf(result);}private static String normalizedStatus(String value){if(value==null||value.isBlank())return "ALL";String status=value.toUpperCase(java.util.Locale.ROOT);if(!Set.of("ALL","ACTIVE","LOCKED","DISABLED").contains(status))throw new IllegalArgumentException();return status;}
    private void audit(CurrentUser actor,String action,String id,String reason,Map<String,String> attributes){String cleanReason=reason==null?"":reason.strip();if(cleanReason.length()>500)throw new IllegalArgumentException();var detail=new java.util.HashMap<>(attributes);if(!cleanReason.isBlank())detail.put("reason",cleanReason);audit.publish(new AuditEvent(clock.instant(),MDC.get("requestId")==null?"system":MDC.get("requestId"),actor.iamUserId(),action,"local_account",id,detail));}
    public record CreateCommand(String loginName,String displayName,String organizationId,String password,Set<String> roles,Set<String> systemCodes,String reason){}
    public record UpdateCommand(long version,String displayName,String organizationId,boolean enabled,Set<String> roles,Set<String> systemCodes,String reason){}
    public record AccountView(String id,String loginName,String displayName,String organizationId,boolean enabled,Instant lockedUntil,int failedLoginCount,Set<String> roles,Set<String> systemCodes,long version,Instant updatedAt){}
    public record AccountPage(java.util.List<AccountView> items,int page,int pageSize,long total){}
}
